### ISSUE TITLE
Dynamic linking of Scala code

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#121]
Currently Scala Native only supports dynamic linking with C libraries. All of the Scala code has to be statically known at compile-time. We need to explore the space of dynamic linking of Scala code, it might still be feasible in some form.

**Comment by mdedetrich** [comment]
Since scala-native plans to have full TCO (if it already doesn't have so), this can complicate matters in regards to making dynamically linked libraries. Rust, for example, had to drop support for full TCO (see https://mail.mozilla.org/pipermail/rust-dev/2013-April/003557.html) for such reasons.

I am not sure if its possible to have an ABI that respects full TCO without throwing performance out the window (or doing some crazy runtime stuff).

The other issue is, that Scala code tends to use generics which can't be erased really heavily, which means optimising them can be quite hard. Not a problem on platforms like JVM, where JIT takes care of everything, but make a JIT appears to be out of scope for scala-native.

@sjrd had a good idea in regards to having a scala-native version of `@JSExport`, but I don't think it would solve everything

**Comment by mdedetrich** [comment]
Also another important link regarding TCO http://llvm.org/docs/CodeGenerator.html#tail-call-optimization. According to the docs, you need to use a specific calling convention if you want full TCO (which isn't the C calling convention), quoting the docs

>  fastcc, cc 10 (GHC calling convention) or cc 11 (HiPE calling convention)

**Comment by densh** [comment]
This hasn't really come up for a really long time and very few people expressed interest in this, I'm closing it for now.

**Comment by mdedetrich** [comment]
@densh Yeah, I think if people wan't dynamically linked libraries, then just using the JVM is the best option for now (its heavily optimised for this scenario). Its also not really a niche that scala-native should be targeting (we should prioritise things that the JVM is really bad at, i.e. latency/startup time/pluggable gc's/low level code/C interopt)
