### ISSUE TITLE
scala-native apps should all be GPLv2

### ISSUE THREAD

**Issue by fommil** [scala-native/scala-native#1230]
Sorry if this sounds like a massive troll, it really isn't, but I don't think in the light of https://www.wired.com/story/the-case-that-never-ends-oracle-wins-latest-round-vs-google/ we can legitimately claim that scala-native produces anything except GPLv2+cpe applications since it is **statically** linking against JDK APIs that have been implemented by Harmony in a way that violates the court decision above.

One possible way to fix this is to allow **dynamic** linking to a `libjdk` and then interpreting "classpath" as dynamic linking. But you'd need to get explicit confirmation from Oracle to confirm that they interpret the "classpath" in this way in your context.

**Comment by fommil** [comment]
further precedent in https://github.com/oracle/graal project

**Comment by densh** [comment]
So far in hearings of Google vs Oracle it has been ruled that:

1. API's Sequence, Structure and Organization (i.e. names, types, etc) are copyrightable.
2. Google's has violated fair use of Oracle's copyrighted APIs in Android.

In case of Scala Native, we may not use Oracle's original GPL code (because it's in incompatible language), and thus we **must** reimplement JDK APIs as Scala depends on them to work. The bare fact of reimplementation, **no matter the license on the source code** might or might not be fair use of Oracle's copyrighted APIs. 

Scala Native developers have never touched any of the GPL code in JDK or any other GPL project (which is written and required from all contributors as per contributing guidelines published on our website), and thus there is literally no reason for it to be GPL. Changing license to GPL would not protect us from potential copyright violation on the design of JDK APIs as we'll still be reimplementing a copyrighted API. 

If the fact that we ported classes from Apache Harmony (which has Scala-compatible license) turns out to be an issue, we would discard those implementations and either reimplement them from scratch, or stop supporting them if they are accidental.

Scala Native would only change license, if Scala itself changes license. I hope we don't have to restart this discussion every other month.

**Comment by fommil** [comment]
@densh I mean this sincerely, you're playing with fire and you really need to talk to a specialist lawyer about all of this. You don't understand what you think you understand.
