### ISSUE TITLE
Missing methods in `Date`

### ISSUE THREAD

**Issue by cquiroz** [scala-native/scala-native#1247]
I'm hitting link errors with the following methods in `java.util.Date`

```
[error] cannot link: @java.util.Date$
[error] cannot link: @java.util.Date$::UTC_i32_i32_i32_i32_i32_i32_i64
[error] cannot link: @java.util.Date::getDay_i32
[error] cannot link: @java.util.Date::getHours_i32
[error] cannot link: @java.util.Date::getMinutes_i32
[error] cannot link: @java.util.Date::getMonth_i32
[error] cannot link: @java.util.Date::getSeconds_i32
[error] cannot link: @java.util.Date::getYear_i32
```

**Comment by LeeTibbert** [comment]
@cquiroz  As a result of our conversation on gitter a few days ago, I believe that this issue 
can be closed.  I have been told that it is bad form to close someone else's issue, so I think
you have the ball.  Just trying to reduce the Issue backlog here.  Please let me know if  I missed something.

For the gentle reader (and my future self). the essence of the conversation was that a comment
in javalib/src/main/scala/java/util/Date.scala said that deprecated methods were not ported. A quick check on the InterWeb revealed that these routines have been deprecated since Java 1.1 or so.
The java doc says to use Calendar replacements.  GregorianCalendar.scala exists but I did not check if these routines are there. It seemed like the C strftime() routine & friend were a good enough workaround for you.

**Comment by cquiroz** [comment]
@LeeTibbert Thanks a lot for your example and support.I haven't been able to test this yet but I think it is the right  solution rather than doing a full implementation of all those legacy API
