### ISSUE TITLE
Better GC

### ISSUE THREAD

**Issue by ebruchez** [scala-native/scala-native#128]
Adding this as a backlog idea.

[sgen](http://www.mono-project.com/docs/advanced/garbage-collector/sgen/) is Mono's newish garbage collector, introduced to replace the old Boehm. It is a generational gc, and since it works for Mono, I would think it could fit the bill for Scala Native as well.

Here is the [source code](https://github.com/mono/mono/tree/c642d898a4345554751f163ed3714fd2bf012fbe/mono/sgen). It appears to under the MIT license.

**Comment by sirinath** [comment]
IBM J9 GC is available through Eclipse OMR. So is the Core.Net and .Net LLILC. Please evaluate and choose the most performant of the GCs than choosing one arbitrarily.

**Comment by ebruchez** [comment]
Just googling a bit:

- [OMR gc](https://github.com/eclipse/omr/tree/master/gc), under Eclipse Public License/Apache
- [CoreCLR gc](https://github.com/dotnet/coreclr/tree/master/src/gc), under MIT license

I agree it would be ideal to choose the best one. Figuring out which one that is might not be easy.

**Comment by sirinath** [comment]
LLILC refs docs about gc: https://github.com/dotnet/llilc/blob/master/Documentation/llilc-gc-transition.md, https://github.com/dotnet/llilc/blob/master/Documentation/llilc-gc.md

**Comment by densh** [comment]
Just a minor clarification: it's possible to have a GC derived from one of the existings ones, but it's unlikely that anything is going to be as reusable as Boehm GC. This is due to the fact that efficient GCs are usually tightly coupled to the underlying managed runtime they're meant for. For "good" GC will probably study existing solutions and come up with our own thing that takes internals of SN into account.

**Comment by sirinath** [comment]
In Which case the best GC algo is in the Azul Zing VM which is not open sourced through. OCaml GC algo is pretty good I believe but have to dig deep. Also there is [MPS](http://www.ravenbrook.com/project/mps/) which is not under a permisive license through but may be worth while to study. The best situation would be if you can upstream the GC to the LLVM project which means perhaps more contributors and also maintainability such that it does not break every time LLVM updates.

**Comment by ebruchez** [comment]
Adding reference to [Android gc](https://android.googlesource.com/platform/art/+/master/runtime/gc/) for consideration as well.

**Comment by mstoodle** [comment]
Just a quick hopefully non offensive plug for the Eclipse OMR GC: the Eclipse OMR GC technology has been integrated underneath CRuby, CPython, SOM++ (Smalltalk VM that uses C++ objects), and the IBM J9 Java Virtual Machine: in each case, using the native object model by implementing what's called a "language glue layer". It could be just what you're looking for. And if it's not, we may be able to help to improve the fit since reusable technology is what the OMR project is all about.

**Comment by densh** [comment]
@mstoodle So far Eclipse OMR looks like the best option I've seen to date. I'm really interested in trying it out some time in the near future, once we're done with basic language & tooling support.

**Comment by sirinath** [comment]
Also the [following proposal](https://github.com/scalacenter/advisoryboard/blob/master/proposals/001-native-scala-for-spark.md) also seeks non GC based approach for memory management. (`(3) provide a platform to explore non-GC based approaches to memory management`). So perhaps non GC approaches also should be fully explored where GC overhead is not acceptable.

**Comment by sirinath** [comment]
Proposed non GC enhancements in D: https://wiki.dlang.org/DIP69, http://forum.dlang.org/post/etjuormplgfbomwdrurp@forum.dlang.org

**Comment by densh** [comment]
I think D is a poor example to take hints from in terms of memory management. The author of the language describes the situation as (emphasis on the last sentence is mine) : 

> **Weak story about D's relationship to garbage collection.** GC is a great invention, but the decision to use it for D has instantly alienated a core market - existing C and C++ programmers. For those, the party line has historically been "Don't want GC? No problem! You can use D with RAII or manual management style as well!" Though true, that's next to useless because there's little support in the standard library for alternative memory management styles, which means the putative user would need to start with the language stripped down to the studs and create all the core infrastructure. Also, for those who are okay with using a GC, the quality of its implementation is lackluster. *Overall it could be said that D has the downsides of GC but doesn't enjoy its benefits.*

https://www.quora.com/Which-language-has-the-brightest-future-in-replacement-of-C-between-D-Go-and-Rust-And-Why/answer/Andrei-Alexandrescu

Scala is GC-ed language first and foremost. All of the existing libraries assume GC. We're not going to repeat the same mistakes. Exploration of alternative memory management techniques is not the main focus of the project.

**Comment by sirinath** [comment]
How does [SCP-001](https://github.com/scalacenter/advisoryboard/blob/master/proposals/001-native-scala-for-spark.md) supported as it is directly related SN?

**Comment by sirinath** [comment]
[Go’s march to low-latency GC](https://blog.twitch.tv/gos-march-to-low-latency-gc-a6fa96f06eb7)

**Comment by sirinath** [comment]
https://github.com/eriksvedang/Carp

**Comment by sirinath** [comment]
http://gchandbook.org/

**Comment by densh** [comment]
@sirinath Can you please put all of your links into a single comment as a list of items?

**Comment by DemiMarie** [comment]
Another option: write a bespoke GC, either in a low-level language (Rust?) or in Scala itself.

But that would be a lot of work.

**Comment by benjamingeer** [comment]
Food for thought: the limitations of Haskell's parallel, but not current, stop-the-world GC: https://blog.pusher.com/latency-working-set-ghc-gc-pick-two/

**Comment by Mirimoss** [comment]
I find the statement "Scala is GC-ed language first and foremost" quite bizarre. I never thought about GC when I first engaged with Scala. The reality was that Scala ran on the JVM and that was a "given". 

Unfortunately, when you work on memory intensive projects - that translates into the equivalent of "technical debt". You will inevitably encounter a full GC - and unless you are omni-potent - you will soon suffer the unpredictable and emotional reactions of gods that have been put to sleep for 75 seconds.

There are potential workarounds - but they are just that - and they won't scale as memory expansion outstrips single threaded CPU capacity.

So please! Lets clean up as we go. Not just shift the garbage into a hole in the ground that will hopefully be removed by someone at some point in the future when their coffee is lukewarm.

Enabling Scala-native to scale and provide deterministic behaviour through a reference counted GC mechanism will be a critical competitive advantage. Otherwise I will stick to C++.

**Comment by densh** [comment]
@Mirimoss Reference counting can be a foundation for a high-performance garbage collector and we do not dismiss it as an option. The only issue is that it must also handle object cycles automatically as those are extremely common in Scala. In other words we can't have Objective-C/Swift-like reference counting but something along the lines of Python-like reference-counting with a cycle-collector is possible.

**Comment by jesnor** [comment]
Reference counting with cycle collector is exactly what [Kotlin native](https://github.com/JetBrains/kotlin-native) is using. Maybe it would be good to work together with them on a common GC.

**Comment by ousado** [comment]
Here's an interesting design document regarding a future LuaJIT 3.0 GC:
http://wiki.luajit.org/New-Garbage-Collector

**Comment by densh** [comment]
**Update:** this issue is going to be fixed by https://github.com/scala-native/scala-native/pull/726. More details to come at ScalaDays CPH, stay tuned.

**Comment by densh** [comment]
We're currently as ScalaDays, here is a very short summary of the state of our current immix prototype (slides to be posted online soon): 

<img width="1021" alt="screen shot 2017-06-01 at 09 26 51" src="https://cloud.githubusercontent.com/assets/320966/26669215/4b706bc4-46ad-11e7-9951-c4eb3c50593d.png">

Initial performance evaluation results looks rather promising, it seems like we're going to stick with it for some time. Immix is going to be available via an opt-in option in 0.3 and will become the default once implementation matures a bit.
