### ISSUE TITLE
Make immix heap size configurable

### ISSUE THREAD

**Issue by jokade** [scala-native/scala-native#1312]
The size of the memory chunks `mmap`ed by immix (and GC=`none`) seems to be too large for iOS devices.

`Heap_getMemoryLimit()` returns the full RAM size, and then `mmap` is called twice with this size (each for `smallHeap` and `largeHeap`). The second call to `mmap` returns `0xFFFFFFFF`which results in `Heap_mapAndAlign` returning a `NULL` ptr, which is not checked in the subsequent call to `LargeAllocator_Init()`:
https://github.com/scala-native/scala-native/blob/28a6d64525ef3ff640fffd26057921101975d68d/nativelib/src/main/resources/gc/immix/Heap.c#L66-L68

**Comment by densh** [comment]
@jokade Would adding an equivalent of -Xms/-Xmx setting on JVM fix the issue for you?

Double heap size reservation is an implementation artifact that we should totally address. Currently, large and small subsets of heaps have completely disjoint subheap areas but it's just an implementation artifact. They can (and should) coexist in a single memory area. 

Virtually reserving contiguous area of the max heap size is necessary due to conservative heap scanning. If you know that heap is a monolithic memory area, then checking if the pointer is in heap is trivial bounds check. This is not something we can fix easily.

**Comment by jokade** [comment]
@densh yes, when I hack immix/Heap.c to a reduced heap size (e.g. 64MB), immix heap allocation works fine for iOS/arm64 :) So -Xms/-Xmx should do the job

**Comment by densh** [comment]
Fixed in #1374.
