### ISSUE TITLE
Does it work on Windows?

### ISSUE THREAD

**Issue by darkoverlordofdata** [scala-native/scala-native#1367]
Does it work on Windows?

I'm trying to install on Windows with MSys2:

Windows 10 build 17134
MINGW64_NT-10.0
javac 1.8.0_161
sbt.version = 0.13.17
clang version 6.0.1
mingw64/mingw-w64-x86_64-libunwind 5.0.1-3 [installed]
msys/libgc-devel 7.6.0-1 (development)
msys/re2c 0.16-1
msys/zlib-devel 1.2.11-1 (development)

I'm not sure if I get an error from sbt or scala-native, I'm not very experienced with scala or jvm, I'm a c/c++ person. I'm running into a problem that sbt has problems locating java, it says it can't find it but runs anyway, then says it can't find clang and dies.

So I tested my sbt install using:
https://docs.scala-lang.org/getting-started-sbt-track/testing-scala-with-sbt-on-the-command-line.html

And I get mixed results:

	The Java Development Kit (JDK) installation you have is not up to date.
	sbt requires at least version 6+, you have
	version 0

	Please go to http://www.oracle.com/technetwork/java/javase/downloads/ and download
	a valid JDK and install before running sbt.

	Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
	[info] Loading project definition from C:\Users\darko\source\scalatesttutorial\project
	[info] Set current project to scalatest-example (in build file:/C:/Users/darko/source/scalatesttutorial/)
	[info] Running CubeCalculator
	[success] Total time: 1 s, completed Oct 16, 2018 12:10:45 AM 

then I try it with sbt new scala-native/scala-native.g8.
When I try sbt run, I get errors that it can't find clang:

	[error] No recent installation of clang found at /mingw64/bin/clang++

So I tried a version that is not at a posix mapped location, but I still get an error:

	[error] No recent installation of clang found at C:\Users\darko\Documents\GitHub\emsdk\clang\fastcomp\build_incoming_vs2015_64\Release\bin

**Comment by densh** [comment]
Hi @darkoverlordofdata, we don't currently support windows officially out of the box. Some people reported that it works out of the box if you use using WSL (Windows Subsystem for Linux) on Windows 10. Otherwise, please track issue #113.

**Comment by densh** [comment]
@darkoverlordofdata We'd like to eventually support Windows natively, but there is no exact timeline in terms of when it's going to happen. Please track #113 to get notified about the progress on that front.

**Comment by deabreu** [comment]
Hi @darkoverlordofdata, I have successfully compiled a Scala Native Project on WSL using nativeLink call on sbt. So I can state this works allright. But it is a Linux executable.

Then I tryed the same on WIndows PowerShell but I got the following backtracing:
_Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading settings for project global-plugins from idea.sbt ...
[info] Loading global plugins from C:\Users\ronal\.sbt\1.0\plugins
[info] Updating ProjectRef(uri("file:/C:/Users/ronal/.sbt/1.0/plugins/"), "global-plugins")...
[info] Done updating.
[info] Loading settings for project first-build from plugins.sbt ...
[info] Loading project definition from D:\Workspace\Scala-Native\proj-1\first\project
[info] Updating ProjectRef(uri("file:/D:/Workspace/Scala-Native/proj-1/first/project/"), "first-build")...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/tools_2.12/0.3.9/tools_2.12-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/util_2.12/0.3.9/util_2.12-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/nir_2.12/0.3.9/nir_2.12-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/test-runner_2.12/0.3.9/test-runner_2.12-0.3.9.jar ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-native/sbt-scala-native/scala_2.12/sbt_1.0/0.3.9/jars/sbt-scala-native.jar ...
[info]  [SUCCESSFUL ] org.scala-native#util_2.12;0.3.9!util_2.12.jar (2210ms)
[info]  [SUCCESSFUL ] org.scala-native#test-runner_2.12;0.3.9!test-runner_2.12.jar (2648ms)
[info]  [SUCCESSFUL ] org.scala-native#tools_2.12;0.3.9!tools_2.12.jar (3043ms)
[info]  [SUCCESSFUL ] org.scala-native#nir_2.12;0.3.9!nir_2.12.jar (4800ms)
[info]  [SUCCESSFUL ] org.scala-native#sbt-scala-native;0.3.9!sbt-scala-native.jar (7446ms)
[info] Done updating.
[info] Loading settings for project first from build.sbt ...
[info] Set current project to first (in build file:/D:/Workspace/Scala-Native/proj-1/first/)
[info] Updating ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/nativelib_native0.3_2.11/0.3.9/nativelib_native0.3_2.11-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/javalib_native0.3_2.11/0.3.9/javalib_native0.3_2.11-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/scalalib_native0.3_2.11/0.3.9/scalalib_native0.3_2.11-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/auxlib_native0.3_2.11/0.3.9/auxlib_native0.3_2.11-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/test-interface_native0.3_2.11/0.3.9/test-interface_native0.3_2.11-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/test-interface-serialization_native0.3_2.11/0.3.9/test-interface-serialization_native0.3_2.11-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/nscplugin_2.11.12/0.3.9/nscplugin_2.11.12-0.3.9.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-native/test-interface-sbt-defs_native0.3_2.11/0.3.9/test-interface-sbt-defs_native0.3_2.11-0.3.9.jar ...
[info]  [SUCCESSFUL ] org.scala-native#test-interface_native0.3_2.11;0.3.9!test-interface_native0.3_2.11.jar (1025ms)
[info]  [SUCCESSFUL ] org.scala-native#auxlib_native0.3_2.11;0.3.9!auxlib_native0.3_2.11.jar (1710ms)
[info]  [SUCCESSFUL ] org.scala-native#test-interface-serialization_native0.3_2.11;0.3.9!test-interface-serialization_native0.3_2.11.jar (2859ms)
[info]  [SUCCESSFUL ] org.scala-native#test-interface-sbt-defs_native0.3_2.11;0.3.9!test-interface-sbt-defs_native0.3_2.11.jar (3802ms)
[info]  [SUCCESSFUL ] org.scala-native#nscplugin_2.11.12;0.3.9!nscplugin_2.11.12.jar (4443ms)
[info]  [SUCCESSFUL ] org.scala-native#nativelib_native0.3_2.11;0.3.9!nativelib_native0.3_2.11.jar (9032ms)
[info]  [SUCCESSFUL ] org.scala-native#javalib_native0.3_2.11;0.3.9!javalib_native0.3_2.11.jar (22720ms)
[info]  [SUCCESSFUL ] org.scala-native#scalalib_native0.3_2.11;0.3.9!scalalib_native0.3_2.11.jar (36131ms)
[info] Done updating.
[info] Compiling 1 Scala source to D:\Workspace\Scala-Native\proj-1\first\target\scala-2.11\classes ...
[info] Non-compiled module 'compiler-bridge_2.11' for Scala 2.11.12. Compiling...
[info]   Compilation completed in 11.494s.
[info] Done compiling.
[error] java.io.IOException: Cannot run program "which": CreateProcess error=2, O sistema nÒo pode encontrar o arquivo especificado
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:112)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error]         at scala.scalanative.build.Discover$.discover(Discover.scala:156)
[error]         at scala.scalanative.build.Discover$.clang(Discover.scala:24)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$4(ScalaNativePluginInternal.scala:55)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:210)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$3(ScalaNativePluginInternal.scala:55)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.IOException: CreateProcess error=2, O sistema nÒo pode encontrar o arquivo especificado
[error]         at java.lang.ProcessImpl.create(Native Method)
[error]         at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[error]         at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:112)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error]         at scala.scalanative.build.Discover$.discover(Discover.scala:156)
[error]         at scala.scalanative.build.Discover$.clang(Discover.scala:24)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$4(ScalaNativePluginInternal.scala:55)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:210)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$3(ScalaNativePluginInternal.scala:55)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.io.IOException: Cannot run program "which": CreateProcess error=2, O sistema nÒo pode encontrar o arquivo especificado
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:112)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error]         at scala.scalanative.build.Discover$.discover(Discover.scala:156)
[error]         at scala.scalanative.build.Discover$.clangpp(Discover.scala:31)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$7(ScalaNativePluginInternal.scala:57)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:210)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$6(ScalaNativePluginInternal.scala:57)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.IOException: CreateProcess error=2, O sistema nÒo pode encontrar o arquivo especificado
[error]         at java.lang.ProcessImpl.create(Native Method)
[error]         at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
[error]         at java.lang.ProcessImpl.start(ProcessImpl.java:137)
[error]         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
[error]         at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:71)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream(ProcessBuilderImpl.scala:143)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lineStream_$bang(ProcessBuilderImpl.scala:112)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilder.lines_$bang$(ProcessBuilder.scala:214)
[error]         at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.lines_$bang(ProcessBuilderImpl.scala:87)
[error]         at scala.scalanative.build.Discover$.discover(Discover.scala:156)
[error]         at scala.scalanative.build.Discover$.clangpp(Discover.scala:31)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$7(ScalaNativePluginInternal.scala:57)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:210)
[error]         at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeBaseSettings$6(ScalaNativePluginInternal.scala:57)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (nativeClang) java.io.IOException: Cannot run program "which": CreateProcess error=2, O sistema nÒo pode encontrar o arquivo especificado
[error] (nativeClangPP) java.io.IOException: Cannot run program "which": CreateProcess error=2, O sistema nÒo pode encontrar o arquivo especificado
[error] Total time: 63 s, completed 30/08/2019 11:58:53_

This project was a simple helloworld project. So I believe that for more complex projects maybe it would be much harder to port.

I didn't tryed to use the intermediary representation and cross-compile the IR for Windows Native binary.

**Comment by cup** [comment]
https://github.com/scala-native/scala-native/issues/113

https://github.com/scala-native/scala-native/issues/1367
https://github.com/scala-native/scala-native/pull/691
