### ISSUE TITLE
Setting socket timeout on i386 throws an exception

### ISSUE THREAD

**Issue by shadaj** [scala-native/scala-native#1369]
Calling `socket.setsockopt` returns `-1` for some reason, needs more investigation.

**Comment by LeeTibbert** [comment]
Shadaj,

Sorry you are experiencing this.   I thought that this looked familiar
and finally got some time to check it out.

I believe that I have one or more PRs in the queue to address this.
I also believe that the underlying problem occurs on both 64 & 32 bit
platforms.

If I remember correctly, the socket fix was a breaking fix, so that it needed/needs
to wait for a release, S-N 4.0 or such, which allows breaking changes.

In the mean while there might be some alternatives.  If you are writing 
new code, there is a PR in the queue which implements poll(), which allows
timeouts (and works).  I can track down the PR if you like.

Or you could copy over the socket PRs.  I could create a list for you.

If you are modifying existing code, switching to poll() should be relatively
easy (says he, knowing that _nothing_ is _ever_easy_). Certainly easier
than implementing custom timeout & cancellation code.

If you are using only a few sockets, poll() should have faster execution speed
and use less memory..

Let me know how I can help out.

Lee

**Comment by densh** [comment]
@LeeTibbert Next release is going to be 0.4.0 so we are accepting breaking changes now.

**Comment by LeeTibbert** [comment]
@shadaj    @densh  merged PR #1454 just today.  When/if you get a chance, you may want to
try again with current mainline.  I would be surprised if the bug you experienced still exists.
If it does, I'll have to study your environment.  Setting a timeout in either connect() or accept()
provoked the bug in my environment.

Hopefully this is one stone out of your path...

**Comment by WojciechMazur** [comment]
As there were no reports since merging 1454 I think we can close this issue.

**Comment by LeeTibbert** [comment]
@WojciechMazur  I concur. 

Indeed I have thought so since Mar 18, 2019 but have
never had privileges to close someone else's Issue.

If you do, closing this would be one off the backlog.

At one point, there were several other aged Issues which,
I think, can be closed.  If it would be helpful, I can go
through the list and see if any of these remain.

**Comment by WojciechMazur** [comment]
Sure, we can close few others, especially if they're marked as bugs.
