### ISSUE TITLE
Proposal: plugin task to output NIR show of class/object

### ISSUE THREAD

**Issue by coreyoconnor** [scala-native/scala-native#1414]
Request is for some mechanism to view a pretty printed IR of a object/class. For instance: A task of the plugin to output `scala.scalanative.nir.Show.apply` of a class/object. 

A tool with similar functionality to what I'm looking for is `ghc-core`:

* https://hackage.haskell.org/package/ghc-core

Which, previously, I've found to be useful when implementing low-level optimizations versus using llvm IR. I suspect easily viewing the NIR would be similarly useful.

Did not see anything obvious for this. Not a priority IMO.

**Comment by densh** [comment]
@coreyoconnor We used to have a semi-private `nativeOptimizerReporter` sbt setting in SN <= 0.3.6. It was removed in 0.3.7 because of the build tool api refactoring (we were not ready to commit to the previous reporter design long-term). We should probably reconsider adding some form of NIR printout for introspection/debugging purposes.

**Comment by densh** [comment]
@coreyoconnor #1596 adds a setting to dump NIR for the entire application after linking and after optimization in the same folder as LLVM IR files. You can then find any linked method in there by grepping through those files. Would that work for your use case?

**Comment by densh** [comment]
Fixed in #1596.

**Comment by coreyoconnor** [comment]
Yes. That looks like it would work fine for my use case. Thanks!
