### ISSUE TITLE
Add support for class pinning

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#156]
Currently we dead-code eliminate all unreachable classes and modules. For some use-cases like reflection it might be beneficial to whitelist some classes to be always included. This is going to be implemented as an sbt key `nativePinnedClasses` that will let one enumerate all the classes that should stay in compiled code.

**Comment by vossad01** [comment]
Is there an expectation that different builds will need to pin different classes?

If I am understanding correctly, I am surprised to see this in being configured in sbt rather than in code.  For example with something along the lines of the `@JSExport` that Scala.js uses to denote availability to external JavaScript callers.

**Comment by densh** [comment]
There are two major use cases for this:

1. Reflection #159 
2. Linking Scala code as dynamic library #155

I'm not completely sure if solution for both is going to look the same, so I'm delegating this issue to be addressed in one of the tickets above.
