### ISSUE TITLE
Missing a few useful ANSI/POSIX C functions

### ISSUE THREAD

**Issue by rwhaling** [scala-native/scala-native#1642]
I've been using my own bindings for a handful of c functions:

wait()
waitpid()
fdopen()
execvp()
gai_strerror()

It would be great to get these merged in for 0.4

**Comment by LeeTibbert** [comment]
@rwhaling    

It took a while, like 3.5+ years.  Through the efforts of many people, I think all of your list is completed.
Your use case is probably long gone, but other people may find benefit.  
It is nice to see some good come from a line of work: many individual contributions towards the
same end.


PR #3160 should provide `fdopen()`, the last of the missing items on your list.  It, along with prior work
by @ekrich  also makes POSIX `stdio` complete. When that PR merges, this issue will get closed as
part of the merge process.  Please do let me know if you have additional concerns on this Issue
or in a new Issue.

This PR is scheduled for 0.5.0, due to the use of `@blocking`, so it will be awhile until it is generally 
released.

Most importantly, thank you for your support of Scala, and of Scala Native over the years.
