### ISSUE TITLE
Plan for SN TestFramework using portable-scala-reflect?

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1763]
I took a run at implementing SN support in portable-scala-reflect and then using that
in the Zio TestFramework.  From past work, I am pretty familiar with the baseline SN 
TestFramework.   From both of these, it looks to me like the SN Framework could be
simplified by changing it to use portable-scala-reflect.  

The current code is pretty clever and, to its enduring credit, does its job well. It is, however,
somewhat challenging to follow or trace, let alone modify.

I believe the long term plan would be to make the SN & Scala.js frameworks more similar.
Starting with portable-scala-reflect might be a good step.

I do not want to start an engineering design study if someone else is already intending to make this change or if it conflicts with medium or long-range plans for SN evolution.

**Comment by sjrd** [comment]
Since the API of `Reflect` in Scala Native is copied verbatim from Scala.js, the work in portable-scala-reflect is just to copy the implementation from `js/` and paste it in `native/` (and change a few imports). There isn't much engineering left to do. ;-)

After that, the plan is of course for testing frameworks to all standardize on portable-scala-reflect for all platforms.

**Comment by ekrich** [comment]
The Scala.js world has used JUnit for some time but you suggested that was non-optimal due to annotations and the hassle (plugin) to support them. Is there a strategy for JS and Native going forward vs Native's home grown testing framework? MUnit pulled in via source?

**Comment by sjrd** [comment]
JUnit may not have been optimal, but it is definitely the best solution we have. It wasn't optimal for us because we had to rewrite it, but it was optimal for the ecosystem. And since for Scala Native we can copy paste instead of rewrite, well that's basically optimal.

**Comment by sjrd** [comment]
Oh and the annotation business means it does not give a perfect UX for users, but a less than optimal UX is still infinitely better than not supporting JUnit at all.

**Comment by ekrich** [comment]
The plan is to support JUnit then instead of the current test suite or some other option? 

I was porting `scala-js-java-time` to Scala Native and just changed it to use MUnit instead. That was a pretty simple change - basic search and replace. I have it working MUnit for JVM, JS and Native.

Does it make sense to consider MUnit as an option?

**Comment by sjrd** [comment]
No, MUnit doesn't make any more sense than all the other Scala-based frameworks. Perhaps even less so:

* MUnit builds on top of JUnit; in JS and JVM they actually do that, but on Native I don't know what they do, although I guess they would welcome better support of JUnit for Native
* MUnit is still very new, and their Getting Started page say they have *no* compatibility guarantee at the moment

More generally, it doesn't make sense to reuse any Scala-based testing framework:

* They have to depend on JS/Native. You can't have JS/Native depend on them.
* Yes, sourcing in the code is possible, but that means you have to replicate their build config, that you are always behind, and that is still introducing a circular dependency.
* Inevitably, the testing framework will drop earlier versions of Scala. But JS/Native need to be the last ones to drop an old version of Scala, since everything else needs them. That means at some point you're stuck with a non-upgradable version of the testing framework; what if support for a *new* Scala version is only added in a version that does not support the *old* one? Then you're in a very bad situation.

All these concerns were very carefully weighed 6 years ago when we decided to reimplement JUnit for Scala.js. We did not *once* regret that decision. It is *very* unlikely that you'll be able to change my mind on this topic. So when you say "have you considered X?", well *yes*, we've considered all the options. JUnit is the best one.

**Comment by ekrich** [comment]
I am certainly not opposed but when I asked about porting JUnit quite some time ago to Scala Native you didn't encourage it. Maybe that was for other reasons but you didn't explain.

Plus, at one time there was some initiative to port a `minitest` type test framework to the Scala platform. See https://github.com/scala/scala-dev/issues/641 I don't know if this will ever get to production but it is a thing at some level - https://github.com/scala/nanotest-strawman

Yes, I understand the circular dependency but the library could be designed to be pulled and if it was associated with Scala proper it might be workable. To even consider the approach it would have to designed and vetted so that clearly is not in the cards.

**Comment by sjrd** [comment]
> I am certainly not opposed but when I asked about porting JUnit quite some time ago to Scala Native you didn't encourage it. Maybe that was for other reasons but you didn't explain.

Oh, did I? Wow, I must apologize for what I said at that time, and my therefore-too-harsh reply hereabove.

I don't know why I would have discouraged from porting JUnit for Scala Native. Perhaps if you have the link handy to the context where I said, I might recover from the context what prompted whatever I said at the time. Otherwise, let's just assume I was plain wrong.

**Comment by ekrich** [comment]
My probing is really just to have a better picture of the thought processes and back story. I was a bit taken aback but you have really been involved in this for awhile so things that may seem obvious to you may not be super obvious to others. These communications are just in snippets so certainly more context and explanation is better to some extent but it is difficult to get them just right for anyone. I do appreciate the apology. Any strategies from your perspective for Scala Native are certainly welcome and they can help contributors decide what makes sense to work on next.

**Comment by LeeTibbert** [comment]
I believe this issue is addressed & made obsolete by PR #1802. Thank you @errikos
