### ISSUE TITLE
IO.scala:100:29: ambiguous reference to overloaded definition,

### ISSUE THREAD

**Issue by hepin1989** [scala-native/scala-native#1780]
JDK: java 11,with jabba
```sbt publishLocal```
MacOs with the `Environment setup` done
gives:
```scala
[error] /Users/kerr/IdeaProjects/scala-native/tools/src/main/scala/scala/scalanative/build/IO.scala:100:29: ambiguous reference to overloaded definition,
[error] both method newFileSystem in class FileSystems of type (x$1: java.nio.file.Path, x$2: java.util.Map[String, _])java.nio.file.FileSystem
[error] and  method newFileSystem in class FileSystems of type (x$1: java.nio.file.Path, x$2: ClassLoader)java.nio.file.FileSystem
[error] match argument types (java.nio.file.Path,Null)
[error]     val zipFS = FileSystems.newFileSystem(archive, null)
```

**Comment by LeeTibbert** [comment]
@hepin1989 Kerr, thank you for the report.  I myself have run into a number of issues with building
SN on Java 11. I then have to jerk myself awake and realize that SN currently only supports Java 8, 
I believe. I think Java  9 & 10 work.  This may all change when SN supports a Scala which supports 
Java 11 (I think there were some problems with corner cases in some relatively recent Scala versions, fixed in 2.1?.)

**Comment by WojciechMazur** [comment]
Hey @hepin1989, can you tell me which JDK distribution were you using? I've not used Jabba before, but I can see it allows numerous different Java distributions. None of JDKs I've checked (GraalVM, OracleJDK, OpenJDK)  contains signature for `newFileSystem(Path, Map[String,String])`. I guess this bug may be distribution specific.

**Comment by ekrich** [comment]
I don't see it in JDK 11. https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/FileSystems.html
