### ISSUE TITLE
fromCString(null) returns java.lang.RuntimeException not NullPointerException

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1796]
@david-bouyssie reported a real life problem he has been encountering.  We have been discussing 
it offline and refining possible solutions.  Time has come, I think, to open up the discussion.

I barfed as I was writing the `fromCString(null)` as I was writing the title and any people
probably averted their eyes and refused to read it.  The classical, and my usual answer,
is "Don't do that, If nulls are a possibility, say from a getenv() call, check your results and/or
errno".  Still a good, albeit unfriendly, response. The classical reply is"Nulls exist in the real world,
get over it. Library code should not be actively hostile in handling them."

To the current problem.  My recent understanding is that Scala practice is to not do explicit
checks for null and rely upon Scala throwing a NullPointerException, which can be caught,
Fine so far.  

Now scalanative.unsafe.fromCString is, well, unsafe. It is on the edge of Scala and OS code.
David reported that fromCString(null) returns java.lang.RuntimeException.  He is innocent
of bad coding; he is working with an API which deals with nulls as default values.
Investigation shows that the generated binary for null.getBytes(mumble) throws the
Unix signal 11 Segmentation fault. Scala adds 128 and reports it as java.lang.RuntimeException 139,
which can not be caught.  Not friendly for a recoverable error (yes, people should check rather
than relying upon try/catch).  The expected/desired behavior would be to get a NullPointerException.

There are a couple of possible solutions.

1) Do nothing, we have other things to do. 

2) Document as a "Do not do that", probably in the clib(?) documentation, where fromCString()
    is described.  Suggest using a wrapper around the fromCString() call and possibly
    provide an example.

3) add the lines of code roughly so that the usual, expected, & NullPointerException, which can be
    caught.
```
if (cstr == null) {
    throw new NullPointerException
}
```
   This adds a test and branch across a small code block for each and every call to the
    method, but is friendlier and more inline with norms & practice.

4) Implement a fromCStringOrElse(str, default = TBS) method. This would be the example
    suggested above, but better.  Similar to Option.getOrElse, it would return the default
    in case of null arg or other.  This is adds an extra entrypoint to the SN unsafe API
    doing work which developers should be doing themselves but it avoids the support
    cost of a number of devos writing their own, possibly wrong, code.  That is, it is
    friendlier, but not without cost.

    The default for the default is open to discussion, if the discussion gets that far. A possibility
     would be the empty string.  Another possibility is null in, null out.  

Thoughts? Beyond the very appropriate yeech!

**Comment by sjrd** [comment]
> To the current problem. My recent understanding is that Scala practice is to not do explicit
> checks for null and rely upon Scala throwing a NullPointerException, which can be caught,
> Fine so far.

No, `NullPointerException`s should definitely not be caught, like, ever. In Scala.js that's not even possible (it's undefined behavior). That said, it is common practice not to do explicit checks for `null`s, and instead assume that passing `null` to an API violate its precondition, unless otherwise documented (or unless the parameter is of an unbounded type parameter, which means it should be type parametric, in which case it should cope with `null` just fine).

With that perspective, I believe the current implementation of `fromCString` and `toCString`, which is to do "whatever" if you give them `null`, is idiomatic Scala. The parameter is not type parametric (it is of fixed type `CString`) and the Scaladoc does not say anything about `null`. It is therefore assumed that passing `null` to it is invalid, a programming error.

---

Now, we can debate on whether the particular conversion methods `fromCString` and `toCString` should specifically define the behavior if they receive `null`. In other words, should we turn the existing undefined behavior into a specified behavior?

If yes, then to me the only reasonable option is to convert `null: CString` into `null: String` in `fromCString`, and conversely in `toCString`.

**Comment by david-bouyssie** [comment]
I would vote for the last @sjrd's suggested option for a pragmatic reason. Those methods (as some others in the SN API) are used as a glue between the Scala and C worlds. Many C libraries accept/return null values for various pointers. These "C" null values need to translate into "Scala" null values and vice versa.
I'm now used to do systematically ```if (cstr == null) null else fromCString(cstr)```, and I have the feeling that it would  be more pleasant for SN users to avoid this (since calling toCString/fromCString is a very common thing).

I can't anticipate how much impact this change could have on the SN unit tests and SN libraries, but I "optimistically" guess it should not introduce any bug.

**Comment by LeeTibbert** [comment]
Because I had only a small chunk of time and my brain was fried with equality issues, I took a 
run at implementing sjrd's suggestion:
```
```
Just to see what, if anything smoked.

As is my want, I first implemented unit tests for each of fromCString(null) and toCString(null).
The know RuntimeException understandably slew the SN binary porting of the testinterface,
triggering the known and dreaded local (SBT JVM side) "java.net.SocketException: Socket closed".
That problem had been reported a year ago in an Issue #1585 and I have been pecking away at it.

So, I need to create a new issue (binary run ends early) and then take a recursive edit to fix
some of the items described in #1583 

The before case of toCString() seems to throw the expected NullPointerException. So the anomaly seems to be that fromCString() returns the RuntimeException. From looking at the implementation,
is is obvious why libc.strlen(null) is unhappy.

I am somewhat uncomfortable having fromCString(null) pass back a null and the increasing
the code path length of a very commonly used method.  I keep returning to the fromCStringOrElse()
concept, perhaps implemented as a suggestion to users?  Right now I have bigger issues to 
address than my discomfort and would like to make this usable. 

More when I finish addressing the review comments for two particularly tricky PRs, and have
been able to make progress on Issue #1585.

**Comment by jokade** [comment]
> If yes, then to me the only reasonable option is to convert `null: CString` into `null: String` in `fromCString`, and conversely in `toCString`.

Just seen this issue. I'm working mostly on SN interop and I must agree with @david-bouyssie: I would definitely prefer to go with the proposal that `fromCString(null)` should simply return `null`, so we can get rid of the guards in glue code.

I don't think throwing an exception in this case is the right way to go since returning `null` is often just the normal behavior of C libs.

Furthermore, the inverse operation `toCString(null)` should also yield `null`. If a C library returns a null from a function, chances are that it will also accept this `null` as argument to other operations, for example `getXXX` / `setXXX`. I think this should be reflected in SN, i.e.
```scala
val foo = fromCString( getFoo(instancePtr) )  // call to getFoo returns null
// ...
setFoo( instancePtr, toCString(foo) )
```
should work the same way it would if I'd written it in C. 

But if you do decide on throwing exceptions, it would be useful if the `unsafe` package also provided helper functions like `fromCStringOption: CString => Option[String]` and `toCString: Option[String] => CString`.

**Comment by LeeTibbert** [comment]
jakade, Thank you for your real world experience.

Much as I hate proliferating entry points, perhaps the adding the Option based helper functions described
in your comment deserves consideration. Something similar may have been proposed earlier in this
Issue.

This code is operating at the interface between Scala & C, with Java as the ever present background
ghost. I think there will always be at least two camps (of a common culture, important to remember that
these days): "This ought to work like Scala, where Option is preferred over nulls scattering all over the place"
and "This ought to be like C (with Java hovering at the edge of the discussion) where nulls are first class citizens,
live with it!"   As much as my professional background and life outside of Scala is in C, I am obviously in
the first camp when writing in Scala.

I can not name them off the top of my head, but I think there are other methods in Scala which have
two variants, Throw and Option.  I seem to remember that the get handling of Option itself is one such
place.

If there is some consensus, I can modify my PR.  If not, it is a least-change solution which will not
preclude more elegant solutions.  I am part of the posse chasing the Perfect, but I also realize that
the problem reported in the base note is being experienced by people in the wild and needs a timely
solution, albeit imperfect.

**Comment by LeeTibbert** [comment]
In refreshing my memory of Option get* methods, I had the feeling that I had see a "toCStringOrElse" proposal before,
from @david-bouyssie, from me???

**Comment by sjrd** [comment]
I don't think we should play with Options here. Either we should throw on `null`, or return `null`, but having alternatives with `Option`s falls outside of the scope of those low-level primitives that are meant to talk to C.

**Comment by ekrich** [comment]
> If yes, then to me the only reasonable option is to convert `null: CString` into `null: String` in `fromCString`, and conversely in `toCString`.

I totally agree with this too. One null String is converted to the other.

**Comment by david-bouyssie** [comment]
I'm also in favor of sticking with null values for these conversion helpers.
Scala would then allows to do idiomatically ```Option(fromCString(cstr)).map(str => ...)```, so to me it is good enough.

**Comment by ritschwumm** [comment]
how is ```Option(fromCString(cstr)).map(str => ...)``` better than ```Option(cstr).map(fromCString)```?
i don't see how it's a good idea to hide a possible bug by passing on a null value instead of dealing with null values as early as possible.

**Comment by david-bouyssie** [comment]
@ritschwumm ```Option(cstr).map(fromCString)``` is for sure not a bad practice, but I think the other way ```Option(fromCString(cstr))```should not crash the program and I would expect it to provide similar results.

The Option/map combination is a possible use case, but another scenario is a C function wrapper returning a java.lang.String:

```scala
def cFuncWrapper(): String = {
  // Some C level calls
  ...
  val finalResultAsCStr = cfunc()
  fromCString(finalResultAsCStr) // may fail with the current implementation
}

def cFuncWrapperWithNullCheck(): String = {
  // Some C level calls
  ...
  val finalResultAsCStr = cfunc()
  if (cstr == finalResultAsCStr ) null else fromCString(finalResultAsCStr ) // ok with the current implementation
}
```

Since writing C function wrappers can be a cumbersome task for large C libraries, I would prefer to avoid null checking string conversions systematically and let the ``cFuncWrapper()``` caller do the null check (or wrap the String into an Option[String]).

**Comment by jokade** [comment]
Is there a decision on this (and the behavior of `toCString()`?

From the point of writing bindings for C libs I *really* would prefer if both would just map `null` to `null`. For example, a common pattern (for me at least) is to provide a simple wrapper that takes a `String` where the external function takes a `CString`:
```scala
def foo(arg1: CString, arg2: CString): Unit = extern

def foo(arg1: String, arg2: String): Unit = Zone{ implicit z =>
  foo( if(arg1==null) null else toCString(arg1),
       if(arg2==null) null else toCString(arg2) )
}
```
Gtk+ for example takes `null` as a valid argument for a `CString` in a lot of cases. It's really annoying having to check for `null` every time...

Yes, I know, in *idiomatic Scala* the signature of the helper should be:
```scala
def foo(arg1: Option[String], arg2: Option[String]): Unit = // ...
```

but it's not convenient, since in a lot of cases we only use the `null` value at compile time (i.e. if the `CString` is optional in the external function call):
```scala
def setLabel(label) = foo(label,null)
```
IMHO it's *idiomatic w.r.t to the external library* to use `String`s + `null` instead of `Option[String]`.

**Comment by LeeTibbert** [comment]
I seem to be in the minority. I can close this PR in favor of someone else writing a PR which implements the
null-to-null. While technical fit-to-use is a concern for me, community harmony and progress is a greater
goal.

I still believe that letting nulls cross the Scala/C boundary is a mistake.  
That belief is that the code handling the transition should do the simplest thing and expected 
thing __in_the_Scala_ecosystem.   I think that translating the (un-intended!) C signal to an
Exception that is identical to the way nulls are handled in almost all other Scala library code
is that simplicity.   Obviously, at least two experienced people where the rubber hits the road have
evidence-based opinions which differ.

Let the naked nulls stay in C.  Yes, I have written __lots__ of C code, most of which was
OS kernel code, where a C signal would crash the entire OS.

I think that this PR should be the basic layer.  It does a tiny defensive change and does not force existing code to change.

I also think it would be a kindness to developers if one or more small helper functions, such as the ones @david-bouyssie and I discussed at the beginning of this comment train, were created in a separate PR.

My primary concern is that I do not have to go chasing C signals resulting from a null getting to the libc 
call. If this superseding PR, could ensure that, I would be grateful.

Yes, the base code which executes when a Scala Native binary begins to execute should (optinally?)  establish some C
signal handlers, so that a C signal does not cause it to die silently in the night, with an obscure excess-128 error code.
That however, is an entirely different discussion, design, & PR.

**Comment by david-bouyssie** [comment]
Having additional helpers is not incompatible with the previously discussed behavior of fromCString/toCString and might be indeed useful for developers, at the cost of increasing a bit the number of available functions in the API.
I guess this could be implemented like this (either in end-user utilities or directly in the SN code base):

```scala
def fromCStringOrElse(cstr: CString, default: String): String = {
  require(default != null, "the default value can't be null")
  if (cstr == null) default else fromCString(cstr)
}
def toCStringOrElse(str: String, default: CString): CString = {
  require(default != null, "the default value can't be null")
  if (str == null) default else toCString(str)
}
```

We avoid the use of Option types here which was a concern from @sjrd.
This being said, I can't tell if it is wise or not to include these functions in the SN API.

**Comment by sjrd** [comment]
I suggest we go forward with `fromCString` and `toCString` preserving `null`s, so `fromCString(null)` and `toCString(null)` both return `null`.

**Comment by LeeTibbert** [comment]
OK, I will submit a new PR, null begets null.

**Comment by LeeTibbert** [comment]
OK, I will submit a new PR, null begets null.  Thank you for the clear direction.

**Comment by LeeTibbert** [comment]
@david-bouyssie,  @jokade, @ekrich   Did PR #1945 implement the sense of the meeting here and the final direction?
I hope so and I hope it eases your work.  Please advise.  

For some reason, I could not mark @david-bouyssie and @jokade  as reviewers, sorry.  I appreciate your review time and the time you gave this discussion.

**Comment by david-bouyssie** [comment]
Thank you @LeeTibbert for the new PR. It also looks good to me and I think it should not change the behavior of existing user code, so I assume there will be no unexpected surprise when the next release comes out.

Thank you also for updating ```docs/user/interop.rst```.
