### ISSUE TITLE
Test runner should timeout tests which take unexpected & excessive time

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#1816]
I am trying to help improve the experience of new & experienced developers using
the Scala Native test environment by writing down pain points as I am able to
describe them. 

This provides a base for iterative & Pareto (70/30) improvement.

The current ScalaNativeRunner/ComRunner interface allows to specify a timeout
values that sbt will use when doing a recieve() from the SN binary.  From my tracing
it seems like almost all or all(?) of the time, this is specified as Infinity.  Useful
for bootstrapping, but not robust as more people join the project.

Imaging a test under development which created an "Infinite" loop. Currently this will,
I believe, _silently_ hang the test environment until either the user gets tired and interrupts or
Travis CI times out. 

Now the obvious, but less than helpful solutions are:
1) Buy a faster CPU, so the infinite loop completes faster.
2) Do not write buggy tests.

The cheap, short term solution is to change the current default of Infinity to something fixed, arbitrary,
and probably long enough for any reasonable test to succeed. One nanosecond is probably too small
and one hour is probably too long.  My guess that 5 minutes is more than adequate for unit-tests.
Two minutes would probably be shorted & also successful. I have not traced if scripted-tests
uses this pathway. Those tests probably need the full 5,

mid-long to Long term:

Zio solves this problem by allowing tests to have an annotation which specifies the maximum
amount of time a test is expected to run.  

I do not know if JUnit has a similar concept.  By describing this Issue, it can be kept in mind
as tests are written/converted to use JUnit.

**Comment by sjrd** [comment]
JUnit has a similar concept, yes.

However, I don't think we should build timeouts in the system itself, other than those controlled by dedicated annotations from testing frameworks. We recently decided again against having any such timeout in Scala.js. Reading the rationale at https://github.com/scala-js/scala-js/issues/4059 can be useful.

So other than trying to implement the timeouts in the JUnit framework when we get there (which is not going to be ready or even possible, due to the single threaded nature), I don't think there is anything to do here.

**Comment by LeeTibbert** [comment]
Addressed by now merged PR #1813.
