### ISSUE TITLE
missing symbols on scala-2.12 build

### ISSUE THREAD

**Issue by catap** [scala-native/scala-native#1930]
I've tried to migrate https://github.com/catap/scala-blake3 on 8b4e40904697b66cd130fc375202a35680d7490a and got an error:
```
[info] Linking (2152 ms)
[error] missing symbols:
[error] * M89org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$RE
[error]   - from M29org.scalatest.tools.FrameworkIE
[error] * T89org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$
```

How to reproduce.
1. You need to publish locally SN that is overstep or fixed https://github.com/scala-native/scala-native/issues/1925 for example by branch that I've used: https://github.com/catap/scala-native/commits/increased-buffer
2. You need to publish locally scalatest. An easy way is using https://github.com/scalatest/scalatest/pull/1902 from branch https://github.com/catap/scalatest/tree/scala-native-2.12-local.sh that contains `local.sh`. Just run it and wait couple of hours. 
3. After that you need a master branch of https://github.com/catap/scala-blake3. As soon as you get it just run
```
env SCALANATIVE_VERSION=0.4.0-SNAPSHOT sbt ++2.12.12 test
```

**Comment by errikos** [comment]
I think that you need to annotate the `org.scalatest.tools.Framework` object or class with `scala.scalanative.reflect.annotation.EnableReflectiveInstantiation`.

**Comment by catap** [comment]
@errikos I've did it on the same way as it made for SJS: https://github.com/catap/scalatest/commit/c0510dbe75703fcd28cddfe044a0bf3167192069

It moves to the next issues:
```
[error] missing symbols:
[error] * M111org.scalatest.featurespec.AnyFeatureSpecL40org.scalatest.featurespec.AnyFeatureSpec$SN$ReflectivelyInstantiate$RE
[error]   - from M40org.scalatest.featurespec.AnyFeatureSpecIE
[error] * M89org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$RE
[error]   - from M29org.scalatest.tools.FrameworkIE
[error] * M94org.scalatest.SuitesL20org.scalatest.SuitesL20scala.collection.Seq$SN$ReflectivelyInstantiate$RE
[error]   - from M20org.scalatest.SuitesIE
[error] * M95org.scalatest.funspec.AnyFunSpecL32org.scalatest.funspec.AnyFunSpec$SN$ReflectivelyInstantiate$RE
[error]   - from M32org.scalatest.funspec.AnyFunSpecIE
[error] * M99org.scalatest.flatspec.AnyFlatSpecL34org.scalatest.flatspec.AnyFlatSpec$SN$ReflectivelyInstantiate$RE
[error]   - from M34org.scalatest.flatspec.AnyFlatSpecIE
[error] * M99org.scalatest.freespec.AnyFreeSpecL34org.scalatest.freespec.AnyFreeSpec$SN$ReflectivelyInstantiate$RE
[error]   - from M34org.scalatest.freespec.AnyFreeSpecIE
[error] * M99org.scalatest.funsuite.AnyFunSuiteL34org.scalatest.funsuite.AnyFunSuite$SN$ReflectivelyInstantiate$RE
[error]   - from M34org.scalatest.funsuite.AnyFunSuiteIE
[error] * M99org.scalatest.propspec.AnyPropSpecL34org.scalatest.propspec.AnyPropSpec$SN$ReflectivelyInstantiate$RE
[error]   - from M34org.scalatest.propspec.AnyPropSpecIE
[error] * M99org.scalatest.wordspec.AnyWordSpecL34org.scalatest.wordspec.AnyWordSpec$SN$ReflectivelyInstantiate$RE
[error]   - from M34org.scalatest.wordspec.AnyWordSpecIE
[error] * T111org.scalatest.featurespec.AnyFeatureSpecL40org.scalatest.featurespec.AnyFeatureSpec$SN$ReflectivelyInstantiate$
```

**Comment by catap** [comment]
@errikos and the things that scala-js passing this test :(

**Comment by catap** [comment]
To make things clear. https://github.com/catap/scalatest/commit/c0510dbe75703fcd28cddfe044a0bf3167192069 generate a code that is building by scala-native for `AnyFeatureSpec` like this
```
@Finders(Array("org.scalatest.finders.FunSuiteFinder"))
//SCALATESTJS-ONLY @scala.scalajs.reflect.annotation.EnableReflectiveInstantiation
@scala.scalanative.reflect.annotation.EnableReflectiveInstantiation
class AnyFunSuite extends AnyFunSuiteLike {

  override def toString: String = Suite.suiteToString(None, this)
}
```

You can check it by using this branch and run
```
env SCALANATIVE_VERSION=0.4.0-SNAPSHOT sbt ++2.12.12 "project scalatestNative" compile
```
and find this file at `native/funsuite/target/scala-2.12/src_managed/main/scala/org/scalatest/funsuite/AnyFunSuite.scala`

**Comment by catap** [comment]
Small update on this topic.

Right now master branch can't produce scalatest that can be used. For example SN-2.11 crashes on linking of application's tests with error:
```
[error] missing symbols:
[error] * M89org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$RE
[error]   - from M29org.scalatest.tools.FrameworkIE
[error] * T89org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$
[error] java.util.NoSuchElementException: key not found: Top(org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$)
[error] 	at scala.collection.MapLike.default(MapLike.scala:235)
[error] 	at scala.collection.MapLike.default$(MapLike.scala:234)
[error] 	at scala.collection.AbstractMap.default(Map.scala:65)
[error] 	at scala.collection.mutable.HashMap.apply(HashMap.scala:69)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$logLinked$2(ScalaNative.scala:45)
[error] 	at scala.scalanative.build.ScalaNative$.$anonfun$logLinked$2$adapted(ScalaNative.scala:42)
[error] 	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[error] 	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[error] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[error] 	at scala.scalanative.build.ScalaNative$.showLinkingErrors$1(ScalaNative.scala:42)
[error] 	at scala.scalanative.build.ScalaNative$.logLinked(ScalaNative.scala:65)
[error] 	at scala.scalanative.build.Build$.$anonfun$build$1(Build.scala:56)
[error] 	at scala.scalanative.build.Logger.time(Logger.scala:32)
[error] 	at scala.scalanative.build.Logger.time$(Logger.scala:29)
[error] 	at scala.scalanative.build.Logger$$anon$2.time(Logger.scala:66)
[error] 	at scala.scalanative.build.Build$.build(Build.scala:53)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$11(ScalaNativePluginInternal.scala:127)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.interceptBuildException(ScalaNativePluginInternal.scala:182)
[error] 	at scala.scalanative.sbtplugin.ScalaNativePluginInternal$.$anonfun$scalaNativeConfigSettings$10(ScalaNativePluginInternal.scala:127)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (blake3Native / Test / nativeLink) java.util.NoSuchElementException: key not found: Top(org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$)
```

I mad small investigation by using:
 - http://github.com/catap/scala-blake3
 - https://github.com/catap/scalatest/tree/scala-native-2.12
 - https://gist.github.com/catap/23f0ff49c4f624f3c499d412c64c5f66

And discovered that the issue started since https://github.com/scala-native/scala-native/commit/3077e74c363307963ce6dfbe7da1969bb76993b3.

**Comment by LeeTibbert** [comment]
Yes, This is the problem that I have mentioned.  I did some exploratory work getting ScalaTest on 0.4.0-August2020
because scala-java-time uses ScalaTest.    With proper futzing ScalaTest works just fine.  

The end-of-steel issue I encountered is that the ScalaTest build does not put the *Reflective* symbols into its
artifacts.  Framework is used by ST core, any of the FooSuite (FunSuite, etc). artifacts need a *Reflective*
symbol for their class-of-interest. 

 The ScalaTest build does some OSGi (sp?) packaging.  About a month or so ago I put a long description
into the ScalaTest gitter.  I have not heard back and have not had time to make it a formal issue for
ScalaTest.  With more than reasonable effort I could not figure out why the *Reflective* symbol was
not being picked up (the .nir & .class are generated).  I think the problem is that the SN plugin
generates the code, so that the OSGi code never sees it because some SBT mumble mumble
config parameter is never gets set up to include it.

For a scala-java-time and something else I do not remember, I hacked around it by supplying
the missing symbols (i.e, placing the source code into the project).  With that blatant hack,
ScalaTest worked just fine with 0.4.0-SNAPSHOT-Aug2020.

SN.next is approaching, but, due to the press of my current SN test infrastructure work,
I have not taken the next step with the ScalaTest devos.  I would like to have a 
production SN in hand before I ask for their help.

**Comment by catap** [comment]
@LeeTibbert just for records: I added `@scala.scalanative.reflect.annotation.EnableReflectiveInstantiation` for all same class that has it already for SJS.

See: https://github.com/catap/scalatest/commit/28efed0941c547a4088b3af092270f10e4c29eb0

**Comment by LeeTibbert** [comment]
Yes,  I suspect that code will be very useful.   I think it will not compile now if submitted to ScalaTest just now.

I had thought of using portable-scala.mumble but rejected it for two reasons:
1) There is a PR portable-scala.mumble to introduce SN EnableReflectiveInstantiation but that PR
     can not be acted upon until after SN 0.next is production.  (And it needs some point edits because
    it has not aged well over the past six months.)

2) Much as I hate almost-exact-but-not-quite-duplicate code paths, I did not want to disturb the 
   existing and working Scala.js path.

**Comment by catap** [comment]
@LeeTibbert I feel that it is a bug inside scala-native.

Why?

For example I have an error:
```
[error] * M89org.scalatest.tools.FrameworkL29org.scalatest.tools.Framework$SN$ReflectivelyInstantiate$RE
[error]   - from M29org.scalatest.tools.FrameworkIE
```

It was build from scala code:
```
import sbt.testing.{Framework => BaseFramework, Event => SbtEvent, Status => SbtStatus, _}
...
@scala.scalanative.reflect.annotation.EnableReflectiveInstantiation
class Framework extends BaseFramework {
...
}
```

As far as I understand how it works linker should find this annotation.

Have I miss something?

**Comment by LeeTibbert** [comment]
By my reading and in my simple debug environment, the SN plugin _is_ finding the annotation and is generating
the proper mumbleReflectiveInsmumble .class and .nir files.  The issue that has stopped me is that ScalaTest
does not find those file and place them in the artifact(s) it creates. 

Warning:  Sensitive souls, sound engineers, and people under the age of Majority, what ever that may be
                 where you live, should not proceed beyond this point.

                 All others, proceed only at risk of you sensibility.

As mentioned, when I take those exact ScalaTest files, put them into the right place in my local sandbox, and complie
my local project using a libraryDependency on ScalaTest artifact built for SN 0.4.0-SNAPSHOT,  those symbols are found.
This tells me, at least, that the issue is a ScalaTest issue. Having enough of an ecosystem that I can test scala-java-time and,
IIRC, utest with ScalaTest and SN Reflection, I simply have not had time to run the ScalaTest packaging issue to ground.
I do not want to interrupt ScalaTest developers directly until SN 0.Next is a done deed.  

Now, a clever person might say "Why not just take the .class and .nir files that ScalaTest is already building, put them in a jar,
and place them in the <project-root>/lib of my SN sandbox project.  I thought of that also but was not clever or persistent enought to pull it off.  SN seemed to be wanting to look for LmumbleReflectiveMumble symbols when the symbols generated by both 
ScalaTest and my private source clone provided MmumbleReflectiveMumble.   There is written documentation, recently updated in the SN repository about name mangling.  With sufficient effort, I could have figured out what the difference between L and M is.  I suspect that M means module meaning, for me, Object.   

If you want to take a day or night and to team or tag-team programming to try to figure out the ScalaTest
OSGi packaging, I am willing. I __think__ it has something to do with the way directories are set up in
Sbt.  The files sneakily generated by SN are probably not being put in a place that the OSGi packaging
would ever expect, or there is an exclusion filter.

The other possibility is that if this is a BIG DISSATISFIER for you I could switch efforts and, hopefully, run
it to ground.  I have about two days of work submitting 3 PRs before I could get to a good switching point.


Short term, ScalaTest can be made to work in a local project. I can send you the code for personal use as scaffolding until 
what I believe is a ScalaTest packaging issue can be resolved.

If this does not help directly, perhaps it gives you a place to look.  If you do a "jar tf" on your custom ScalaTest artifacts do you see the symbols the linker can not find. I suspect not, linker could not find them either.  Now if, from the project root directory,
if you do a "find . -type file -iname "*ReflectivelyInstantiate*" (did I get that name right from memory?  Linker will tell expected name) do you see the symbols?  I suspect yes.  

When I was debugging, I also created a simple project and used "sbt package" to create an artifact expected
to contain RI (mumbleReflectivelyInstantateMumble) symbols, they showed up in the artifact and were accessible
from an independent sandbox project which used that artifact as a libraryDependency.  This added weight to
my hypothesis that the issue I/we encountered has to do with ScalaTest packaging.

Those appropriate "*ReflectivelyInstantiate" symbols get packaged into

After my query in the ScalaTest gitter got no response, I took a run

**Comment by catap** [comment]
@LeeTibbert have you tried generated sources in your simple project?

I feel that it might be a cause of the issue.

**Comment by catap** [comment]
@LeeTibbert it is definitely OSGI but not plugin, it the OSGI repacking itself that loosing all files that hasn't got a file with the same name but that is ends as `.class`.

Anyway, I found a workaround and it isn't a SN bug => I close the issue.

**Comment by LeeTibbert** [comment]
@catap  Good to see that you were able to fix this (and that it was not, directly, a bug in Scala Native).
You obviously put a lot of thought & effort into coming up with a provisional solution for the ScalaTest devos.

I believe that a functioning ScalaTest on SN 0.next unlocks uTest , scala-java-time, scala-java-*, and probably
a bunch more. You cleared a log jam.
