### ISSUE TITLE
ZipException when packaging the scalalib for 2.13

### ISSUE THREAD

**Issue by sjrd** [scala-native/scala-native#2117]
The following task, which is called by `scalalib/publishSigned`, fails:
```
> ++2.13.4
> scalalib/compile:packageSrc
[error] java.util.zip.ZipException: duplicate entry: scala/Enumeration.scala
[error]         at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
[error]         at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
[error]         at sbt.io.IO$.addFileEntry$1(IO.scala:709)
[error]         at sbt.io.IO$.$anonfun$writeZip$6(IO.scala:718)
[error]         at sbt.io.IO$.$anonfun$writeZip$6$adapted(IO.scala:718)
...
```
Apparently the source files that `packageSrc` sees contains twice the file `scala/Enumeration.scala`, which prevents the jar from being built.

**Comment by WojciechMazur** [comment]
Indeed Enumeration is defined twice: it's in `scalalib/overrides` and `scalalib/overrides-2.13`. They're both listed in `packageSrc::mappings` which probably causes failure. 

Currentlly `scalalib/compile:packageSrc::mappings` contains only override files. Since we don't publish their `*.class` files we can filter them out. Am I correct @sjrd?  Otherwise we can include in mappings only those override that are contained in `Compile/sources`.

**Comment by sjrd** [comment]
Yes, I guess we can filter out everything in scalalib.
