### ISSUE TITLE
scalafmt & clang-formt should just go ahead and format not hard fail.

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2191]
What is the biblical saying about "When I was a child..."

Tools are supposed to ease development, not to be something
one needs to fight against.

Having scalafmt,  and later clang-format, served the childhood of the
SN project.  When those tools were younger, there were times when
they could mangle the code, rather than ensure consistency.
It made sense at the time to force manual review.

Time has passed, those tools have matured.  I submit that having
those tools hard fail now is just frustration.  They should just go
ahead and reformat, and perhaps give me a message/warning that
they proactively did so.   That way I can review at my leisure and
the rest of the PR can progress.

This wail of agony, and suggested improvement, came from
accepting a reasonably well formed edit suggested/provided_by
a PR reviewer and then having to utterly waste a half hour or more
because scalafmt failed hard (over a questionable reformat at that).

Comments? (besides, "Chill out, Dude! It happens to better people than you.")

If there is some agreement that this is a good way to go, I will throw
it at the back of my "Someday..." ~~compost-pile~~ Dream list.

**Comment by ekrich** [comment]
Honestly, I don't know what you are getting at. I think most people run `scalafmt` before they push a commit or better yet before they do the commit.

Hard failing I believe here means returning 1 instead of 0 from the script. This is needed so that the CI can flag the problem.

Or is the question or suggestion something different?

I submit that `scalafmt` has its warts but we typically do not have to spend multiple iterations on format issues or understanding a formatting guide making it easier for the contributor. 

Is there a specific problem you ran into?

Maybe this is a better topic for Gitter perhaps before creating an issue.

**Comment by LeeTibbert** [comment]
Closing, too many dragons (Issues).  I need to focus on the Big Dragons, and those closer
to my heart.

 The problem is not so much scalafmt itself, I agree that any
style guide's first pass must be executable. The problem I experienced is with our CI script which
uses scalafmt.  

The current script currently exits with failure after detecting a formatting error.  It would be
as easy as anything ever is to run the script again, only after failures, but this time do
the formatting.  

The hard part is getting the script to commit the resultant formatted code to the Repository.
I simply do not have time to track that down.  Maybe the next time, or the 20th time,
this will become my biggest problem and I will create the time.  Until then it is an
annoyance.
