### ISSUE TITLE
Fix Clang discovery on Windows

### ISSUE THREAD

**Issue by david-bouyssie** [scala-native/scala-native#2321]
On my Windows machine, the current implementation of ```private[scalanative] def discover(binaryName: String, envPath: String): Path``` in "\tools\src\main\scala\scala\scalanative\build\Discover.scala" fails to retrieve the proper location of clang.exe.

On my system this fix works (addition of ```if (binaryFile.isFile) return binaryFile.toPath```):
```
  /** Discover the binary path using environment
   *  variables or the command from the path.
   */
  private[scalanative] def discover(binaryName: String,
                                    envPath: String): Path = {
    val binaryNameOrPath = sys.env.getOrElse(envPath, binaryName)
    val binaryFile = new File(binaryNameOrPath)     // added by me
    if (binaryFile.isFile) return binaryFile.toPath // added by me
    
    val locateCmd        = if (Platform.isWindows) "where" else "which"
    val path = Process(Seq(locateCmd, binaryNameOrPath))
      .lineStream_!(silentLogger())
      .map { p => Paths.get(p) }
      .headOption
      .getOrElse {
        throw new BuildException(
          s"""No '$binaryNameOrPath' found in PATH or via '$envPath' environment variable.
             |Please refer to ($docSetup)""".stripMargin)
      }
    path
  }
```

Sorry but I'm too lazy/busy to make a PR for these two lines of code.
I hope this will still help.

**Comment by ekrich** [comment]
So right now it expects either the `CLANG_PATH` to be set to the directory of the `clang[.exe]` or the executable to be in the path. If `CLANG_PATH` is set to point at the full path to `clang[.exe]` then that should be changed locally. If `CLANG_PATH` is being set to the value you suggest then it would be really helpful to know what tool or process is setting that value.

FWIW, I would like to change the discovery somewhat anyway.

**Comment by david-bouyssie** [comment]
So you mean that instead of setting "CLANG_PATH=C:\Program Files\LLVM\bin\clang.exe" I should put "CLANG_PATH=C:\Program Files\LLVM\bin\"?

I saw your related issue #2127, it would be indeed a nice improvement.

**Comment by ekrich** [comment]
@david-bouyssie Looking at this code makes me think my answer above is completely wrong and I was thinking about how I would like it to be as outlined in #2127. The good news is that the clang discovery for windows has been merged and either having `clang.exe` in the PATH or using the full path like "CLANG_PATH=C:\Program Files\LLVM\bin\clang.exe" should work. I think we can close this ticket if you can confirm that `clang.exe` can be found on Windows.

**Comment by david-bouyssie** [comment]
I did my tests with a clone from this commit:
https://github.com/scala-native/scala-native/commit/15abb846e1ad7533e0614fe206164f9a6aef8096

Without the previously described fix I got an error when I was using ```CLANG_PATH=C:\Program Files\LLVM\bin\clang.exe```
I don't see any update regarding this code in recent commits. Do you have something specific in mind?

**Comment by ekrich** [comment]
I will look into it or get back with you.

**Comment by ekrich** [comment]
Workaround: Add path to `LLVM\bin` to the PATH. `CLANG_PATH` and `CLANGPP_PATH` env vars will not work yet because of issue #2333.

**Comment by ekrich** [comment]
Based on the way `where` works (shown below) on the windows platform it may be time to work on issue #2127. It requires a `path:pattern` and if we switched to requiring just a path to where `clang` and `clang++` exist then we could have just one env var for the path rather than one for  `clang` and one for `clang++`.  What is the chance that a developer or during CI that someone would want to use compilers that are not from the same distro?

Do we want to repurpose `CLANG_PATH` or do we want to use something else like `LLVM_BIN` which I found on the web used for this purpose? I propose we use `LLVM_BIN` but it could be breaking to some - likely very few.

I will go forward in this direction unless there are objections.

```
PS C:\Users\xxx\workspace\scala-native> C:\Windows\System32\where C:\Users\xxx\AppData\Local\LLVM\bin:clang
C:\Users\xxx\AppData\Local\LLVM\bin\clang.exe
PS C:\Users\xxx\workspace\scala-native> C:\Windows\System32\where C:\Users\xxx\AppData\Local\LLVM\bin:clang++
C:\Users\xxx\AppData\Local\LLVM\bin\clang++.exe
```
The full path to `where` is required in Powershell.

**Comment by david-bouyssie** [comment]
Maybe I don't understand but I don't see the point of using "where" if you can guess the directory.
A simple ```File(dir, exe).isFile```, shouldn't be enough?

**Comment by ekrich** [comment]
The goal is to use the system path and `clang` and get a full path to the executable using `which` or `where` so when you call `Process` you are sure it is going to work. If `clang` is not in the path it fails. Otherwise, for CI or if you want to try different versions of `clang` you can set an env var, in this case `LLVM_BIN`, and you can append `clang` and then run `which` or `where`. In this case you hope that it brings back the full path to the executable but if the path is wrong it won't and fails.

Once you have the full path to `clang`, we check the major version to make sure it is bigger that the minimum. So this is basically the simplest the code can be. I actually thought the code was pretty good plus `where` in Windows is more complex and allows you to search multiple paths etc.
