### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#233]
2.12 is near the end of the development cycle. We need to extend our nscplugin to support it.

**Comment by densh** [comment]
Here is the initial list of things that need to be done here:

- [ ] Update port of scala.runtime to reflect recent changes in scala/scala#5110 and scala/scala#5098
- [ ] Add proper support for closured to NIR
- [ ] Test support for SAMs and how it works with FunctionPtrN

**Comment by ZizhengTai** [comment]
Any update on this?

**Comment by densh** [comment]
@ZizhengTai We're currently focusing on improving javalib, 2.12 support is next on the list once we are reasonably happy with state of things on 2.11.

**Comment by densh** [comment]
We have to make sure we take this in mind: https://github.com/scala/scala/pull/5944

**Comment by fancywriter** [comment]
Hello from 2018! Do you have some news, do you need any assistance, just in case?

**Comment by ekrich** [comment]
@densh I was looking at this https://github.com/scala/scala-collection-compat/pull/45 and thinking that this could become more important when 2.12 support lands in Scala Native because then it seems that we could support 2.13 as well. It seems we have stubs for the methods that didn't link but when I inspect the class listed as suspect, I don't see any of the methods anyway now. 

Do you think someone could resurrect this PR if you think this makes sense? 

Will 2.11 still be supported as well?
