### ISSUE TITLE
Doc mention of `__empty.ll` is out of date

### ISSUE THREAD

**Issue by ebruchez** [scala-native/scala-native#2435]
In this file:

https://github.com/scala-native/scala-native/blob/master/docs/contrib/compiler.rst

`sandbox/run` now produces a series of numbered `.ll` files but none is called `__empty.ll`.

The doc should be updated to explain what the `.ll` files contain.

**Comment by densh** [comment]
Another thing that's out of date on that page is that dotty doesn't ship with LTO optimizer of their own.

**Comment by LeeTibbert** [comment]
I took a look at this issue whilst waiting for a PR to finish CI. 

It looks like the location for the `.ll` files given in the same paragraph
has changed with time.  I now see something like `sandbox/.3/target/scala-3.1.3`.

The files have names:
```
./native/2.ll
./native/3.ll
./native/1.ll
./native/0.ll
```

I think the intent of that paragraph can be provided
by file discovery instead of hard coding information which
changes.

```
// From the project root
find sandbox -name '*.ll'
```

I will try for another improvement sprint as I submit PRs and wait for their CI.
This update is in case someone gets there before I do.

**Comment by LeeTibbert** [comment]
@ebruchez PR #2679, once merged, should close this issue.  Sorry that it took so long.

I addressed your two , very accurate, concerns
1) __empty.ll no longer exists
2) Explain what .ll file are.

I did a `grep` of all the .rst file for the Contributor's Guide
for `dotty` and find nothing. Looks like someone had
previously addressed densh' concern.

`.rst` Rich Structured Text files are hard to read through
but if you notice anything that could be improved
once they reach ReadTheDocs, please let me know.

Again, thank you for your attention to detail and for
creating this issue.  People actually try to use
the docs to get work down and, I believe, it
should save them time not waste it.

**Comment by ebruchez** [comment]
Thanks for updating the doc, @LeeTibbert!
