### ISSUE TITLE
Throw compile-time error when `extern` cannot be used 

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#2498]
We should add a compile-time check when trying to use `extern` in an unsupported manner. 
For example `extern` cannot be used in `val foo: Int = extern`
Also, it should report usages as a default parameter of methods, if it is not runtime exceptions should contain information about unsupported usage of the extern method.

**Comment by riiswa** [comment]
Hi, I'd like to start contributing to Scala Native by fixing this issue (there is the good first issue tag), do you have any ideas where I can start? :)

**Comment by i10416** [comment]
Are all following codes supposed to throw compile-time error too?

- `def f[T](arg:T): R = extern`  Currently, runtime unexpected behavior (probably because of overload resolution)
- `def f[\@specialized(S0,S1,...) T]: R = extern` Currently, runtime unexpected behavior (probably because of overload resolution)
On the other hand,
- `def f[\@specialized(S0) T]: R = extern` Currently, It works🤔
