### ISSUE TITLE
support Scala 3.1.1

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/scala-native#2535]
https://github.com/lampepfl/dotty/releases/tag/3.1.1

🙏

**Comment by WojciechMazur** [comment]
Thank you for the report, we would release backported 3.1.1 support for 0.4.3-RC versions today and it would be included as well in the upcoming 0.4.3 release. 

Btw. It looks like you're using a non-standard Scala Steward instance. The current Scala release procedure was updated and standard Scala Steward is notified about new Scala versions when the core ecosystem dependencies are published. I would suggest using it instead when possible, because it would allow for a smoother upgrade, especially with Scala Native, Scala.js and other projects that are using Scala compiler as a dependency.

https://github.com/lampepfl/dotty/issues/14311 
https://github.com/scala-steward-org/scala-steward/blob/master/modules/core/src/main/resources/default.scala-steward.conf#L3

**Comment by WojciechMazur** [comment]
Compiler plugin artifacts for 0.4.3-RC1 and 0.4.3-RC2 were published to Maven repository, they should be available now

**Comment by xuwei-k** [comment]
Thanks!
