### ISSUE TITLE
Scala Native should not provide a cryptographically insecure `UUID.randomUUID()` implementation

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#2600]
Scala Native counterpart of https://github.com/scala-js/scala-js/issues/4657. See discussion there.

https://github.com/scala-native/scala-native/blob/30b6781ee3f1854e07ea5b9274179c14e0e5abd5/javalib/src/main/scala/java/util/UUID.scala#L137-L145

/cc @sjrd

**Comment by LeeTibbert** [comment]
Given that Scala.js has a CVE for this and, if I read correctly, made substantial changes as
a result, I believe this should be a BLOCKER for 0.5.0.  There is an argument that it
should be fixed in the 0.4.x stream earlier than that.

I think the, admittedly ugly, short term fix is to leave UUID and have `randomUUID()` 
be implemented as `???`.  Rude, yes, but first do no harm.

A proper fix probably leads directly thru Eric's #2601.  That is a lot of 
work and probably ends up, in the short to medium run, with randomUUID()
 unimplemented, just unimplemented somewhere else.

@armanbilge Since you discovered this, one or more of your projects
probably use `randomUUID()`.  How would it affect your projects if
`randomUUID()` threw an Exception?

Alternatively, did the way Scala.js fixed this work for you? From
my rapid tour, it appears they separated a library and used a
Node.js feature.    

I have not discovered a secure callable Linux
randomUUID, but I am only a few minutes into the search.
As with most things on the Internet, the probability of finding
something goes down inversely by some large factor of the time spent looking,
so I do not have my hopes up.  (libuuid provides uuids, but, I am told,
not secure ones. I need to poke into internals).

**Comment by armanbilge** [comment]
@LeeTibbert thanks for your interest in this!

> I have not discovered a secure callable Linux randomUUID, but I am only a few minutes into the search.

The good news is we don't actually need a `randomUUID()`. We just need a source of cryptographically strong random numbers, then we can implement `randomUUID()` ourselves.

Indeed, this is how Scala.js solved the issue in https://github.com/scala-js/scala-js/pull/4659. They implemented `randomUUID()` in Scala.js core in terms of `java.security.SecureRandom`, which is _not_ implemented in Scala.js core.

Then they published a separate artifact that implements `SecureRandom` for Node.js and browsers using the APIs available in those runtimes.
https://github.com/scala-js/scala-js-java-securerandom/

> Alternatively, did the way Scala.js fixed this work for you?

Unfortunately not. Besides publishing the true `SecureRandom` implementation I linked above, for backwards-compatibility they also published a "fake", insecure implementation. Unfortunately many users have not been able to appreciate the risk of this artifact despite the multiple warnings. For example in https://github.com/scalatest/scalatest/issues/2116 and https://github.com/scoverage/scalac-scoverage-plugin/pull/459 the fake insecure one was used, and this was a serious mistake. See discussion in https://github.com/scala-js/scala-js/issues/4663#issuecomment-1141787032.

> Since you discovered this, one or more of your projects probably use randomUUID(). How would it affect your projects if randomUUID() threw an Exception?

We would be unaffected by any changes here. Cats Effect has its own `UUIDGen` and `SecureRandom` abstractions and due to this vulnerability and the existence of "fake" implementations we have decided to stay away from the Java APIs. Instead, we inline our own implementations of these, that are guaranteed to be secure. See https://github.com/typelevel/cats-effect/pull/2945.

---

> There is an argument that it should be fixed in the 0.4.x stream earlier than that.

I agree. If Scala Native wants to be taken seriously, then it must take security issues seriously. So, what to do for 0.4.x?

> I think the, admittedly ugly, short term fix is to leave UUID and have `randomUUID()`
be implemented as `???`. Rude, yes, but first do no harm.

We can do a bit better and follow Scala.js lead here, and implement it in terms of `java.security.SecureRandom`. Then, we leave it to the user to provide their own implementation of `java.security.SecureRandom`. This has the advantage it will be a link-time error, instead of a runtime error, and that a user _can_ solve it, unlike `???` for which there is no userland fix.

If this strategy is acceptable, I am happy to make the PR.

**Comment by ekrich** [comment]
If you have time for an experiment and follow the way Scala.js does it would be a good idea.

**Comment by armanbilge** [comment]
@ekrich not really an experiment, it was quite straightforward to port the Scala.js changes :) see https://github.com/scala-native/scala-native/pull/2759. Thanks for the nudge.

**Comment by LeeTibbert** [comment]
@armanbilge  Thank you for taking a run at this.  Asking, or considering what SJS would do a second time around
is certainly worthwhile.  I personally, and from my quick reading the original Scala.js work think that providing
a 'weak' version of a documented 'secure' method has massive negative value.

When to provide the error, runtime vs linktime, is, I think, one of those "designer choice" decisions, where
different designers make different decisions; your effort, your call.   On the "linktime" path, I recommend
putting a reminder about "link stubs' in the Change Note.  I can understand a preference for "linktime"
but breaking an application developers work permanently for what may be to them a minor feature
is not, in my book, kind.  Yes, I can understand entirely, and probably agree with, the feeling that
if people discover how to take blade guards off, that is on them, but we should not be telling
them how to do it.  

On the 0.5.0 train I have fewer concerns about hard breaking applications.  My concerns
are greater on the 0.4.x train.  

I am not trying to make things so difficult they never get done, just collegial discussion.

**Comment by sjrd** [comment]
If we could do it all over from scratch, without compatibility in mind, we would do exactly what we ended up doing except publishing the insecure version.

The only reason we did publish the insecure version is this:

> but breaking an application developers work permanently for what may be to them a minor feature
> is not, in my book, kind

**Comment by armanbilge** [comment]
>  I personally, and from my quick reading the original Scala.js work think that providing
a 'weak' version of a documented 'secure' method has massive negative value.

Yes, absolutely agree with this.

>  I can understand a preference for "linktime" but breaking an application developers work permanently for what may be to them a minor feature is not, in my book, kind.

Hmm, I am confused by what you mean here. Implementing `randomUUID()` with `???` as you propose would definitely break application developers work permanently, and with no warning, since they are unable to change the implementation.

Meanwhile, by implementing `randomUUID()` with `SecureRandom`, it creates a linking error that can warn the developer ahead of time, and that they can solve themselves by providing a suitable implementation of `SecureRandom` in their application. So I wouldn't describe it as "permanent" at a all :)

> On the 0.5.0 train I have fewer concerns about hard breaking applications. My concerns
are greater on the 0.4.x train.

Sure, there is a trade-off here. We have to weigh shipping a vulnerability against breaking applications. I won't fight to include this in 0.4.x because adoption is so low. It's the question of how serious Scala Native is about security issues.

---

One more option is we can actually try to implement `randomUUID()` correctly using cryptographically strong random values. This was impossible for Scala.js to do because the JavaScript standard doesn't include a suitable API, but we can probably do it here. However, this would be going against your proposal to stop adding security-related classes in Scala Native in https://github.com/scala-native/scala-native/issues/2601#issuecomment-1196638517.

**Comment by LeeTibbert** [comment]
> Hmm, I am confused by what you mean here. Implementing randomUUID() with ??? as you propose would definitely break 
> application developers work permanently, and with no warning, since they are unable to change the implementation.

I did not explain myself well enough. Hazards of typing before finishing my morning coffee (What was Eric saying the other day about that?).    

I see what you mean. If you implement on the basis `secureRandom()` a developer could always write
their own, `secureRandom`. It it happened to be something non-secure that is their considered decision.
IMO, a change note could suggest "writing your own or find 3rd party".
If I were doing it, I would not go into detail.  We might have to do that on support channels (but should
still not describe something insecure (I am honoring the Scala.js "2nd time around"  learnings here.)

> One more option is we can actually try to implement randomUUID() correctly using cryptographically strong random values. 

TL;DR  I recommend against, but am not the one doing the work.

When faces with Software Engineering design & resource allocation issues, I always like to step
back and ask 3 questions:
1) Does this feature have an identifiable present or near future sponsor/champion/user?

2) If/When this work ships, who is going do maintain this work for the next decade?
    Are we going to have or be able to train quickly enough, someone to do fixes correctly,
    especially if/wen Institutional Knowledge is lost beyond recovery?

3) How does this feature compete with other proposed features for customer
    benefit and present devo resources?

All that said, my memory is hazy but I think that you and Typelevel 
decided to  directly implement either `randomUUID()` or `secureRandom()` for exactly
the reasons that doing the latter in Scala Native, across Linux, macOS, Windows, & 
myDogWalkersOS  would be so difficult.  Is that code suitable for SN (cut & paste of
source)?  What is the licensing?

Where do your interests lie? 

As long as we are generating possibilities, perhaps instead of having a `SecureRandom.scala` file
and a publicly visible `SecureRandom` class is that `armansSecureMagic` (not `SecureRandom`) be a 
Scala `private` routine in the existing `UUID.scala` file.

Ugly, but limits the commitment you are, implicitly, making.  I have not looked at the contents and
requirements of `SecureRandom` to see if this is feasible or wise. 

My goal here is to be collegial and supportive, even if I would do things differently.

**Comment by armanbilge** [comment]
> If you implement on the basis `secureRandom()` a developer could always write
> their own, `secureRandom`. It it happened to be something non-secure that is their considered decision.
> IMO, a change note could suggest "writing your own or find 3rd party".
> If I were doing it, I would not go into detail.

Yes, I think we are in agreement about this :) in fact, in some cases the best advice turned out to be "actually, you don't need UUID here at all :)" For example see https://github.com/scalatest/scalatest/pull/2117. In situations where you absolutely _do_ need a UUID, you should definitely be conscious about how it is being generated.

---

> As long as we are generating possibilities, perhaps instead of having a `SecureRandom.scala` file and a publicly visible `SecureRandom` class is that `armansSecureMagic` (not `SecureRandom`) be a Scala `private` routine in the existing `UUID.scala` file.

I thought about this as well. I suppose it could be a band-aid for 0.4.x, but I am afraid it is only making a new promise that we intend to break. In my opinion `randomUUID()` should absolutely delegate to `SecureRandom` as the platform's canonical source of cryptographically strong random values, although I do not think this is required by the Java Specification.

---

> All that said, my memory is hazy but I think that you and Typelevel
> decided to directly implement either `randomUUID()` or `secureRandom()` for exactly
> the reasons that doing the latter in Scala Native, across Linux, macOS, Windows, &
> myDogWalkersOS would be so difficult. Is that code suitable for SN (cut & paste of
> source)? What is the licensing?

You remember correctly. I will link the code below. It currently only supports Linux / modern macOS and I believe is making sub-optimal use of the `getentropy` routine, which ideally should be used for _seeding_ a cryptographically strong random generator instead of the direct source of random values.

https://github.com/typelevel/cats-effect/blob/c1c5b1734a88c2104e606426e141f8426acb8e86/std/native/src/main/scala/cats/effect/std/SecureRandomCompanionPlatform.scala

The goal of that implementation in Cats Effect is to have something secure and correct that we can iterate and improve on later. Scala Native support is still experimental at this stage.

If we were to include something like that in Scala Native core would need to account for Windows at the very least.

---

> TL;DR I recommend against, but am not the one doing the work.

I concur with your recommendation.

**Comment by armanbilge** [comment]
This is fixed as of 0.4.6/0.4.7.

**Comment by lolgab** [comment]
`java.security.SecureRandom` is now provided by `"com.github.lolgab" %%% "scala-native-crypto" % "0.0.3"` which uses openssl underneath.
It can be used to fix linking issues like:
```
[error] Found 2 missing definitions while linking
[error] Not found Top(java.security.SecureRandom)
[error]         at /home/wmazur/projects/scalacenter/scala-native/scala-native/javalib/src/main/scala/java/util/UUID.scala:140
[error] Not found Member(Top(java.security.SecureRandom),RE)
[error]         at /home/wmazur/projects/scalacenter/scala-native/scala-native/javalib/src/main/scala/java/util/UUID.scala:138
```

**Comment by ekrich** [comment]
Maybe the release notes could add some info if the site can be updated.
