### ISSUE TITLE
User Guide stackalloc description gives old, not current, memory clearing behavior

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2764]
The interop section of the 0.5.0-latest User's Guide (and many a previous version) describes
`stackalloc` and explicitly states `Memory is not zeroed out by default`.  This has been untrue
for a number of Scala Native 0.4.x. versions. Given that those versions have shipped,
it would be very hard to have `stackalloc` revert to its previous behavior.  I know
that a number (10?, 20?) places within Scala Native itself describe relying
upon the current clearing behavior.

I think it is time to correct that section of the User's Guide to have it describe,
and make official, the current clearing behavior. 

The impact of the outdated description is that users in the field may
be believing it and manually clearing already cleared memory.
This increases application execution time for no good reason.

  Given that go ahead, I will submit a PR.

Please advise.

Editorial comment:  having `stackalloc` clear is absolutely bonkers, but it is the way it is
                                and the way it has been for more than a year. Like language
                                dictionaries, the doc should describe current, not ideal, practice.

**Comment by ekrich** [comment]
I think this could be revisited but we would need to find out why it was changed. The only thing I can think of right away is that maybe this was done because Java initializes primitives to default values, 0, false etc. Default values here: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

If we are going to eventually have structs and case classes etc. on the stack then perhaps we would want this initialization. Also, C has a way to zero structs and arrays easily. However, I don't think any of this is set in stone so if we want to change things like this we should change it now rather than later.

Either way we should have documents that explain this one way or the other. If you want to change this back to the old way maybe you can research (git-blame) and try and figure out why it was changed and make a new proposal issue.

**Comment by LeeTibbert** [comment]
Eric, thank you for your thoughts. I mostly concur.  My overall thought is that `stackalloc()` clearing has been
shipping for so many versions that Scala Native owns it as it is.  I recall that it was done for 'because Java' does that.
To my thinking any non-clearing method would have to have a new name, leaving the current with its 
clearing behavior.  

I think changing the docs to reflect current behavior is the minimal change to create/preserving docs
that people can believe and code to as accurate.  

I know that I do not have cycles to fix the world, especially when at least two people actually
__like__ the current behavior.  Ugly is in the eye of the beholder.  (When this change was
made, I was in no position to suggest against, so I have to wear that).

**Comment by ekrich** [comment]
Well, we do want the highest performance and only interopt code can be `stackalloc`ed so I think your argument is good. If we do `stackalloc` `CStruct`s and `Object`s then could figure that out then and do the right thing when generating code as needed. I believe the idea was to have an annotation or just do it by default. I think it may be better to discuss this on a new issue. The sooner we potentially break things if needed the better.
