### ISSUE TITLE
`Not found Member(Top(java.net.Inet6Address))` issue

### ISSUE THREAD

**Issue by fiatjaf** [scala-native/scala-native#2784]
The error happens when doing a `ǹativeLink`, apparently something is missing in a library:
```
[warn] Found a call to not defined static method Member(Top(java.net.Inet6Address),D12getByAddressL16java.lang.StringLAb_L25java.net.NetworkInterfaceL21java.net.Inet6AddressEo). Static methods are generated since Scala Native 0.4.3, report this bug in the Scala Native issues. Call defined at file:/home/fiatjaf/comp/scoin/shared/src/main/scala/ln/CommonCodecs.scala:136:55
[error] Found 2 missing definitions while linking
[error] Not found Member(Top(java.net.Inet6Address),D12getByAddressL16java.lang.StringLAb_L25java.net.NetworkInterfaceL21java.net.Inet6AddressEo)
[error] 	at /home/fiatjaf/comp/scoin/shared/src/main/scala/ln/CommonCodecs.scala:136
[error] Not found Top(java.net.NetworkInterface)
[error] 	at /home/fiatjaf/comp/scoin/shared/src/main/scala/ln/CommonCodecs.scala:136
[error] Undefined definitions found in reachability phase
[error] (Compile / nativeLink) Undefined definitions found in reachability phase
[error] Total time: 18 s, completed Aug 12, 2022, 8:54:09 AM
```

See the error in CI here: https://github.com/fiatjaf/poncho/runs/7805958225?check_suite_focus=true#step:6:19

To reproduce locally, run:
```
git clone git@github.com:fiatjaf/poncho -b next
cd poncho
sbt nativeLink
```

The library being imported is [scoin](https://github.com/fiatjaf/scoin/tree/v0.2.0), authored by me.

The weird thing is that the library compiles fine and publishes fine and I even used it this week (using v0.2.0-SNAPSHOT and `publishLocal`) to compile locally [another app](https://github.com/fiatjaf/openchain/tree/2edfe7dc86ff1d830ea37a0ff36874fdb1a54b7a/miner) that depended on `scoin` (although it didn't use the `CommonCodecs` object).

**Comment by armanbilge** [comment]
Thanks for the report. I wouldn't say it's "weird", simply that method has not been implemented in Native Javalib yet :)

https://github.com/scala-native/scala-native/blob/333af14f936a42b374be503186252d8ae84ad239/javalib/src/main/scala/java/net/Inet6Address.scala#L70

**Comment by armanbilge** [comment]
> The weird thing is that the library compiles fine and publishes fine and I even used it this week

Yes, linking errors don't appear at compile time. A library can compile fine, even if Scala Native has not implemented those JDK APIs.

You can even use that library, so long as you don't call any methods that call the unimplemented JDK APIs.

**Comment by fiatjaf** [comment]
How can I check if a library is able to "link" fine before publishing it?

**Comment by armanbilge** [comment]
By writing tests, and running them :)

**Comment by fiatjaf** [comment]
This is sad. I don't want to do that.

**Comment by fiatjaf** [comment]
Anyway, thank you!

**Comment by armanbilge** [comment]
@fiatjaf you can leave this issue open, as a reminder to implement that method. Perhaps it's not too hard and one of the gang will pick it up ;)

**Comment by LeeTibbert** [comment]
@fiatjaf   Sorry that you experience this & thank you for reporting this.

It is great to see someone (attempting to) use IPv6.

I know that it is not always possible to change code. I will give you the lay 
of the land, as I know it.  

I lost track, are you doing unix, Windows, or both/all? 

##### Working
`posixlib` IPV6 & UDP are implemented and working in 0.5.0-SNAPSHOT.
`sendmsg`, `recvmsg`, and a number of performance improvements are 
in the the PR queue for 0.5.0-SNAPSHOT, awaiting their turn.

I have put a lot of work into implementing them & writing unit-tests for them.
"A lot of work' does not insure correctness, but at least someone has
visited the back 40 acres (20 or so hectares? ) recently.

In SN `0.4.x` The `sendto` & `recvfrom` methods either do not exist
or do not function. The `sendmsg` & `recvmsg`  are not implemented.

#####  Known not working

The fact that javalib has _any_ networking support is a tribute
to the authors/porters of that code.

IPv6 and UDP did not make the implementation of javalib.
They were left as an exercise for a future generation.

Implementing them is non-trival, so I have not gotten to it yet.
There is a huge amount of code which needs to be ripped out
because we are going on 15 or so years since the original
Harmony code.

Implementing `java.net.Inet6Address` is blocked by
the code in javalib which assumes that only IPv4
exists and "localhost" is always "127.0.0.1".

IIRC, there are enough references to IPv6 in
that directory to make one expect that IPv6 was
implemented.  I certainly did the first 15 or
20 (well more like 40) times I looked in 
that directory.

Are you actively using `Inet6Address` methods  or just expect the
class to exist?

**Comment by fiatjaf** [comment]
Thank you for this long explanation.

I am using only Linux.

I am porting this library/thing that was written for Scala JVM to Scala Native and Scala JS. It is basically just a big collection of helper methods, types and codecs. The IPv6 code here is just parsing an address from what I could understand.

There is another related project that uses this library and actually does network connections using `java.net.Socket` directly which I think is a raw TCP socket (is it?). I didn't expect that part to be available on SN and was thinking about how I could implement it myself using some C library, but I don't understand these low-level things very well, it would be for the distant future though.

That is to say, I just need to be able to parse the IPv6 addresses, but if that is too hard I think it is fine to remove that part from the SN version for now or replace it with just returning an error. Very few people use IPv6 anyway.

**Comment by armanbilge** [comment]
> That is to say, I just need to be able to parse the IPv6 addresses

@fiatjaf You may look at https://github.com/comcast/ip4s. I have some native snapshots available.
https://s01.oss.sonatype.org/content/repositories/snapshots/com/armanbilge/ip4s-core_native0.4_3/

**Comment by fiatjaf** [comment]
Wait, my linking is failing because `getByAddress` does not exist, but it does exist!
https://github.com/scala-native/scala-native/blob/333af14f936a42b374be503186252d8ae84ad239/javalib/src/main/scala/java/net/Inet6Address.scala#L55-L68

My code is calling it with `Inet6Address.getByAddress(null, something that is a Array[Byte], null)`

What is the issue then?

**Comment by LeeTibbert** [comment]
> That is to say, I just need to be able to parse the IPv6 addresses, but if that is too hard I think it is fine to remove that part from 
> the SN version for now or replace it with just returning an error.

Implementing parsing IPv6 addresses is a pain, even if one is an IPv6 expert.  There is a whole other Universe
of concepts to get right.

Depending upon the data you have at hand, a String such as "::1", there are some routines in `clib` which
do the parsing using the system provided C (netdb) implementation.  If that gets the parse wrong, at least it
is not your problem :grin:.

There are some examples in the SN unit-tests of how to use them.  I believe that "Udp6SocketTest.scala"
does so. 

Can you post "This is my input", "This is the output I would like to get"?

**Comment by armanbilge** [comment]
@fiatjaf indeed, there are two methods named `getByAddress`.

You are calling the overload that is _not_ implemented. If you change your calling signature, you can use the one above which is implemented.

https://github.com/scala-native/scala-native/blob/333af14f936a42b374be503186252d8ae84ad239/javalib/src/main/scala/java/net/Inet6Address.scala#L55-L59

https://github.com/scala-native/scala-native/blob/333af14f936a42b374be503186252d8ae84ad239/javalib/src/main/scala/java/net/Inet6Address.scala#L70

**Comment by LeeTibbert** [comment]
As a quick shot while I am chasing this, you could change the rightmost null to a 0. 
That might do what Arman described: get the right call signature.

I will take me a few minutes to chase the type  'nif: NetworkInterface'  It is 
probably `AnyRef`, meaning that your null pointer matches that, not 
the Int of the implemented method.

**Comment by LeeTibbert** [comment]
Network Interface is defined in Java 8 as derived from Object, so it is an `AnyRef` (something
referred to by a pointer, such as null.)

If I had to spin a yarn, I would say that the call with null as the third argument did not
match the existing method declaration (which expected an Int).  Since there was
no match, no method was called in the Object and Dead Code Elimination (DCE)
removed it.

I am going to await the results of your trying a 0 as the third arg.  My morning
walk is calling.

Please advise.  & Good Luck.

**Comment by LeeTibbert** [comment]
From the base post:
> Not found Top(java.net.NetworkInterface)

There is the indication that the third argument to the call being
null caused the missing prototype to be sought.

**Comment by fiatjaf** [comment]
This is fixed for me by specifying the parameters as a blank `String` and a `0` in my call instead of `null` and `null`. Should we close this issue?

**Comment by LeeTibbert** [comment]
Yes, please.  That keeps the decks cleared and ready for action.

I am glad that you were able to solve the problem.  

I had missed the other `null` argument, thinking it would be
OK since it was a pointer, used in a position which required
a pointer. "" is better practice anyway. I have a Scala induced
dislike of `null`.
