### ISSUE TITLE
Avoid allocation in ieee754tostring implementations

### ISSUE THREAD

**Issue by david-bouyssie** [scala-native/scala-native#2902]
I'm having a look at ieee754tostring classes, and I'm wondering if won't be better to accept a custom Array[Char] and an offset instead of allocating a new one:
https://github.com/scala-native/scala-native/blob/cf6d1a4de1e1a9386fc437119158dc7384b9a58e/nativelib/src/main/scala/scala/scalanative/runtime/ieee754tostring/ryu/RyuDouble.scala#L871

The risk is to have an Array that is too small, but I guess this can be checked, and also since it is internal code, things are a bit under control.

**Comment by david-bouyssie** [comment]
Reply from @densh on Discord:
_For internal code, refactoring to avoid allocation and pass destination from the caller as an argument is in fact a great idea, as long we think through of potential error cases and make sure they don't happen in our code (common pitfalls: accidental aliasing, or writing to data which should have been immutable).  The technique is also known as destination passing style (there is a paper with the same name that shows how it can be used to compile functional languages), and it's a common technique for manually avoiding unnecessary memory copies in C/C++._

**Comment by LeeTibbert** [comment]
@david-bouyssie   Let me try to catch my understanding up.

IIUC, you have actual places where you call `RyuDouble.doubleToString()`.
You are proposing passing in an `Array[Char]` and having the method
return a String?

Or are you proposing a new, say, `RyuDouble.doubleToProvidedArrayChar(): Unit`
(leaving aside, for the moment, issues of how errors might be returned. C code
has a hard time `throw`ing (but it can signal() real well ;-) having lived thru
many Issues with the latter.)

If you have something local running at the usual huge scale of your endeavors,
what results are you seeing?

Thanks,

Lee

Background:  
* I checked the Ryu repository to update my brain.  That line is 
  a literal translation  of the Java code. So nothing introduced in SN port.
  Not to say it is right, just accurate.

* The only SN caller of `RyuDouble.doubleToString()` is javalib 
  `Double.scala#toString`.  

* The SN implementation was announced a long time on the
   Ryu repository page as existing.  I know of no direct users
   but, I believe, we must behave as though at least one exists.
   That means preserving the current method but also does
   not mean that an overload is not possible/feasible.

**Comment by david-bouyssie** [comment]
Sorry I'm lacking time for a detailed reply, but briefly here is what I would like to do inside the `StringBuilder` class.

The goal is to replace `StringBuilder.append(d: Double)`:

```scala
  def append(d: scala.Double): StringBuilder = {
    append0(Double.toString(d))
    this
  }
```
by
```scala
  def append(d: scala.Double): StringBuilder = {
    this.ensureCapacity(this.count + _RyuDouble.RESULT_STRING_MAX_LENGTH)
    this.count = _RyuDouble.doubleToChars(d, RyuRoundingMode.Conservative, value, this.count)
    this
  }
```

This means that we can thus pass the portion of SB backing Array where the _RyuDouble can encode the Double value, saving thus an extra String/Array  allocations.
I will  submit a the PR to show my current implementation.

**Comment by LeeTibbert** [comment]
Pending data, this looks like a good change.

You have probably confirmed already that the Chars in doubleToChars are 2-byte Java Chars?

The only real concern I have is with `RyuRoundingMode.Conservative`. Is that what is being
used now under the covers when called from javalib?  There is an entire continent-wide
swamp around rounding modes and the ability to set them, or not, and the default modes.

I seem to have a _dim_ memory of the current rounding mode as being a "best approximation"
rather than exact match for JVM. I would have to check, but I think JVM has some quirks in
rounding mode.    Please do not take any of this, except the "beware the swamp" part, as
fact.

**Comment by david-bouyssie** [comment]
>You have probably confirmed already that the Chars in doubleToChars are 2-byte Java Chars?

What do you mean by confirming?

>The only real concern I have is with RyuRoundingMode.Conservative. Is that what is being
used now under the covers when called from javalib? There is an entire continent-wide
swamp around rounding modes and the ability to set them, or not, and the default modes.
I seem to have a dim memory of the current rounding mode as being a "best approximation"
rather than exact match for JVM. I would have to check, but I think JVM has some quirks in
rounding mode. Please do not take any of this, except the "beware the swamp" part, as
fact.

Honestly I have just followed what is currently done in `Double.toString`
https://github.com/scala-native/scala-native/blob/1db4999aecbff4d8d3498c573f9524110516e70c/javalib/src/main/scala/java/lang/Double.scala#L321

As you previously verified _The only SN caller of `RyuDouble.doubleToString()` is javalib `Double.scala#toString`"_.

I have not investigated alternative rounding modes, as it is not the main purpose of this issue, so I can't tell too much if it is the best way to go. I'm just blindly trusting the selected strategy 😄

**Comment by LeeTibbert** [comment]
> RyuDouble.doubleToString(d, RyuRoundingMode.Conservative) 

Ah, if that was the prior art, you have answered my question: you/we are introducing no changes.
> What do you mean by confirming?

Looking a the Ryu code.   

I took a quick look at the existing Ryu code. Everything there uses Java 2-byte
Character values, so that question is answered

Looks like ` _RyuDouble.doubleToChars` is a proposed new addition.
Did I miss something?

If I understand correctly, the existing `RyuDouble.doubleToChars` would
become a wrapper around the new `RyuDouble.doubleToChars()` which
would allocate 24 Array[Character], pass it to `RyuDouble.doubleToChars()`,
and convert the Array to a String on the way home.

The existing `doubleToString` body would need a few changes: name, arguments,
one place where it allocates an array, and deleting the final `toString()`.

I would probably drop the leading '_' but am not against it.

I think there was some discussion, but no action as of the date of the port
to SN, to do something like that in the Ryu repository.

**Comment by david-bouyssie** [comment]
>Looks like _RyuDouble.doubleToChars is a proposed new addition.
>I would probably drop the leading '_' but am not against it.

Sorry, this comes from a quick&dirty copy pasting of code from my Sandbox, not relevant.

>If I understand correctly, the existing RyuDouble.doubleToChars would
become a wrapper around the new RyuDouble.doubleToChars() which
would allocate 24 Array[Character], pass it to RyuDouble.doubleToChars(),
and convert the Array to a String on the way home.
The existing doubleToString body would need a few changes: name, arguments,
one place where it allocates an array, and deleting the final toString().

It is exactly what I had in mind :)

And since, sometimes, a PR is better than a long speach, here we go: https://github.com/scala-native/scala-native/pull/2917
