### ISSUE TITLE
javalib j.l.String#getValue needs to be expunged

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#2927]
Whilst attempting to fix #2925, I discovered the javalib `java.lang.String` method

` def getValue(): Array[Char] = value`

This method has two defects and needs to be expunged.
* It breaks the Java guarantee immutability of Strings, in a major way!
  Yes, SN build trickery provides some invisibility of the entry point,
  but it is still a hazard.

* The entry point is not in Java {8, 15, I_stopped_looking}.

It is unused in the SN codebase and adds cognitive cost without benefit.

**Comment by david-bouyssie** [comment]
I totally agree, it will definitely increase robustness and avoid mistakes/regressions.

I was also disturbed by this one, but since at the beginning I wanted to focus on new features, rather than bug hunting, I let it untouched.
Now I realize, that avoiding potential/existing bugs before trying implement new features may have been a better strategy...

I'm not legitimate (yet?) but LGTM.
