### ISSUE TITLE
`getByName("foo")` no longer throws `UnknownHostException`

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#3005]
### 0.4.7

```scala
//> using platform "native"
//> using nativeVersion "0.4.7"

import java.net.InetAddress

@main def main = InetAddress.getByName("foo")
```
```
java.net.UnknownHostException: foo: Name or service not known
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at java.net.InetAddressBase.$anonfun$1(Unknown Source)
        at java.net.InetAddressBase$$Lambda$8.apply(Unknown Source)
        at scala.Option.getOrElse(Unknown Source)
        at java.net.InetAddressBase.getByName(Unknown Source)
        at java.net.InetAddress.getByName(Unknown Source)
        at test$package$.main(Unknown Source)
        at main.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

### 0.4.8

```
java.io.IOException: No address associated with hostname
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at java.io.IOException.<init>(Unknown Source)
        at java.net.InetAddress$.getByNonNumericName$$anonfun$1(Unknown Source)
        at java.net.InetAddress$$$Lambda$6.apply(Unknown Source)
        at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
        at java.net.InetAddress$.getByNonNumericName(Unknown Source)
        at java.net.InetAddress$.getByName$$anonfun$1(Unknown Source)
        at java.net.InetAddress$$$Lambda$8.apply(Unknown Source)
        at scala.Option.getOrElse(Unknown Source)
        at java.net.InetAddress$.getByName(Unknown Source)
        at java.net.InetAddress.getByName(Unknown Source)
        at test$package$.main(Unknown Source)
        at main.main(Unknown Source)
        at <none>.main(Unknown Source)
        at <none>.__libc_start_main(Unknown Source)
        at <none>._start(Unknown Source)
```

**Comment by armanbilge** [comment]
I've added a test demonstrating the problem in 9b8f2cf6b1da1aa1c49c951a3a1f2474cf473e86.

**Comment by ekrich** [comment]
The previous behavior on `0.4.7` was correct and the message matched on the JVM.

**Comment by LeeTibbert** [comment]
Arman,

Sorry that you encountered this regression & thank you for reporting it.

 I will look into it.

There is a unit-test case which should have caught the un-intended change
before it shipped.  I will have to understand why it did not.

```
 // case from 'Comcast/ip4s' project, lookup non-existing host.              
    assertThrows(
      "getByName(not.example.com)",
      classOf[UnknownHostException],
      InetAddress.getByName("not.example.com")
    )
```

**Comment by LeeTibbert** [comment]
Can not replicate "foo" on clean repository 0.5.0-SNAPSHOT. Which is not to say that you are not
experiencing it on 0.4.8.     I will try 0.5.0-SNAPSHOT InetAddressTest with both "example" and "not.example.com"

I will set up a 0.4.8 environment (probably by hacking epollcat) to see what I get.   Will keep folks posted.

**Comment by armanbilge** [comment]
Huh that's strange, I was able to replicate in 0.5.0 in https://github.com/scala-native/scala-native/commit/9b8f2cf6b1da1aa1c49c951a3a1f2474cf473e86.

**Comment by armanbilge** [comment]
```
$ uname -a
Linux armanbilge-scalanative-7yqib28iyt2 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

I checkout https://github.com/scala-native/scala-native/commit/9b8f2cf6b1da1aa1c49c951a3a1f2474cf473e86 and run

```
sbt:scala-native> tests2_13/testOnly *.InetAddressTest
...
[error] Test javalib.net.InetAddressTest.getByName failed: java.lang.AssertionError: getByName(foo): unexpected exception type thrown; expected:<java.net.UnknownHostException> but was:<java.io.IOException>, took 0.153 sec
[error]     at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
[error]     at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
[error]     at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
[error]     at java.lang.StackTrace$.currentStackTrace(Unknown Source)
[error]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
[error]     at java.lang.AssertionError.this(Unknown Source)
[error]     ...
[error] Caused by: java.io.IOException: No address associated with hostname
[error]     at java.lang.StackTrace$.$anonfun$currentStackTrace$1(Unknown Source)
[error]     at java.lang.StackTrace$$$Lambda$2.apply(Unknown Source)
[error]     at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
[error]     at java.lang.StackTrace$.currentStackTrace(Unknown Source)
[error]     at java.lang.Throwable.fillInStackTrace(Unknown Source)
[error]     at java.io.IOException.this(Unknown Source)
[error]     at java.net.InetAddress$.$anonfun$getByNonNumericName$1(Unknown Source)
[error]     at java.net.InetAddress$$$Lambda$2.apply(Unknown Source)
[error]     at scala.scalanative.unsafe.Zone$.apply(Unknown Source)
[error]     at java.net.InetAddress$.getByNonNumericName(Unknown Source)
[error]     at java.net.InetAddress$.$anonfun$getByName$1(Unknown Source)
[error]     at java.net.InetAddress$$$Lambda$4.apply(Unknown Source)
[error]     at scala.Option.getOrElse(Unknown Source)
[error]     at java.net.InetAddress$.getByName(Unknown Source)
[error]     at java.net.InetAddress.getByName(Unknown Source)
[error]     at javalib.net.InetAddressTest.$anonfun$getByName$2(Unknown Source)
[error]     at javalib.net.InetAddressTest$$Lambda$8.apply(Unknown Source)
[error]     at org.scalanative.testsuite.utils.AssertThrows$$anon$2.run(Unknown Source)
[error]     ... 44 more
...

**Comment by LeeTibbert** [comment]
With a quick 0.4.8 SN 2.13 test gbn("foo") gives 

`java.net.UnknownHostException: Name or service not known`

I think we corrected the lack of the hostname just after 0.4.8 was 
released. I believe that fix is queued for 0.4.9.

I will do the checkout you recommend and study your configuration.

**Comment by LeeTibbert** [comment]
I cloned the repository you stated and copied over the file with the changes. Then I ran on Scala 2.13, Java 8.mumble,
as simply "sbt" then "sbt> tests2_13/testOnly *.Inet*".   I was not able to replicate the failure.  
Again, that is not to say that you are not seeing it. It is still a concern.

My current thinking is a transient name server issue in your environment.  `getaddrinfo()` may be returning
EAI_AGAIN instead of EAI_NONAME.   I think we are going to ask someone additional to try to replicate.

By any chance, is the machine you are experiencing this on a virtual machine?

**Comment by armanbilge** [comment]
> My current thinking is a transient name server issue in your environment. `getaddrinfo()` may be returning
> EAI_AGAIN instead of EAI_NONAME. I think we are going to ask someone additional to try to replicate.

Btw, I added a `println` and it is returning `-5`.

**Comment by LeeTibbert** [comment]
In 0.4.7 any error from `getaddrinfo()` would cause the `UnknownHostException`.

// 0.4.7 InetAddress.scala
```
 } else {
      val ip = SocketHelpers.hostToIp(host).getOrElse {
        throw new UnknownHostException(
          host + ": Name or service not known"
        )
```
// SocketHelpers.scala
```
val status = getaddrinfo(toCString(host), null, hints, ret)
      if (status != 0)
        return None
```

This changed in 0.4.8 to attempt to report the actual error. If EAI_AGAIN (or ilk) had previously been reported
in 0.4.7 as UnknownHostException it will now be reported as IOException() and give the results in the base
of this Issue.

Here we have the inverse situation of having the text and wishing for the actual gai_errno number. 
Life can be strange.  The difficulty is that the two texts are almost the same.

I can provide an `InetAddress.scala` which edits the IOException message or I can post
the changes to one line.   Perhaps if we could get the gai_errno number where it is occurring
than might help us make progress.

Is the "not.example.com" case passing for you?  Must be, or else you would have mentioned it.
Does changing from "foo" to, say, "perdition" give the UnknownHostException?

Sometimes a simple "abc" (no .domain) takes an expedited path where "abc.org" takes
the longer trip to the name/bind server.

**Comment by armanbilge** [comment]
> Perhaps if we could get the gai_errno number where it is occurring
than might help us make progress.

Sorry, should have shared it before: `-5`.

> Is the "not.example.com" case passing for you? Must be, or else you would have mentioned it.
Does changing from "foo" to, say, "perdition" give the UnknownHostException?

It is passing. I can try `perdition` and report back.

**Comment by armanbilge** [comment]
Hmm, you're right. `perdition` gets me an `UnknownHostException`.

**Comment by LeeTibbert** [comment]
I think the 0.4.8 changes are doing their job, as time consuming that is for us.

The CI stack trace gives "Caused by: java.io.IOException: Temporary failure in name resolution"
I believe that would translate to EAI_AGAIN.  

Now the question becomes what do we want to do about it.  Lack of evidence (EAI_AGAIN) is
not strictly evidence for the lack of a name (EAI_NONAME), but both mean that no host translation is
available.  In the former, it is UnknowableHostException, the latter is a solid UnknownHostException.
Unlike an I/O read() call mumble_AGAIN, we probably do not want to loop trying again.

Now that we seem to have identified the underlying condition, is there a better way to handle 
the these Exceptions?


I have to say it or it will stick with me all day: There is something about "foo". Would make
a good title for a movie.

**Comment by LeeTibbert** [comment]
The -5 error code is very helpful. I am assuming that it is the (gai/eai) error code returned
by getaddrinfo().  

Ubuntu Linux give s
```
# ifdef __USE_GNU
#  define EAI_NODATA      -5    /* No address associated with NAME.  */
```
https://lists.freebsd.org/pipermail/freebsd-ports/2003-October/005757.html
states that EAI_NODATA was removed in RFC3493 " Basic Socket Interface Extensions for IPv6",
February 2003. I doubt it has been re-introduced.

I will check if it is defined on macOS (netdb.c compilation issues) and on Windows.

Given that we have encountered an example of EAI_NODATA in the wild, seems like a stronger
argument for InetAddress.scala to use UnknownHostException here (and leave EAI_AGAIN) 
as it is.

**Comment by armanbilge** [comment]
Lee, thank as always for the investigation and detailed write-up :) much appreciated. If you believe it is worthwhile to make this change then I like your proposal. I am also open to conceding that not every exception can behave the same across Native and JVM, and this is just one of those edge cases.

> I do have some lingering disquiet in that the text "Caused by: java.io.IOException: Temporary failure in name resolution"
looks like EAI_AGAIN and not the (-5, EAI_NODATA).

This is a good point. Let me verify that indeed this is the error message for that number.

**Comment by LeeTibbert** [comment]
I think we are making or have made progress.     I will implement 
an extended UnknownHostException test & post it.  Then
you can see if it makes CI happy.  Sound like a plan?

I wish I understood where the problem with "foo" is coming from
on your system.  I guess somethings are just destined to remain
mysteries; humbles one.


 Probably as single routine, called from two places.   The LinkTimeInfo
stuff is complicated & ugly enough that I do not want to do it in 2 places.
Usually, when I code, I create a method the second time I use something
and certainly the third. Looks like I took the easy-at-the-time route
here and am now ruing it.

PS:  The reason that I asked about VMs is that sometimes the network
        on a VM is only minimal and the bind/nameserver may be either
        minimal or from an `/etc/hosts` or `resolv.conf`.

        Something else appears to be going on here.

**Comment by ekrich** [comment]
Prior to this pull, we got the same thing as JVM except we didn't have the `<host>:` prefix. In this case `foo:`. I only tried `foo` but I could try those others on that version if it could be helpful. https://github.com/scala-native/scala-native/pull/2984

**Comment by LeeTibbert** [comment]
Eric, thank you for the data and your time.   SN < 0.4.8 reported _every_ getaddrinfo failure as 
UnknownHostException. 0.4.8 tried to do the right thing and report at a finer granularity.
The hope was that this would aid debugging (by giving a better idea of the underlying fault).

I think at this point a way to proceed that preserves everybody's time, an exceedingly 
scarce resource, is for me to submit a trial PR and see if it solves the reported problem.
I suspect it will add robustness in any case (by covering the well obsolete EAI_NODATA case 
where it makes sense).  We will just have to plug it into Arman's CI and see what happens.

There is a fix in the pipeline for the missing hostname, but that glitch still complicates the
discussion.

I have a good idea of what to do. Just want to do it when I am rested, so that I do not
introduce more bugs.

**Comment by ekrich** [comment]
Not to split hairs but I think just doing what the JVM does is fine - In my test in #2984 it shows the stacktrace so I assume you could figure out the code path from that. The more tests we have against the JVM the better so maybe just throwing that same old exception and wording is fine - I was actually surprised the error was the same. It is an indication that you are calling the same error to string routine as the JVM.

**Comment by armanbilge** [comment]
> 0.4.8 tried to do the right thing and report at a finer granularity.
The hope was that this would aid debugging (by giving a better idea of the underlying fault).

Yes, and I think this is definitely the right think to do. It's very possible that the JVM is doing coarse-grained error reporting here, and tucking various issues under the guise of "unknown host". Admittedly I am very biased towards matching empiricalJVM behavior and in retrospect too much: bug-for-bug is not really what we want to aim for.

That is to say: I really appreciate everyone's time investigating this issue. Lee, I trust your judgement if there is legitimate room for improvement here. Or if this is just a crusade for matching the JVM to the point where it's actually detrimental to getting precise, helpful error messages, then maybe we can let this one go.

**Comment by ekrich** [comment]
That is fine. Some of the code I have written for Scala Native and Scala.js is arguably better that the JVM so we could definitely put this into that category. Plus, if we use the errors from C, people can search that online for info as well.

**Comment by LeeTibbert** [comment]
@armanbilge 

If/when PR #3007 passes CI could you try it in your environment if/when you have a chance?

getByName("foo") should now throw an UnknownHostException of the form "foo: <reason>".
What I am interested in is if the <reason> is " Name or service not known"
or something else, such as a message about a temporary failure.

@arman, @ekrich 
I have attempted to consolidate the discussion in this Issue so that any Exception
intended to cross the Java API is an UnknownHostException where the host is printed
if it can be determined and a <reason> is given, not just the fixed text "Name or service not known".
This should preserve the kind of Exception yet allow some hints of causes of failures (such as EFAIL text).

I am also silently converting the well obsolete but not yet gone EAI_NODATA to EAI_NONAME, so 
that the same text message is shown for both. Reduces confusion and wastes to our time.

Messages such as "unsupported address family" are caused by developers and should never get
to users of javalib. These remain IOExceptions, so they can convey detailed information and also
alert/break test Suites.

Thank you for the discussion, suggestions, & improvements.
