### ISSUE TITLE
What steps are needed in order for SN to provide non-raw javadoc for javalib? 

### ISSUE THREAD

**Issue by LeeTibbert** [scala-native/scala-native#3030]
Ekrich has been advocating for SN to publish javadoc for a while now.    Some recent layout changes to
the ReadTheDocs javalib.rst brought the issue into focus.   

This Issue is a placeholder for a discussion about providing javadoc.  It is terse because the White Rabbit
is looking at their pocket watch and pulling on my cuffs.

I know that I for one need a brief tutorial/walk_thru about,  at least:
- [ ]  What a javadoc comment looks like.  Same as ScalaDoc?  URL?
- [ ] How to generate javadoc

From a quick look at the SN javadoc URL Eric sent, it looks like we need to
add "SN implementation detail" to several *Ops classes. I suspect that a lot
of the Unix*Impl and Windows*Impl classes will need the same. That is,
everything which is not official Java API.

Looks like plenty of work items to peck away at whilst waiting for CI runs
to complete.

Eric, as mentioned, this is a placeholder.  You are the Champion here and have
some knowledge, so  please steer the discussion.

**Comment by LeeTibbert** [comment]
If I may try to capture the essence of the suggestion, Arman suggested that such javadoc not be
public but  Contributor only (last words are my characterization), and that people on the landing
page be directed to the official Java API.
> However, we should not publish and promote documentation for these unofficial APIs.

People using unofficial APIs in the wild and becoming dependent on them is __always__ a 
source of development pain & suffering.

This is an example of why the javadoc discussion needs some hammering out & definition.

**Comment by WojciechMazur** [comment]
One issue I've stumpled upon is problem with handling unicode characters in `java.lang.Character`  https://github.dev/scala-native/scala-native/blob/5b38bd8dca71f127f7a69789aaa78956fbdf55cb/javalib/src/main/scala/java/lang/Character.scala#L227-L230 

By default we're using a UTF-8 encoding of sources. However, Scala2 scaladoc when generating `api/index.js` would try to fill  some of it's field with unicode value. This operation would fail and would throw MalformedInputException. 
From what I've seen mitigating this issue should be enough to finish generating scaladoc for javalib.  One workaround is adding explicit result type for these fields. Probably scaladoc/compiler would infer their type to singleton literal type instead of widening them to scala.Char.
After fixing that there would be ~20 warnings that probably should be addressed.

**Comment by ekrich** [comment]
I ran into the same problems in my branch - I can push it so you can compare if you like.

**Comment by ekrich** [comment]
I pushed my branch - sure you already have what i have so far. https://github.com/scala-native/scala-native/pull/3035

**Comment by LeeTibbert** [comment]
I believe this issue has faded into the mists of time.
