### ISSUE TITLE
Opaque types disappear during reachability phase

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#3063]
See https://github.com/keynmol/microuilib-scala-native-demo/blob/main/src/main/scala/microuilib.scala#L9

Compilation fails with `Not found Top(microuilib.types$.mu_Font) Undefined definitions found in reachability`

**Comment by JD557** [comment]
I'm still experiencing this issue on https://github.com/keynmol/microuilib-scala-native-demo

However, now I can compile and run the program just fine *once*. Then if I edit some file and try to run it again, I get the `Not found Top(microuilib.types$.mu_Font) Undefined definitions found in reachability` error.

Running `clean` is enough to being able to compile it again.

**Comment by WojciechMazur** [comment]
Suprisingly the issue now only present after subsequent compilation after modifying the sources, but probably it can be present in any multi-stage compilation / when using external dependencies

I've managed to find the reason why it fails: it seems like inner objects accessors/fields are not limited: 
In Bytecode
```java
public final class microuilib.aliases$ implements java.io.Serializable {
  public static final microuilib.aliases$mu_Font$ mu_Font;
  public static final microuilib.aliases$mu_Id$ mu_Id;
  public static final microuilib.aliases$mu_Real$ mu_Real;
  public static final microuilib.aliases$ MODULE$;
  private microuilib.aliases$();
  public static {};
  private java.lang.Object writeReplace();
}
```

In NIR:
```LLVM-IR
decl @"M19microuilib.aliases$D12writeReplaceL16java.lang.ObjectEPT19microuilib.aliases$" : (@"T19microuilib.aliases$") => @"T16java.lang.Object"
decl @"M19microuilib.aliases$RE" : (@"T19microuilib.aliases$") => unit
module @"T19microuilib.aliases$" : @"T16java.lang.Object"
```

Probably its due to the fact that we assumed that inner objects within object can be statically reachable and defined as pseudo-global variable.
