### ISSUE TITLE
Environment setup docs need updating 

### ISSUE THREAD

**Issue by faveoled** [scala-native/scala-native#3098]
I tried a simple g8 template on Ubuntu 22.04 and got the error:
```
[error] /home/user/Dev/Scala/scala-native/target/scala-3.1.3/native/native-code-nativelib_native0.4_3-0.4.5-0/scala-native/eh.cpp:1:10: fatal error: 'exception' file not found
[error] #include <exception>
[error] /home/user/Dev/Scala/scala-native/target/scala-3.1.3/native/native-code-nativelib_native0.4_3-0.4.5-0/scala-native/platform/posix/process_monitor.cpp:5:10: fatal error: 'memory' file not found
[error] #include <memory>
[error]          ^~~~~~~~
[error]          ^~~~~~~~~~~
[error] 1 error generated.
[error] 1 error generated.
[error] Failed to compile /home/user/Dev/Scala/scala-native/target/scala-3.1.3/native/native-code-nativelib_native0.4_3-0.4.5-0/scala-native/eh.cpp
[error] (Compile / nativeLink) Failed to compile /home/user/Dev/Scala/scala-native/target/scala-3.1.3/native/native-code-nativelib_native0.4_3-0.4.5-0/scala-native/eh.cpp
[error] Total time: 12 s, completed Jan 20, 2023, 1:56:38 PM
```
I solved it using the following command:
```
sudo apt install libstdc++-12-dev
``` 
I think the doc should be updated with an additional dependency line

**Comment by LeeTibbert** [comment]
@faveoled 

Thank you for taking the time to report this difficulty and posting the solution you found.
Your first entry! I am sorry that you encountered this defect.  

May I ask a few questions to help me & others study this report?  I do not want the process to 
feel like an interrogation.  

What hardware architecture (Amd64, aka X86_64, or Arm64)?  

Which Scala Native version?  (It appears to be an early 4.n version)

Which .g8 template (if you feel comfortable posting that name)?

Again, thank you.

____________________________________________________________________________________________

I think the next step for any devo looking at this is to spin up a fresh VM, install a vanilla 
out-of-the-box Ubuntu 20.04  (because it is a long term support version) from ISO, and 
see what steps are necessary to successfully build either your .g8 or, especially, the 
Scala Native provided .g8.

A good use of time whilst waiting for CI on other PRs to complete.

I hope to update the SN .g8 once Scala 3.2.2 is released.

**Comment by faveoled** [comment]
It was from the command on amd64.
```
sbt new scala-native/scala-native.g8
```
I tried to reproduce it with Docker with no success. So there's actually no obvious defect in docs.
For those who are interested:
[Dockerfile.zip](https://github.com/scala-native/scala-native/files/10478548/Dockerfile.zip). Running via command:
```
docker build -t "scalanative:Dockerfile" .
```

**Comment by philwalk** [comment]
I have been running into this problem in a Windows 10 WSL ubuntu environment:
`Linux d5 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

The following fixed it, although I didn't verify which environment variables were actually required.

```
sudo apt install libstdc++-dev

export CLANG_FORMAT_PATH=/usr/lib/llvm-10/bin/clang-format
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/llvm-10
export CPPFLAGS=-I/usr/include/c++/10
```

The same problem in Linux Mint Ubuntu was fixed with environment setup:

`Linux mint202 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

I got past it with this (although see the subsequent problem below):

```
sudo apt install libstdc++-dev

export CLANG_FORMAT_PATH=/usr/lib/llvm-14/bin/clang-format
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/llvm-14
export CPPFLAGS=-I/usr/include/c++/12
```
