### ISSUE TITLE
Cast exception in ServerSocket on accept().

### ISSUE THREAD

**Issue by devlaam** [scala-native/scala-native#3131]
When i create a server with the following code (Scala 3.2.1, Native 0.4.10)
```scala
val serverSocket = new ServerSocket(8180,10,InetAddress.getLoopbackAddress())
try
  val socket = serverSocket.accept()
  println(s"Remote port = ${socket.getPort()}")
  socket.close()
catch
  case e: Exception => println(e.getMessage)
serverSocket.close()
```
I get an the following exception on an accepted connection:
```log
scala.scalanative.unsafe.CStruct1 cannot be cast to scala.scalanative.unsafe.Ptr
```
Setting a timeout on the serverSocket does not change this behaviour.

**Comment by WojciechMazur** [comment]
Thank you for reporting this issue and a great minimization, we'll try to fix it in the next release

**Comment by LeeTibbert** [comment]
@devlaam  

Sorry that you encountered this defect and thank you for reporting it.
No surprise to you, I have reproduced it using Scala Native 0.5.0-today.

I checked that there is a test for `accept()` in the Scala Native test ensemble
and there is one.  This must tickle another path.   May I have your 
permission to add code based on your reproducer to the SN test ensemble,
with recognition of you as original author?  

I will try to isolate the defect over the weekend.

**Comment by LeeTibbert** [comment]
@devlaam 

I have located the two defects. One on the IPv4 path, and its mate on the IPv6 path. Ouch! This one is nasty.

Looks like I introduced the defect whilst implementing IPv6 support.  Guess I do not get a prize this month :-(

I have a proof-of-concept fix for both paths and the fixes pass close relatives of your reproducer.

Now comes the hard part. First figuring out why the existing tests did not catch this.  

Then creating new tests to try to detect it before it rears its head again.  Those are going to be difficult.

I may PR the fixes so that they are available while I figure out how to automate tests.  That
would make them available sooner.

**Comment by devlaam** [comment]
@LeeTibbert 
> May I have your permission to add code based on your reproducer to the SN test ensemble, with recognition of you as original author?

Of course, i am happy to help and pleasantly surprised it is taken on so quickly. Thank you for that!

**Comment by LeeTibbert** [comment]
For other reasons, I had to trace the history of changes in the affected file.
Looks like the bug reported in this Issue has existed for more than 3.5 years.

**Comment by devlaam** [comment]
This seems a long time but is actually not that surprising; `.accept()` on the server socket block, which causes some problems in a single threaded environment. So i suspect application builders tend to steer around this. However, since the nio channels are not yet implemented in Native there are not much alternatives. Actors can save the day here, for it renders the actual threading model irrelevant, and iff you program the right way, you can still use `.accept()`. This might explain why i encountered the bug first, as I am working on an cross-platform actor system. As soon as multithreading becomes available (out of the box), others will quickly spot it as well i suppose.
