### ISSUE TITLE
Missing `Files.readString`

### ISSUE THREAD

**Issue by faveoled** [scala-native/scala-native#3135]
```scala
import java.nio.file.{Files, Paths}

Files.readString(Paths.get("file.txt"))
```
This wails with (truncated)
```
Found a call to not defined static method Member(Top(java.nio.file.Files),D10readStringL18java.nio.file.PathL16java.lang.StringEo). Static methods are generated since Scala Native 0.4.3, report this bug in the Scala Native issues. 
````
UPD: Solved using the following:
```scala
def readString(path: Path): String = {
  String(Files.readAllBytes(path), StandardCharsets.UTF_8)
}
```

**Comment by LeeTibbert** [comment]
@faveoled 

Thank you for reporting this defect and the  suggested workaround/implementation and 
sorry that you encountered it.

I have a fix to this in testing as part of a PR for the complementary `writeString()` issues 
reported in PR #3071.   Looks like you tripped over this defect before I was able to hid
it under the covers. 


A note for other people using the posted workaround.  An implementation suitable
to current needs is far better than theoretical purity and empty hands. That said and
recognized, `readAllBytes()` is documented by Java:
```
Note that this method is intended for simple cases where it is convenient to read all bytes into a byte array. It is not intended for reading in large files.
```

Where "large" is defined as "large enough to break `readAllBytes`()"   

I intend for the  SN javalib `readString()`  family to be able to read larger
files.  I will have to compare implementations to ensure that.

At some point, any implementation will be limited to files (well) less than
the maximum size for a String. 

At some point a streaming algorithm rather than a "read all at once"
approach makes sense.   "readAll" is good for "small" strings, where
"small" is defined as "not large enough to break readAll").

I am also implementing the Java 11 `transferTo()` method.

I hope these prove useful to you and others when they are released.

**Comment by faveoled** [comment]
@LeeTibbert 
This might be useful for `transferTo`:
https://github.com/gzm0/scala-js/commit/4080f9889ba2b258138d4109a815bbba25767627

**Comment by LeeTibbert** [comment]
@faveoled Thank you for the reference.  I am always happy to port Scala.js code. Existing Tests especially
save time.    I will review my code and see if it makes sense to use the Scala.js code.  I may well use the
same buffer size (4096).  I waived back and forth on the size for that one.

**Comment by LeeTibbert** [comment]
Just for my edification.  If you do not mind, which Java version are you using?  How large are the 
files you intend to read?   Thanks?

**Comment by faveoled** [comment]
Java 11, files a couple of KB size (actually called from test code)

**Comment by faveoled** [comment]
I tried to use `Source` but found its interface too inconvenient to use

**Comment by LeeTibbert** [comment]
| Java 11, files a couple of KB size (actually called from test code)

Thank you.  The Java 11 part helps orient me as to what is actually being used
by real people.   

Files of a couple KB should be fine with `readAllBytes`. I believe readAllBytes()
assumes the files are UTF-8.  If yes, and you are willing, are they 1-byte, 2-byte, 3-byte,
or 4-byte characters?    

I ask to help ground my testing code.  I always knew there was some use in the Universe/Multi-verse
for Ogham script.

**Comment by LeeTibbert** [comment]
The Scala.js reference paid off.  That is `InputStream.transferTo`.  I did not know that existed.
I am implementing `Reader.transferTo()` which has the same logic but in a different inheritance
tree.  I will have to see what Scala.js does with it (can it somehow call InputStream code).

**Comment by faveoled** [comment]
I guess the files are mostly 1-byte but have some symbols outside of ASCII (>1 byte). I was doing string equals comparisons so line separators are important. (This might be the reason why my `Source` code was failing - it was using line iteration)
