### ISSUE TITLE
Get rid of unneccessary `@stub` annotations

### ISSUE THREAD

**Issue by WojciechMazur** [scala-native/scala-native#3214]
`@stub` is harmful to the native ecosystem, maybe at some point in the past it was useful, but right now it makes no sense to use. 
Option `withLinkStubs(true)` is typically unnecessarily enabled in most of the projects, even when it's not required. If for some reason, the stub annotated methods are used, their usage can lead to unexpected runtime failures, which could have been detected at compile (link) time. 
With current support for link-time properties, it is also easy to eliminate code flows that for some reason could not be implemented of linked otherwise. 

The only justified use case for `@stub` is the definition of abstract members which should never have been used. In such case access to stub would fail to link preventing us from a runtime error. 
https://github.com/scala-native/scala-native/blob/e6fdf3ef3ce0763f0d60082438f6fe1af86e0872/javalib/src/main/scala/java/lang/process/PipeIO.scala#L122-L124

The change should include the removal of stub methods/classes annotated with `@stub`  annotations in the code (e.g. `java.lang.reflect.Field.get`).

**Comment by ekrich** [comment]
Just to confirm, you are not saying `withLinkStubs(true) is going away but that the `@stub` will be removed?

**Comment by WojciechMazur** [comment]
Currently, it's the most important to remove abuses for that annotation. Later we might think if it should remain for the usage like in the snippet above. If we remove `@stub` we can deprecate `withLinkStubs` and make it a no-op. It's only used for disabled stubs behavior.

**Comment by ekrich** [comment]
I see, the default would be true like it is in Scala.js?

I think as long as we can still use `???`, I think that is fine. I need to have `true` set to link in `ekrich/sconfig` so I am thinking the default is `false`. https://github.com/scala-native/scala-native/blob/main/tools/src/main/scala/scala/scalanative/build/NativeConfig.scala#L208

Do you plan to backport to the 0.4.x series? Eventhough is might be breaking, it might be a gateway.

**Comment by WojciechMazur** [comment]
As far as I know, Scala.js has no stubs. No, it should default to `false` to protect from the usage of nonported methods. Otherwise it would always just fail at runtime. You should enable linking stubs only when you explicitly need it

**Comment by ekrich** [comment]
If you take a look at the build here in this project you can see that I have no options for Scala.js but add the `withLinkStubs(true)` for the Native options. https://github.com/ekrich/sconfig

If you look in this area, you can see the shenanigans I have to do for Scala.js. I can't use implicits because of the way the compiler works with the Java library (JVM) linking so I have to use direct delegation.
https://github.com/ekrich/sconfig/tree/main/sconfig/js/src/main/scala/java

I do almost the same thing for Scala Native but some of the "stubs" with `???` are currently in Scala Native but I'll
have to add them to my project post `0.5.0`. They are shared with JVM because the stubs currently are in Scala Native for `URL` and `URLConnection` and and `Thread` methods.
https://github.com/ekrich/sconfig/tree/main/sconfig/jvm-native/src/main/scala

My understanding is that these are in the normal path of code execution so the linker needs them due to reachability but as long as the code does not call a `stub` method, everything is fine. If the code calls any thing that forces a transit to a `???` then I think you get the standard `scala.NotImplementedError: an implementation is missing` or some sort of linking error. The fact that it works on Scala.js with out any settings leads me to believe that as long as the Scala.js linker does not transit into a `???` it is fine which is the same as Scala Native with link stubs set to true.

**Comment by tanishiking** [comment]
To confirm @WojciechMazur's original idea:

"Removing stub" means removing methods that have the @stub annotation. For example, in the [ClassLoader](https://github.com/scala-native/scala-native/blob/582022549183c062db3ff25e89796e39e8b5ec7d/javalib/src/main/scala/java/lang/ClassLoader.scala) class, it would look like this:

```diff
class ClassLoader protected (parent: ClassLoader) {
  def this() = this(null)
-   @stub
-   def loadClass(name: String): Class[_] = ???
-   @stub
-   def getParent(): ClassLoader = ???
-   @stub
-   def getResourceAsStream(name: String): java.io.InputStream = ???
-   @stub
-   def getResources(name: String): java.util.Enumeration[_] = ???
}
```

As a result, Scala code that compiles with Scala Native, which previously referenced stubbed methods such as `ClassLoader#getResources`, will no longer compile. Instead, it will produce an error stating something like "getResource is not a member of object java.lang.ClassLoader."

> The only justified use case for @stub is the definition of abstract members which should never have been used. In such case access to stub would fail to link preventing us from a runtime error.

The `@stub` annotation remains for "abstract members which should never have been used," as seen in [this example](https://github.com/scala-native/scala-native/blob/e6fdf3ef3ce0763f0d60082438f6fe1af86e0872/javalib/src/main/scala/java/lang/process/PipeIO.scala#L122-L124), where it is used for `override def process: GenericProcess = ???`.
However, Scala Native will fail with a linking error if the code has access to the `@stub` method because of the following change to [Reach.scala](https://github.com/scala-native/scala-native/blob/582022549183c062db3ff25e89796e39e8b5ec7d/tools/src/main/scala/scala/scalanative/linker/Reach.scala#L201-L202)


```diff
-     if (defn.attrs.isStub && !config.linkStubs) {
+     if (defn.attrs.isStub) {
        reachUnavailable(name)
```

This is equivalent to setting `config.linkStubs` to always `false`.

With this change, previously runtime failed code that accesses to `@stub` methods can be detected at compile time.

---

On the other hand, @ekrich 's concern is, once the above change is introduced into scala-native, (scala-native projects that uses) `ekrich/sconfig` won't compile even with [`nativeLinkStubs := true`](https://github.com/ekrich/sconfig/blob/main/docs/SCALA-NATIVE.md) out of the box.
And `sconfig` (and all projects that cross-compiles to scala-native that has an access to the `@stub`ed methods) requires these kinds of workaround. (thanks @ekrich for sharing the idea!)

>  I'll have to add them to my project post 0.5.0

https://github.com/ekrich/sconfig/blob/725937516d731b8c0e6daef3263605a2ec0f417d/sconfig/shared/src/main/scala/UriLike.scala#L5-L10

because scala-js doesn't have a `URI#toURL` method https://github.com/scala-js/scala-js/blob/e0afd0f096c6b096ce7ad17f46c07142ac80c7ef/javalib/src/main/scala/java/net/URI.scala#L374-L375

(Other examples can be found here https://github.com/search?q=repo%3Aekrich%2Fsconfig%20%22in%20Scala.js%22&type=code)

---

So, where should we go?

- (1) Remove `@stub` methods as a 0.5.0, is backport to 0.4.x important?
- (2) Or isn't this acceptable change, and we should keep the current behavior?

**Comment by ekrich** [comment]
With Scala.js you can link to an unimplemented method `def foo(): String = ???` just like in Scala in general. As long as it isn't called during runtime, all is fine. Scala Native should work the same as Scala.js.

For `0.5.0` we should remove all the "NotImplemented" code that we do not plan to implement and remove all the `@stub` annotations and remove the `config.linkStubs` option. All of this stuff is just too confusing.

I think `0.4.0` should just remain the same. I don't know if anyone cares to but there is a https://github.com/scala-native/scala-native-java-stubs project to help people make the adjustment if there code is reliant on the older code with unimplemented or partially implemented code that we don't plan on maintaining.

I did some work on `sconfig` and things seem to work fine with `0.5.0`. I opted to add the "NotImplemented" code to the project so things would link. I am not sure if the `withLinkStubs(true)` is needed but I am hoping the answer is **no**.

**Comment by ekrich** [comment]
After publishing `scala-native`, `scala-collection-compat`, and `sjavatime` I am getting a problem linking `sconfig`.
See https://gist.github.com/ekrich/b4d2c0e0edfc7b78eb4b5c263b92c4c8

**Comment by tanishiking** [comment]
> After publishing scala-native, scala-collection-compat, and sjavatime I am getting a problem linking sconfig.

I hit the same problem, and in case sbt clean fixes the issue.

**Comment by ekrich** [comment]
I think there must be a bug because the compiler shouldn't fail. I tried clean and got the following results.

- ++2.13.11; clean; sconfigNative / test `passed`
- ++2.12.18; clean; sconfigNative / test `failed`
- ++3.3.0; clean; sconfigNative / test `failed`

**Comment by tanishiking** [comment]
The remaining `@stub` usages are the following, which are the "justified use case for @stub is the definition of abstract members which should never have been used." mentioned by @WojciechMazur so let's close this issue as completed. (Please re-open it if I missed something :) )

https://github.com/scala-native/scala-native/issues/3214#issue-1619276944

https://github.com/scala-native/scala-native/blob/49df47e055e0d35f60c42e0dd2d5f390ff036f0b/javalib/src/main/scala/java/lang/process/PipeIO.scala#L122-L123

https://github.com/scala-native/scala-native/blob/49df47e055e0d35f60c42e0dd2d5f390ff036f0b/javalib/src/main/scala/scala/scalanative/nio/fs/windows/WindowsAclFileAttributeView.scala#L71-L72

https://github.com/scala-native/scala-native/blob/49df47e055e0d35f60c42e0dd2d5f390ff036f0b/javalib/src/main/scala/scala/scalanative/nio/fs/windows/WindowsFileSystem.scala#L30-L31

---

I remember @ekrich has an idea to get rid of `@stub` from scala-native, and just warns for the unimplemented method
https://github.com/scala-native/scala-native/pull/3348#issuecomment-1611628326
but maybe we want to open another issue for that and work on it after 0.5.0?

**Comment by WojciechMazur** [comment]
I think the current status is good enough. This way we both get linktime-safety that we won't use a method which is not implemented and at the same time we can actually not fight with the compiler, simply becouse we cannot implement given method yet. In each of the cases presented in previous comment usage of `@stub` is completely valid.
