### ISSUE TITLE
primitive classtag equality broken in 2.12

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#3244]
```scala
//> using platform "native"

import scala.reflect.ClassTag

object Main {
  def main(args: Array[String]): Unit = {
    println(implicitly[ClassTag[Byte]] == ClassTag.Byte)
  }
}
```

```
$ scala-cli test.scala -S 2.12
false
$ scala-cli test.scala -S 2.13
true
```

**Comment by armanbilge** [comment]
On second thought: I'm not sure if classtag equality is well-defined anyway.

**Comment by WojciechMazur** [comment]
It's due to overrides done in Scala standard library. Both ClassTag and Manifest are reimplemented as `def` instead of `val`, however in 2.13 they eventually refer to the instance defined in ManifestFactory as an object. In Scala 2.12 they're always created ad hoc, so every call to ClassTag.Byte creates a new instance of it. It should be fixed.

**Comment by armanbilge** [comment]
Thanks, yes I noticed the difference in the overrides. I added a test in 893fe449e80e6598da5c0de482bbace810d6f674 but now I don't think comparing classtags makes sense anyway, it's probably not safe to rely on their equality in general and instead to use `.runtimeClass` for comparison.
