### ISSUE TITLE
Proposal: `Array[Byte]`-like class that is conservatively traced

### ISSUE THREAD

**Issue by armanbilge** [scala-native/scala-native#3312]
More specifically, I propose a new class with the following features.

1. It should be a Scala object, that is GC-managed.
2. It should expose an unsafe `Ptr[Byte]` interface.
3. The GC should trace its memory contents conservatively.

One possible implementation could be similar to the existing array implementations except that the GC would be special-cased to trace the contents conservatively.

### Motivation

When implementing delimited continuations or green threads / fibers it is desirable to have stack-like memory on the heap. By "stack-like" I mean a contiguous block of heterogeneous memory, that may consist of pointers to GC-managed objects, as well as primitives and pointers to manually managed allocations.

Further reading:
- https://github.com/scala-native/scala-native/pull/3286
- https://github.com/typelevel/cats-effect/issues/3661

### Alternatives

https://github.com/scala-native/scala-native/pull/3039 added support for custom GC roots, which could possibly be used here. However it has some limitations:
1. frequently adding / removing roots will have heavy contention and bad performance in multi-threaded runtimes
2. it forces the green thread / fiber to be manually managed, since the root will have to be manually de-registered

Another possibility might be to hijack an `Array[Object]` for this purpose. However that is not currently using the `Marker_markConservative` routine so I am not sure if this will always work correctly.

https://github.com/scala-native/scala-native/blob/fd63394080ef2a545533ebb0445b82ea3f99213a/nativelib/src/main/resources/scala-native/gc/immix/Marker.c#L85-L93

**Comment by armanbilge** [comment]
Another feature I'd like to add to the list:

4. It should be dynamically "resizable". Although the size of the entire allocation must be fixed (like an array), the length that is currently traced by GC can be dynamic. 

    Motivation: memory used for stack may need to be rapidly unwound i.e. our position in the stack decreases. However, the now unused region of the allocation may still hold references to objects that we no longer need. We could `null` these references out as we unwind, but it would be much more efficient if we could simply indicate that the GC should just stop tracing those unused regions.

**Comment by wks** [comment]
If the `Array[Byte]` is a GC-managed object, but its content is conservatively scanned, then the *children* of this `Array[Byte]` must not be moved.

Suppose we have object A, B and C.  A is an `Array[Byte]` which is conservatively scanned.  B and C are other objects.  A contains a conservative pointer that points to C;  B contains a (exact) pointer field that points to C, too.  If A is GC-managed, and A is not necessarily a root, then during a GC, B may be visited by the GC before A is visited by the GC.  Then the edge `B -> C` will be traced by the GC first.  If the GC is an evacuating moving GC (such as SemiSpace or Immix), then `C` will be moved while tracing the edge `B -> C`, and the field in B will updated to point to the new location of B.  Suppose then GC visits A.  It scans A conservatively, and finds a pointer to C, too, and find C has been moved.  But the GC cannot update the field of A because it is conservative.  But C has been moved!  Now A contains a conservative field that points to the from-space copy of C, which is wrong.

I am currently working on adding evacuating GC support for CRuby (by introducing the MMTk framework).  CRuby has many types that have to pin their children, including a type `imemo:tmpbuf` which is exactly like the conservatively scanned `Array[Byte]` in this proposal.  I call such types "potential pinning parents" (PPP) because they pin their children if they are alive, but does not actually need to pin their children if they are dead.  To handle such PPPs, I register all PPPs in a list when PPP types are instantiated, or when an object becomes a PPP.  Before GC, I pin the *children* of all PPPs, preventing them from moving, but not adding them into the root set, either.  This will make sure when GC visits a live PPP, its children must not have been moved.  After GC, I unpin the *children* of live PPPs (dead PPPs are reclaimed).

Anyway, objects that contain un-update-able fields (including conservative fields) are a obstacle for implementing moving GC.  I recommend finding alternative solutions for supporting the desired features such as delimited continuation.  If the goal is saving the execution context of a suspended function, the compiler may help extracting live variables, and generating a strongly-typed Scala class (may be hidden from the programmer, but visible to the GC) that holds the variables.  In this way, the context object can be scanned exactly.

FYI:
-   https://github.com/mmtk/mmtk-core/issues/690
-   https://github.com/mmtk/mmtk-ruby/issues/18

**Comment by armanbilge** [comment]
> then the _children_ of this `Array[Byte]` must not be moved.

@wks thanks for chiming in! Currently Scala Native has a non-moving GC and as far as I know there are no plans to change this.

**Comment by 641bill** [comment]
Hi there @armanbilge ! I felt I should mention that I'm currently undertaking a master's degree project at LAMP to port MMTk to Scala Native, which includes the intention of implementing a moving GC (LXR in particular) as the end goal. Although this isn't common knowledge yet, @WojciechMazur is in the loop and has been of great assistance.
Given these upcoming developments, your proposal may be affected. I wanted to let you know so that you can take this into consideration in your design and implementation planning.

**Comment by armanbilge** [comment]
@641bill very cool, thanks for letting us know!

Last I heard on this topic was from @densh [on Discord](https://discord.com/channels/632150470000902164/635668881951686686/1027597493980119122)

> Our GC is non moving, and for interop reasons it’s likely to stay this way.

Are you planning to submit a SNIP? https://github.com/scala-native/improvement-proposals

**Comment by 641bill** [comment]
@armanbilge Thanks for letting me know the SNIPs! I probably should do it so that more people know... Things have been quite hectic on my end recently, so I'll need to figure out when I can do that.
As for Denys's comment, I think he knew this project around 1 month ago so it's indeed quite new.

**Comment by armanbilge** [comment]
@641bill yes, that would be excellent! Or at the very least, to post something about your project somewhere so that there is a place for broader discussion :)

My proposal here is actually formalizing the approach that @natsukagami (another LAMP student?) is _already_ using in https://github.com/scala-native/scala-native/pull/3286. See https://github.com/scala-native/scala-native/pull/3286#issuecomment-1576030534.
