### ISSUE TITLE
MappedByteBuffer FloatView is very slow

### ISSUE THREAD

**Issue by jrudolph** [scala-native/scala-native#3414]
As observed in https://github.com/jrudolph/llama2.scala/issues/2 at https://github.com/jrudolph/llama2.scala/commit/05bf2d4f8f89f61179ccec0ee8e9d38cb51f86cb

I cannot say for sure what the issue is, two things come to mind:
 * there's allocation happening in MappedByteBufferFloatView.get(idx)
 * in ByteArrayBits, there's no fast path to do pointer casting when the byte order matches the native one (and other preconditions like whether the architecture supports unaligned loads are valid)

Consequently, direct access to float (and more generally non-byte) values in a MappedByteBuffer (and maybe other Buffers as well?) is at least 2-5 times slower than it could be compared to direct ptr access.

**Comment by WojciechMazur** [comment]
The reason for that might be in fact excesive allocation related to usage redundant boxing of pointers. In one of local benchmarks related to reading 32MB of floats usage of intrinsics for reading bytes in `java.nio.ByteArrayBits` managed to drop load times 3x. With this change I was able to lower execution times from 3000ms (debug mode, no lto) to 1000ms (same setup) or 60ms (releaseFast mode + lto-full), which is still slower then warmed up JVM (10ms)
In the same class some additional overhead might be present due to usage of tuples. 
All Heap/Mapped buffer views might be affected by this problems.  
I'll try to continue profiling tomorrow and get more info
