### ISSUE TITLE
maxDepth not being respected in Files.walkFileTree

### ISSUE THREAD

**Issue by keynmol** [scala-native/scala-native#3417]
It's not minimised yet, but os-lib doesn't have any native overrides for this particular functionality so it's not os-lib bug.

Here's a Scala-CLI repro:

```
$ tree test-project/
test-project
├── default.properties
└── src
   ├── project.scala
   └── test.scala

$ cat test.scala
//> using dep com.lihaoyi::os-lib::0.9.1

@main def hello =
  os.walk(os.pwd / "test-project", maxDepth = 1).foreach(println)

$ scli run .
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/tmp.tniFqTLU/test-project/default.properties
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/tmp.tniFqTLU/test-project/src

$ scli run . --native
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/tmp.tniFqTLU/test-project/default.properties
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/tmp.tniFqTLU/test-project/src
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/tmp.tniFqTLU/test-project/src/test.scala
/private/var/folders/jr/4vy422xj6zs44hsn5d1_b4g40000gn/T/tmp.tniFqTLU/test-project/src/project.scala
```

**Comment by LeeTibbert** [comment]
@keynmol  

Thank you for reporting this and for the reproducer.  I used that description to replicate the reported problem
(Scala 3.3.0,  JVM 21-ea).  Sorry this defect took your time.

I am debugging Files walk internals trying to isolate the defect.

PS:   Do you know the full package name for os?  I could not find it
        after spending a few tens of minutes reading the available os docs.

       The reason that I ask is that I am trying do a proper "import mumble.os._" 
        in my design study files.  I am looking for the "mumble" part. 

       The reason that I am trying to do this is that I usually put my design studies
       in a package "package foo.study.yyy".  I had to comment out the package
       statement to get the "import os._" to work. I believe it needs to be fully qualified
       if inside a package statement.   

      Thank you. It is much easier to debug if I am back on my feed.

**Comment by armanbilge** [comment]
> PS: Do you know the full package name for os?

That is the full package name 😁 

https://github.com/com-lihaoyi/os-lib/blob/7f22bf85cd736e392774fbc23aeb20a667519e20/os/src/FileOps.scala#L7

**Comment by LeeTibbert** [comment]
@armanbilge   

Thank you for the full package name.  I'll chase the "include not seen within a personal package" if/when
I get a handle on the basic issue.

1) I got a though thrashing trying to get the reproducer running with a debug version of Scala Native.
   Round one to this Issue.  I need to try Round 2 (I am saying 2 only to save my pride and not admit
   to how many times I was thrashed) by the light of day.  I am probably going to have to create a fake
   SN 4.n package, Rats!

  2)  I found, I think, the place in the os code where it calls Files.walkMumble with 4 args.
       FilesTest.scala appears to have no corresponding test.  I think the next step is to punt
       horrifying build problems create such a Test.  It will yield bisection information in
       the short run and have value in the long run.

**Comment by LeeTibbert** [comment]
Progress:

* I have identified one point defect in Scala Native `Files.scala` and have a trial fix.
   At its simplest, the fix is a one character change: from a 0 to a 1.  Of course, ripples
   will make the final change larger than that.

   That defect is in `walkFileTree()`.  I was checking the corresponding `walk()` method
   when my hardware crashed. Rats!

   It looks like the `walkFileTree()` maxDepth defect has existed in the code for at least
   six years or more.  I was concerned that I had introduced it in my 2 or 3 month old
   work on that method.

* In the course of chasing the above and reading the JVM documentation 40 or more times 
   (slow learner; short memory) I discovered several additional related defects:

   1) Both `walkFileTree()` and `walk()` are supposed to throw an IllegalArgumentException
       when `maxDepth` is negative.

   2) Both `walkFileTree()` and `walk()` are supposed return only the supplied `start` Path argument
       when `maxDepth` is zero.

* I am continuing to work on this, as heat & hardware allow, searching for further ripples,
   especially with `walk()`. Private fixes & new Tests exist for negative, zero, positive maxDepth cases 
   of `walkFileTree` and the negative and zero cases of `walk()`.
