### ISSUE TITLE
Can't read binary-incompatible version of NIR from 'package.nir'

### ISSUE THREAD

**Issue by kyouko-taiga** [scala-native/scala-native#3488]
Encountered this error a lot while trying to run the test suite:
```
java.lang.AssertionError: assertion failed: Can't read binary-incompatible version of NIR from 'package.nir' (expected compat=5, got 6; expected revision=9, got 10).
```

Scala version: 2.12.18
Scala-native version: (v0.4.15) 2c887efb0544d4f4e214689eb0ef853c572c775b

**Comment by WojciechMazur** [comment]
It should only happen when switching between `main` and `0.4.x` branch (or one of the `0.4.x` tags). In such case the `target` directories would not be cleaned up automatically on checkout. Later thanks to the incremental compiler some of the files might not get recompiled and though not produce new NIR artifacts. 
Solution to this issue is to run `clean` in sbt and build again.

**Comment by kyouko-taiga** [comment]
Fantastic, now I got a different set of errors. That's progress!

Thanks a lot.
