### ISSUE TITLE
List linked libraries when exporting a library

### ISSUE THREAD

**Issue by JD557** [scala-native/scala-native#3572]
I was trying out [Exported methods](https://scala-native.org/en/stable/user/interop.html#exported-methods) example in Windows and one of the annoying things was: it's really hard to know what libraries I need to build the final executable.

I had to go through the Scala Native code to find that I needed to use `clang .\test.c -lmylib -ladvapi32 -luserenv -ldbghelp -o test.exe` (although I think some libraries could more stuff, like `-luser32`, `-lkernel32` and `-lws2_32`)

It would be nice if, when exporting a library, scala native printed a "This library depends on ..." message.
If this is not feasible, at least the documentation should state all `@link` annotations used by the scala native stdlib, so that one could know where to start looking.

**Comment by ekrich** [comment]
I am not sure if it is possible but I was thinking about pushing build settings into the NativeConfig eagerly so that would show but this is only using `sbt --debug` so I am not sure that would help for normal builds. When normally building C/C++ it is much more verbose but that does nothing to help the compilation speed so there is some tradeoff.
