### ISSUE TITLE
Strange issue when dereferencing a string pointer

### ISSUE THREAD

**Issue by spamegg1** [scala-native/scala-native#3668]
```scala
package bug

import scalanative.unsafe.{CQuote, Ptr}
import scalanative.libc.stdio

@main
def run: Unit =
  val str: Ptr[Byte] = c"hello"
  stdio.printf(c"dereferencing: %c", !str)
```
This should print `'h'` but it does not:
![bug](https://github.com/scala-native/scala-native/assets/4255997/bcff38ce-5fbb-453b-a460-1eaa36a29e54)

Changing it to `(!str).toByte` works:
![noBug](https://github.com/scala-native/scala-native/assets/4255997/f71594b0-7990-4957-97ff-aa5f574f05b0)

First doing `val char = !str` also works:
![noBug2](https://github.com/scala-native/scala-native/assets/4255997/b4a6476b-d3c0-469d-bea9-9595df2d8d67)

**Comment by WojciechMazur** [comment]
Thank you for reproduction. The problem seems to be caused by passing boxed `java.lang.Byte` instead of primitive Byte. It might be due to using already erased type by the compiler, because the `printf` signature uses `Any*`. We should be able to fix it by usage a corect type existing before erasure
