### ISSUE TITLE
CSignedSize missing

### ISSUE THREAD

**Issue by tindzk** [scala-native/scala-native#368]
`package.scala` defines `CSize` (`size_t`), but doesn't have any equivalent for `ssize_t`. Would it be possible to add `CSignedSize`?

**Comment by densh** [comment]
Good idea, we should do that.

**Comment by mkotsbak** [comment]
But I think this is platform specific?

**Comment by densh** [comment]
All of C types are platform specific. But it's fine given that we currently target 64-bit systems only.

**Comment by ekrich** [comment]
Related to https://github.com/scala-native/scala-native/issues/519

**Comment by LeeTibbert** [comment]
@tindzk 

I believe this has been fixed for a while.  SN 0.3.7 nativelib/src/main/scala/scala/scalanative/native/package.scala has `type CSSize = Word`. 

Trying to reduce the backlog, where I can.

**Comment by densh** [comment]
@LeeTibbert `Word` is signed (unlike `UWord`) and we can not fix it until 0.4.0 due to compatibility constraints.

**Comment by LeeTibbert** [comment]
@densh Thank you for looking at this. 

I'm confused. Your most recent comment sounds like you were talking about #519
and CSize. I understand why #519.

By my reading, this topic talks about signed CSignedSize (sic.). That got implemented
quite a while ago, by someone before me, as `type CSSize = Word`. CSSize is supposed
to be signed, Word is signed (and otherwise appropriate both 64/32), is there a mismatch?

 I believe that code shipped in 0.3.8, probably 0.3.7, and well before that. 

My apology for taking your time & energy if I am missing something, either subtle or obvious.

**Comment by LeeTibbert** [comment]
@WojciechMazur Ah, this is stone in my shoe that I had been thinking about.

You can double check or may know off the top of your head given your recent 
CSize work, but, I believe, CSignedSize has been available (and correct) for
years.

I think this can be closed even before the PR #1949 mentioned above merges.

**Comment by WojciechMazur** [comment]
`CSIgnedSize` is already available with name `CSSize`
