### ISSUE TITLE
(playdate support) delimcc.c is compiled even if Continuations isn't used

### ISSUE THREAD

**Issue by kubukoz** [scala-native/scala-native#3885]
To reproduce:

1. Add this line to delimcc.c, just to make it clear that the code is being included
```diff
diff --git a/nativelib/src/main/resources/scala-native/delimcc.c b/nativelib/src/main/resources/scala-native/delimcc.c
index bd00eb6aa..dd0597d1e 100644
--- a/nativelib/src/main/resources/scala-native/delimcc.c
+++ b/nativelib/src/main/resources/scala-native/delimcc.c
@@ -1,4 +1,6 @@
 #if defined(SCALANATIVE_COMPILE_ALWAYS) || defined(__SCALANATIVE_DELIMCC)
+
+#error "this shouldn't happen!"
 #include "delimcc.h"
 #include <stddef.h>
 #include <stdio.h>

```
2. Publish a snapshot
3. Try to link an app/library, even a "hello world" or a no-op main.

Output:

```
[info] Linking (multithreadingEnabled=true, disable if not used) (322 ms)
[info] Discovered 907 classes and 5623 methods after classloading
[info] Checking intermediate code (quick) (4 ms)
[info] Multithreading was not explicitly enabled - initial class loading has not detected any usage of system threads. Multithreading support will be disabled to improve performance.
[info] Linking (multithreadingEnabled=false) (277 ms)
[info] Discovered 774 classes and 4690 methods after classloading
[info] Checking intermediate code (quick) (2 ms)
[info] Discovered 749 classes and 3668 methods after optimization
[info] Optimizing (debug mode) (156 ms)
[info] Produced 43 LLVM IR files
[info] Generating intermediate code (413 ms)
[error] /Users/kubukoz/projects/demos/target/scala-3.3.3/native/dependencies/nativelib_native0.5_3-0/scala-native/delimcc.c:3:2: error: "this shouldn't happen!"
[error] #error "this shouldn't happen!"
[error]  ^
[error] 1 error generated.
[info] Compiling to native code (1524 ms)
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[error] stack trace is suppressed; run last Compile / nativeLink for the full output
[info] Total (2502 ms)
[error] Failed to compile /Users/kubukoz/projects/demos/target/scala-3.3.3/native/dependencies/nativelib_native0.5_3-0/scala-native/delimcc.c
[error] (Compile / nativeLink) Failed to compile /Users/kubukoz/projects/demos/target/scala-3.3.3/native/dependencies/nativelib_native0.5_3-0/scala-native/delimcc.c
```

Example app setup (requires a publish of `0.5.1-SNAPSHOT`): https://github.com/kubukoz/demos/compare/sn-continuations-repro?expand=1

**Comment by ekrich** [comment]
Won't argue that but if you look how `SCALANATIVE_COMPILE_ALWAYS` is used it is always like the following on the whole file:

```c
#if defined(SCALANATIVE_COMPILE_ALWAYS) || defined(__SCALANATIVE_POSIX_PTHREAD)
#include <pthread.h>
```
Our glue code `pthread.c` has that code. Then here on the Scala side - https://github.com/scala-native/scala-native/blob/main/posixlib/src/main/scala/scala/scalanative/posix/pthread.scala#L12-L15

**Comment by kubukoz** [comment]
right, there's a lot of this pattern in the codebase, and it seems to work correctly for my needs most of the time - the only offender I've found so far is delimcc.

**Comment by ekrich** [comment]
That is not really the one you want to use because that is for the glue code. I put a note on this issue which might be better.
https://github.com/scala-native/scala-native/issues/3877

**Comment by ekrich** [comment]
The `delimcc` is another factor - that should be a feature option somehow.

**Comment by JD557** [comment]
I was trying to reproduce this and noticed that removing `_.withBuildTarget(BuildTarget.libraryDynamic)` seems to fix the issue, so I think this might be impacting the reachability in some way.

**Comment by JD557** [comment]
From what I can tell, the problems come from:
1. When compiling a library (not an application), the reachibility analysis checks for all possible entrypoints (https://github.com/scala-native/scala-native/blob/fb627ad14d6cb09e97bad23e391e39f146706d94/tools/src/main/scala/scala/scalanative/linker/Reach.scala#L59-L66) - I assume that this is intended and working as expected.
2. One of those entrypoints in the initialization of the `Continuations` object, which immediately includes the `Continuations.Impl` (https://github.com/scala-native/scala-native/blob/fb627ad14d6cb09e97bad23e391e39f146706d94/nativelib/src/main/scala-3/scala/scalanative/runtime/Continuations.scala#L27)

Guarding this initialization under a linktime check (such as `if !isWindows`) seems to fix the issue.

I think this would make sense (considering that the feature is disabled on Windows: https://github.com/scala-native/scala-native/blob/fb627ad14d6cb09e97bad23e391e39f146706d94/nativelib/src/main/scala-3/scala/scalanative/runtime/Continuations.scala#L39C1-L39C57)

Regarding Playdate, I actually think this checks are backwards: Instead of checking which platforms don't support the feature (namely, `isWindows`), the checks should check for the platforms that are known to support continuations (`isLinux || isMac || isFreeBSD || isOpenBSD || isNetBSD`). For unknown OSs, the feature should be disabled.

WDYT?

**Comment by JD557** [comment]
For reference, here are the entrypoints captured by the reachability checks in the example library:

```
java.lang.Runtime$$Lambda$1
java.lang.Runtime$$Lambda$2
java.lang.Runtime$$Lambda$3
java.lang.SystemProperties$$$Lambda$1
java.lang.ref.WeakReferenceRegistry$$$Lambda$1
scala.scalanative.runtime.Continuations$$$Lambda$1
scala.scalanative.runtime.Continuations$$$Lambda$2
scala.scalanative.runtime.Continuations$$$Lambda$3
scala.scalanative.runtime.NativeThread$$$Lambda$1
```
