### ISSUE TITLE
"Out of heap space grow heap" error after migration to v0.5.5

### ISSUE THREAD

**Issue by plokhotnyuk** [scala-native/scala-native#4032]
Unexpected scala-test failures after [migration of jsoniter-scala to Scala Native 0.5.5](https://github.com/plokhotnyuk/jsoniter-scala/commit/1ff9cade4c893e60a6abc33b2cf8d73a2422b758) is happening [on the GitHub Actions run](https://github.com/plokhotnyuk/jsoniter-scala/actions/runs/10455418787/job/28950310174#step:8:3526) but is not reproducible on the laptop:
```text
Out of heap space grow heap
	at _SM36scala.scalanative.runtime.CharArray$D5allociL35scala.scalanative.runtime.CharArrayEO
	at _SM31java.lang.AbstractStringBuilderD7append0L16java.lang.StringuEO
	at _SM57com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpecD16$anonfun$new$509L16java.lang.StringdEPT57com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpec
	at _SM69com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpec$$Lambda$465D5applyL16java.lang.ObjectEO
	at _SM24org.scalatest.AssertionsD9interceptL15scala.Function0L22scala.reflect.ClassTagL29org.scalactic.source.PositionL16java.lang.ObjectEO
	at _SM57com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpecD13checkError$40L16java.lang.StringL16java.lang.StringL16java.lang.StringuEPT57com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpec
	at _SM69com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderSpec$$Lambda$490D5applyL16java.lang.ObjectEO
	at _SM23org.scalatest.OutcomeOfD9outcomeOfL15scala.Function0L21org.scalatest.OutcomeEO
	at _SM25org.scalatest.TransformerD5applyL16java.lang.ObjectEO
	at _SM38org.scalatest.wordspec.AnyWordSpecLikeD19invokeWithFixture$1L34org.scalatest.SuperEngine$TestLeafL18org.scalatest.ArgsL16java.lang.StringL21org.scalatest.OutcomeEPT38org.scalatest.wordspec.AnyWordSpecLike
	at _SM49org.scalatest.wordspec.AnyWordSpecLike$$Lambda$10D5applyL16java.lang.ObjectL16java.lang.ObjectEO
	at _SM25org.scalatest.SuperEngineD11runTestImplL19org.scalatest.SuiteL16java.lang.StringL18org.scalatest.ArgszL15scala.Function1L20org.scalatest.StatusEO
	at _SM49org.scalatest.wordspec.AnyWordSpecLike$$Lambda$11D5applyL16java.lang.ObjectL16java.lang.ObjectL16java.lang.ObjectEO
...
```

Now I'm looking for any mitigations except changing tests themselves.

**Comment by plokhotnyuk** [comment]
1st attempt [to replace `Mode.releaseFast` by `Mode.releaseFull`](https://github.com/plokhotnyuk/jsoniter-scala/commit/f1a57b7683123dc9c70ec09db602fa3e81644cdf) failed with [unexpected test failures](https://github.com/plokhotnyuk/jsoniter-scala/actions/runs/10456195348/job/28952940745#step:8:2180).

Could it be that working with long strings (1M characters) is getting broken in the latest release?

**Comment by WojciechMazur** [comment]
I have a feeling it might be caused by this change https://github.com/scala-native/scala-native/pull/3937/commits/bf344d6964289fa91cdfd11c02df78bbd2f747d2 that was supposed to fix the x86 builds. I'll try confirm it later, but as you pointed out it might be hard to reproduce locally. Unfortunately, this change affected the maximal possible GC heap size, so the `GC_MAXIMUM_HEAP_SIZE` env variable would not help here.

**Comment by plokhotnyuk** [comment]
2nd attempt: [turning off multi-threading](https://github.com/plokhotnyuk/jsoniter-scala/commit/dbf4044c18d0de721d6699b7fde1efe91ac80023) doesn't help,  ["Out of heap space grow heap" is returning back](https://github.com/plokhotnyuk/jsoniter-scala/actions/runs/10456609771/job/28954307187#step:8:1920)

**Comment by kyri-petrou** [comment]
Experienced the same issue in ZIO after [trying to upgrade to v0.5.5](https://github.com/zio/zio/actions/runs/10448379500/job/28928753014#step:6:1561). Works fine locally on my Mac arm64 laptop but fails on the Linux amd64 runners in CI. The OOM issue is caused [by this test suite](https://github.com/zio/zio/blob/b9c818c12badcee83ea8ff34c970e049ad9609d7/core-tests/jvm-native/src/test/scala/zio/internal/ConcurrentWeakHashSetSpecJVM.scala#L14-L53).

**Comment by WojciechMazur** [comment]
What happens here is a combination of 2 facts: 
1. The `TestAdapter` for the sbt allows the run of multiple tests in parallel, based on starting multiple instances of a native binary. We're starting up to N = available CPU threads runners that are executing the tests in parallel. We have 1 JVM (sbt) coordinator and N runners executing the tests. They're all communicating via the RPC protocol. 
2. With my change in 0.5.5 the native runner checks how much free memory it can use for GC heap (in immix/commix/none GC, Boehm GC is not affected). Previously every runner would be able to allocate memory equal to the total available RAM (default behaviour unless controlled with env variable). 

Previously, out-of-heap error would happen only when the mmap would fail - at this point typically both RAM and possibly swap would be full. 
With new behaviour all allocations made by previously started runners and other programs would reduce the pool of available memory. We would get to the hard limit set when starting the process, even though other processes might have already released the memory so technically allocation would still be possible. 

A quick workaround would be to use `set Test/parralelExecution := false` - it would tell the sbt to not run tests in parallel.

There are 2 things we can improve: 
1. Revert the recent change to Heap size limits. Default heap size was always unlimited, it should stay that way. 
2. Consider starting only 1 instance of native runner to execute tests. Starting multiple runners was a way to workaround lack of multithreading. By having multiple  single-threaded runners we could have saturated the CPU usage. However now, we can start a single runner using multiple threads. In fact, runners are already using multiple threads (at least in JUnit) so we might actually observe slower performance due to increased context switching from N-runners * M-threads-per-runner threads executing the tests.

**Comment by kyri-petrou** [comment]
@WojciechMazur in ZIO `parallelExecution` is already set to `false` 🤔

This is just speculation, but is it possible the issue is related to one of these two things:
1. Swap is not taken into account when calculating the amount of free memory
2. The native executable is run "too quickly" after we've compiled it, and clang (or other compilers) haven't released the memory by the time we read its state

**Comment by plokhotnyuk** [comment]
@WojciechMazur @kyri-petrou `Test / parallelExecution := false` doesn't help me too.

Also, I tried `.withGC(GC.boehm)` but it [doesn't compile](https://github.com/plokhotnyuk/jsoniter-scala/actions/runs/10458609807/job/28960815609#step:8:1748).

**Comment by kyri-petrou** [comment]
@plokhotnyuk _I think_ (haven't tested it) but you might need to install `libgc-dev` to be able to compile with `GC.boehm`

**Comment by kyri-petrou** [comment]
Seems that using `.withGC(GC.boehm)` solves the issue in ZIO: https://github.com/scala-native/scala-native/issues/4032

**Comment by plokhotnyuk** [comment]
@kyri-petrou Thanks for the heads up! It worked for me too.
