### ISSUE TITLE
Proposal: Replace Pure-Scala DWARF + Mach-O Parser with LLVM Libraries

### ISSUE THREAD

**Issue by tanishiking** [scala-native/scala-native#4056]
Currently, the Scala Native `runtime` uses a pure-Scala DWARF + Mach-O parser developed by @keynmol (https://github.com/indoorvivants/macho-elf-coff-parser/). It allows us to enrich stack traces with line numbers and filenames (see https://github.com/scala-native/scala-native/pull/3343 ) without needing any additional shared libraries, as the implementation is self-contained. 🎉

Alhough Mach-O and DWARF parser implementation work beautifully, I'm considering replacing the current DWARF + object file parser with LLVM libraries ([object](https://github.com/llvm/llvm-project/tree/main/llvm/include/llvm/Object) and [debuginfodwarf](https://github.com/llvm/llvm-project/tree/main/llvm/include/llvm/DebugInfo/DWARF)). for maintainability and extensibility reasons. (Thanks @kyouko-taiga for pointing out these libraries to me a while ago 😄) 

### Pros:
- We would get support for various object file format support almost for free, as LLVM already provides robust parser implementations. (Currently, the enriched stack trace is limited to Mach-O due to the lack of parsers for other formats)
- Better maintainability:
  - We could rely on tried-and-tested LLVM libraries rather than maintaining our own binary parsers.
  - Maintaining binary parsers can be challenging IMO, and this would reduce that burden.
- Potentially better performance (though that’s something we’d need to verify).
- Less code in the runtime:
  - This could lead to smaller binaries (though it may not matter in development environments) and reduced link time.

### Cons:
- The debug build binary would have a runtime dependency on the LLVM shared library.
  - This seems acceptable, as LLVM is likely available in most development environments I believe, and users are generally encouraged to disable debug builds in production (where LLVM won't be available).
- We would need to use C++ interfaces, which could be harder to debug for those unfamiliar with C++.
  - However, I personally think working with C++ is still easier than developing and maintaining binary parsers by diving deep into object file format specifications.

WDYT?
Anyway, I'd like to prototype for Mach-O and see the binary-size/link time/runtime performance :eyes:

**Comment by ekrich** [comment]
We initially started to make `tools` cross compile for native. Initially I thought that it may be good to have access to native LLVM code because as far as I can tell, this is a strategy used by Swift for a little deeper integration with LLVM tools. We could even call the compiler directly rather than through the Process API.

I do believe that if we do go this way, the native macOS tool chain needs to support it. We can't make the tool chain rely on a `brew` installed `clang` / LLVM. I still have not managed to get the native VIsual Studio 2022 tool chain to work but we should also have that goal as well. In the long term this make development on these platforms better.

**Comment by keynmol** [comment]
I feel like this would be a step in the wrong direction.

> This seems acceptable, as LLVM is likely available in most development environments I believe

This is not necessarily the case – the current toolchain in scala native does not have a strict dependency on LLVM (only Clang) or any of its tools. Linux often provides a separate clang package, MacOS only has clang pre-installed, and Windows... well it's Windows, I don't know if you can install clang separately there.

LLVM is a huge project and it's not particularly amenable to fine-grained installation. **Requiring** it for local development if you want to see debugging and exceptions would be incredibly inconvenient and will paint Scala Native exprience in a negative light in comparison to pretty much any other language other that compiles to native.

> Maintaining binary parsers can be challenging IMO, and this would reduce that burden.

I think would be only be true if we aimed to support every possible file format, which historically and presently isn't the case, as Scala Native doesn't aim to have the portability of C or Rust. We can easily support major file formats, and DWARF itself is mostly a frozen spec, with no ongoing maintenance burden. Current state of supported formats is mainly a testament to the very small number of core contributors, rather than any complexity. I did even [start on ELF](https://github.com/indoorvivants/macho-elf-coff-parser/pull/8/files) but hadn't had enough focused time to finish.

Additionally, we should be able to support something like Rust's "optimized build but with debug info" to be able to get meaningful stacktraces in production – producing binaries that depend on LLVM libraries at runtime is a bad idea for the future.

>     However, I personally think working with C++ is still easier than developing and maintaining binary parsers by diving deep into object file format specifications.

The file format specs aren't so deep, ELF is mostly trivial, and DWARF implementation is shared across platforms. More C++ (and by extension – **more C++ wrappers in C because of lack of interop**)  on the other hand _requires_ maintaining that going forward, and IMO adding more C++ code in a codebase already lacking in maintainers and contributors is not a good way forward. 

---

1. If we even entertain any possible incursion into Go's market, producing non-static binaries for something as trivial as "stdlib-only application that can throw meaningful stacktraces" is just a no-go.

2. From my experience in working with Rust and Go and professionally, self-contained toolchains which produce mostly static binaries (libstdc++ excluded) are much more pleasant to work with and distribute that work.

3. Even our current dependency on Clang doesn't need to be forever in debug builds – it would be a massive improvement if in the future we supported a fully self-contained backed emitting assembly directly in debug builds for a small number of platforms. Having all parts of the runtime be written in pure Scala would be a massive time saver in that case.

**Comment by kyouko-taiga** [comment]
Adding a dependency to LLVM will certainly make it harder to setup a developing environment. It is true that relying on `brew` for macOS is a very risky bet and I would not be surprised if similar issues exist on other operating systems. Nonetheless, using the compiler as an end user would not necessarily be more complicated. There are many compilers out there that rely on LLVM and offer pre-compiled all-in-one binaries to install and use on major systems.

One can look at Hylo's repository and CI setup for inspiration. We have put a lot of efforts into making LLVM installation as painless as possible and I think we have mostly succeeded.

Overall, my personal belief is that the more we can re-use LLVM's actual toolchain the better we can guarantee the stability of our own compiler, as long as the cost of using that toolchain doesn't create a major development and maintenance burden of course. In any case, I think an investigation is worth doing.

**Comment by tanishiking** [comment]
Thank you very much for your comments, everyone! 🙌 

**Regarding depending on LLVM tools**

As @ekrich and @keynmol pointed out, I initially assumed it would be possible to leverage system-installed LLVM, but that assumption was incorrect.
Indeed, the macOS toolchain doesn’t provide LLVM libraries (or even `llvm-config`), and considering the variations across Windows and other operating systems I'm less familiar with (and their versions), relying on system/user-installed LLVM for stable usage is definitely not feasible.

I agree with @keynmol that being able to focus on development without being burdened by LLVM setup, similar to the user experience with Go and Rust, is incredibly important.

If we want to use LLVM libraries, as @kyouko-taiga mentioned, it seems like the right direction for Scala Native would be for the `sbt-scala-native` plugin (and other build tools) to install the appropriate LLVM tools used by the compiler, depending on the platform, like `hylo` (does `hylo` install LLVM via an installer or something other than CI?) and `rustup` (AFAIK) does.

---

**Object file/DWARF parser**

Returning to the discussion about the ELF/DWARF parser, as @keynmol pointed out, we should to support "optimized builds with debug info" for runtime environments indeed. Even without an LLVM shared library, enriched backtraces should be possible.
And, to make it work, we will still need to support parsers for those binaries ourselves. (In fact, Rust has implemented their own binary parser: https://github.com/rust-lang/backtrace-rs :eyes: )

Initially, I was considering supporting a wide range of executable formats, but yeah we can focus on supporting the major file formats, and I think we can make that work.

---

I’ll close this issue for now and focus on getting @keynmol's ELF parser working. Thank you all very much for your feedback, @ekrich, @keynmol, and @kyouko-taiga!

I believe bundling LLVM with Scala Native is worth considering, but I would create a separate issue for that later.
