### ISSUE TITLE
Native test runner has the wrong current working directory

### ISSUE THREAD

**Issue by ekrich** [scala-native/scala-native#4077]
Consider the following code:

```scala
val here = new File(".").getAbsolutePath
println(s"CWD = ${here}")
```
The following is reported for a JVM cross project.
```sh
CWD = /Users/eric/workspace/sconfig/sconfig/jvm/.
```
```sh
sbt:sconfig-root> sconfigJVM/testOnly *ConfigDocumentFactoryJvmTest
[info] compiling 1 Scala source to /Users/eric/workspace/sconfig/sconfig/jvm/target/scala-2.13/test-classes ...
[info] Test org.ekrich.config.impl.ConfigDocumentFactoryJvmTest.configDocumentFileParse started
[info] Test org.ekrich.config.impl.ConfigDocumentFactoryJvmTest.configDocumentReaderParse started
[info] Test run org.ekrich.config.impl.ConfigDocumentFactoryJvmTest finished: 0 failed, 0 ignored, 2 total, 0.002s
```
The following is reported for a Native cross project.
```sh
CWD = /Users/eric/workspace/sconfig/.
```
```sh
sbt:sconfig-root> sconfigNative/testOnly *ConfigDocumentFactoryNativeTest
[info] compiling 1 Scala source to /Users/eric/workspace/sconfig/sconfig/native/target/scala-2.13/test-classes ...
...
[info] Linking native code (immix gc, none lto) (146 ms)
[info] Postprocessing (0 ms)
[info] Total (4793 ms)
[info] Starting process '/Users/eric/workspace/sconfig/sconfig/native/target/scala-2.13/sconfig-test' on port '55641'.
[info] Test org.ekrich.config.impl.ConfigDocumentFactoryNativeTest.configDocumentReaderParse started
[info] Test org.ekrich.config.impl.ConfigDocumentFactoryNativeTest.configDocumentFileParse started
[info] Test run org.ekrich.config.impl.ConfigDocumentFactoryNativeTest finished: 0 failed, 0 ignored, 2 total, 0.009s
...
```
Of course I had to hack the code a little to get the test to throw an exception to get this out. I guess we can't get the native test runner to capture `stdout`.

Expected:
```sh
CWD = /Users/eric/workspace/sconfig/sconfig/native/.
```

**Comment by WojciechMazur** [comment]
I've prepared changes that would allow passing a working directory in which runner should be executed however I don't think these should be finally included. 
The behaviour of the `CWD` on JVM is determined by the usage of `Test / fork := true / false` settings. 
If `fork := false` then CWD would be set to CWD of the project itself, typically root directory of project (sbt) 
If `fork := true` then CWD would be controlled by `(Test / forkOptions).value.workingDirectory` which by default is set to `baseDirectory` of project. 

Scala Native has always required `Test / fork := false` to be set - I'm not sure if it's still applicable or was it required only by the old testing framework (before migration to JUnit / Scala.js port in ~2020), but setting this value to `true` would result in build error. 
Because of that current behaviour seems to be in line with the JVM behaviour.  

As an alternative we could check is `fork := true` and then reuse `ForkOptions.workingDirectory` but we would never be able to guarantee that both JVM and Scala Nattve projects defined using cross project are using the same config to guarantee the same behaviour.

**Comment by ekrich** [comment]
Thank-you for looking into this. Indeed, my JVM setting has `Test / fork := true,` so that must be why. I am not sure why it is `true` but I think it is because the library uses classloaders so the tests would not share the sbt classpath??

If it is possible to make it work like the JVM so we could run in fork mode and the directory would be similar I think that would make sense. I have to do special cross build path objects to get the correct relative path to files. Build settings are here - https://github.com/ekrich/sconfig/blob/main/build.sbt#L151-L156

It looks like a runtime error - build seems ok.

```scala
[info] Total (9972 ms)
[error] `test / test` tasks in a Scala Native project require test / fork := false`.
[error] (sconfigNative / Test / loadedTestFrameworks) `test / test` tasks in a Scala Native project require test / fork := false`.
```

**Comment by WojciechMazur** [comment]
The `Test / fork := false` requirement is still needed. Otherwise, we get into problems with deserialization in the sbt testing framework. The same problem exists in Scala.js. It is caused by the fact that both Scala Native and Scala.js re-implement sbt testing interface (written in Java) which then leads to classpath issues after forking, but for some reason It works fine on the same JVM instance. It can be mitigated by producing only `.nir` with `.class` artifacts, however even if we do so the tests would fail at runtime. Forked JVM would try to use the JVM version of JUnit for some reason, instead of our Scala Native specific adapter.  

It seems like we cannot really make `Test / fork := true` work without some serious hacking. In such case, current behaviour seems to be correct - behaves the same on both JVM and Native when `Test / fork := false`

<details>

```scala
[error] Uncaught exception when running tests: java.io.InvalidClassException: sbt.testing.TaskDef; local class incompatible: stream classdesc serialVersionUID = -7417691495999416204, local class serialVersionUID = 2663134200025980977
[error] stack trace is suppressed; run last testInterface3 / Test / test for the full output
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error]         Forked test harness failed: java.net.SocketException: Connection reset
[error]         at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
[error]         at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
[error]         at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
[error]         at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
[error]         at java.base/java.net.Socket$SocketInputStream.read(Socket.java:961)
[error]         at java.base/java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2875)
[error]         at java.base/java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3202)
[error]         at java.base/java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3212)
[error]         at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1684)
[error]         at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[error]         at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[error]         at sbt.React.react(ForkTests.scala:202)
[error]         at sbt.ForkTests$Acceptor$1$.run(ForkTests.scala:133)
[error]         at java.base/java.lang.Thread.run(Thread.java:833)
```

</details>

**Comment by ekrich** [comment]
I think we could probably close this then - maybe we could add a small amount of documentation so that others could know this bump in the road. I can do that if needed.

I worked around this via https://github.com/ekrich/sconfig/blob/main/sconfig/native/src/test/scala/org/ekrich/config/impl/TestPath.scala - The JVM one is similar.

**Comment by ekrich** [comment]
@WojciechMazur Thanks again for looking into this - I will add some testing documentation to cover this.
