### ISSUE TITLE
cannot read integers from stdin using scala.io.StdIn.readInt()

### ISSUE THREAD

**Issue by aostiles** [scala-native/scala-native#543]
<img width="505" alt="screen shot 2017-03-14 at 12 03 03 pm" src="https://cloud.githubusercontent.com/assets/942957/23917930/3908185c-08ae-11e7-90ea-838497d63f5a.png">

@MasseGuillaume reproduced this bug.

**Comment by densh** [comment]
Thanks for the bug report!

**Comment by densh** [comment]
The issue is that we don't wrap stdin in https://github.com/scala-native/scala-native/blob/master/javalib/src/main/scala/java/lang/System.scala#L35, should be trivial to fix.

**Comment by Korf74** [comment]
Is an implementation of a CFileInputStream class sufficient to fix this ?

**Comment by densh** [comment]
@Korf74 Yes, that's exactly what needs to be done here.

**Comment by Korf74** [comment]
```scala
  var in: InputStream  = new CFileInputStream(stdio.stdin)
  var out: PrintStream = new PrintStream(new CFileOutputStream(stdio.stdout))
  var err: PrintStream = new PrintStream(new CFileOutputStream(stdio.stderr))

  private class CFileOutputStream(stream: Ptr[stdio.FILE])
      extends java.io.OutputStream {
    private val buf = stdlib.malloc(1)
    def write(b: Int): Unit = {
      !buf = b.toUByte.toByte
      stdio.fwrite(buf, 1, 1, stream)
    }
  }

  private class CFileInputStream(stream: Ptr[stdio.FILE])
      extends java.io.InputStream {
    private val buf = stdlib.malloc(1)
    override def read(): CInt = {
      stdio.fread(buf, 1, 1, stream)
      (!buf).toInt & 0xFF
    }
  }
```

Calls to scala.io.StdIn.readInt() using this implementation doesn't seem to work, it seems stdin reads 32 (whitespace) in loop

**Comment by fduraffourg** [comment]
I tried with `fread` but it gets on our way because of the buffering. stdin is line buffered so we encounter the case where data is available but `fread` still waits for more data before returning. I tried to change the buffering method with `setvbuf` without any success.

The solution I found is to use `read` from `unistd`:

```
  private class CFileInputStream(stream: Ptr[stdio.FILE])
      extends java.io.InputStream {

    def read(): CInt = {
      stdio.fflush(stdio.stdout)
      val buffer = stackalloc[scala.Byte](1)
      while (unistd.read(0, buffer, 1) != 1) {
        println("Nothing was read on previous iteration")
      }
      buffer(0).toInt
    }

    override def read(b: Array[scala.Byte], off: Int, len: Int): Int = {
      val bufsize = len min 256
      val buffer = stackalloc[scala.Byte](bufsize)
      val nread = unistd.read(0, buffer, bufsize)
      var pos = 0
      while (pos < nread) {
        b(pos) = buffer(pos)
        pos += 1
      }
      nread.toInt
    }
  }
}
```

This way we get data directly from the kernel as soon as it is available and we let `BufferedReader` handle the buffering stuff.

There are still stuff to take care of:
- When run from `sbt run`, stdin seams to be non blocking (or maybe not even opened) so we get into an infinite loop where each read call return immediatly without reading any data. I think using `select` or a blocking method that wait for data to be available should do the job. I'll try that.
- Things can get out of order with stdout. For example calling `println` and then reading some stuff from stdin will wait for stdin before printing
- Right now I create a buffer and then copy each byte from the buffer to the Array. Is it possible to get a Ptr from an Array to avoid this useless copy?
- Maybe look at how sbt connect stdin to the running process and makes sure everything is OK

**Comment by MasseGuillaume** [comment]
sbt run need to connect it's input

```scala
val exitCode = Process(binary +: args).run(logger, connectInput = true).exitValue
```

https://github.com/scala-native/scala-native/pull/612/files#diff-9f8176d7a89fed51f9b5c82605327b36R436
