### ISSUE TITLE
Linker breaks on importing import scala.scalanative.runtime._

### ISSUE THREAD

**Issue by jmcardon** [scala-native/scala-native#545]
Steps for reproduction:

```
import scala.scalanative.runtime._

object Main {

  def main(args: Array[String]): Unit = {
   printf("hello world!")
  }
}
```

Will break `sbt run`. The linker cannot find the main class.

Removing the import statement fixes this.

**Comment by sjrd** [comment]
Well, that's because the import implies
```scala
import scala.scalanative.runtime.Array
```
among other things, which means `Array[String]` means `scala.scalanative.runtime.Array[java.lang.String]`, and therefore the `main` method is not actually a main class.

This is not a bug in my book. It's a perfectly normal behavior. (No one should use things in `runtime` anyway. That package is for internal use by the compiler and/or std lib.)

**Comment by densh** [comment]
Indeed, this is not a bug. Moreover, you should never import things from runtime, those are dark corners of the compiler.
