### ISSUE TITLE
Default ByteBufferPool is too memory-hungry on many-core machines

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#580]
We use a pool of byte buffers to have a scratchpad for File I/O in code gen. Given that code gen is parallel it can ask up to `NUMBER_OF_CORES` buffers to be preallocated and this can easily take all of the typical JVM heap space on many core machines. 

Given that codegen is I/O-bound we need to find some sweet spot maximum number of byte buffers we allocate (my guess would be that it's somewhere from 4 to 8) and reduce code-gen parallelism to that number.

**Comment by MasseGuillaume** [comment]
https://github.com/scala-native/scala-native/blob/master/util/src/main/scala/scala/scalanative/io/ByteBufferPool.scala#L10

**Comment by jonas** [comment]
Based on my understanding, we need to first refactor CodeGen so it can generate code in one pass. Right now it first generates the body and then the prelude+dependencies. This will likely require an initial pass to determine dependencies. Once we figure that out it would be possible to write out code in 1M chunks.

The short term solution proposed in #633 is to not use the buffer pool in CodeGen and instead allocate a `ByteBuffer` for each invocation. This ensures correctness (nothing will blow up due to buffer overflow errors) with minimal penalty (the codegen phase seems to account for 10%), and would allow us to reduce the buffer size since NIR files in most cases are a lot smaller (<3MB).
