### ISSUE TITLE
stdlib.free has incorrect type

### ISSUE THREAD

**Issue by MasseGuillaume** [scala-native/scala-native#592]
It should be `void*` I'm not shure how to map this to scala's types.

`def free(ptr: Ptr[_]): Uni = extern` ?

Also I noted memory leak in https://github.com/scala-native/scala-native/blob/master/demo/native/smallpt.scala#L61

there is mallocs but no free.

**Comment by mscharley** [comment]
`void*` just means 'a pointer with no associated type' or more literally 'a pointer to nothing'. `Ptr[Nothing]` would be the most literal translation, but the most useful would be probably be `Ptr[Any]`. Really it's not a pointer to nothing, it's a pointer to anything, with any size.

**Comment by mscharley** [comment]
Also in a similar vein, the `?alloc()` functions all return `Ptr[Byte]` as well.

**Comment by MasseGuillaume** [comment]
Any have a size.

**Comment by MasseGuillaume** [comment]
Has*

**Comment by densh** [comment]
`Ptr[_]` is not a direct equivalent of `void*` in C because it means `Ptr[T forSome { type T }]` which ultimately implies that it's a pointer to GC-ed object, which does not make sense. `Ptr[_]` also breaks standard pointer arithmetic operations on `void*` as those increment the pointer value by the sizeof of  the type (which is pointer-sized and not byte-sized in this case.)

**Comment by nadavwr** [comment]
According to [this](http://stackoverflow.com/a/3524270/217959) well rounded answer on Stack Overflow, `void*` arithmetic is illegal in both C and C++. GCC allows it unless `-pedantic-errors` is specified, with Clang emulating GCC (while still regarding it as a GNU extension—[proof](https://llvm.org/svn/llvm-project/cfe/trunk/test/Sema/pointer-addition.c)). For what it's worth, MSVC does not allow `void*` arithmetic.

For byte-stride pointer arithmetic, `Ptr[Byte]` seems most accurate. For passing around opaque addresses, `Ptr[Unit]` or `Ptr[Nothing]` might be more appropriate, as that would discourage pointer arithmetic.

For example: the result of `dlsym(c"div", 0)` would be used to invoke a function, but there's no requirement for pointer arithmetic, which is why it returns `void*` instead of a byte-sized pointer.

**Comment by MasseGuillaume** [comment]
@densh 

If I want to free a Ptr[T] that is not a Ptr[Byte] I need to cast it?

**Comment by densh** [comment]
@nadavwr Neither `Ptr[Unit]` nor `Ptr[Nothing]` match the semantics exactly. Unit one means, that there is a unit value behind the pointer and there isn't, nothing one means that it's not a pointer to anything (this is also how you might type `null` if we haven't had a `Null` type.), which is also not true. `Ptr[Byte]` is the closest least surprising match. 

@MasseGuillaume Yep, that's the same as in C.

**Comment by MasseGuillaume** [comment]
you don't need to cast when you free.

**Comment by MasseGuillaume** [comment]
related: https://github.com/scala-native/scala-native/issues/331#issuecomment-257863890
