### ISSUE TITLE
Improve CodeGen to use less memory by writing code in chunks

### ISSUE THREAD

**Issue by jonas** [scala-native/scala-native#658]
CodeGen uses a lot of memory (>32MB for certain files) when generating the `.ll` files. Part of the reason is that it requires two passes, one to generate the body and one to generate the prelude+dependencies. 

While commit 27c2361e5cd5c4ed9e7dd693d6e733b46ab303ca changed codegen to no longer use statically allocated buffers it would be nice to investigate whether we can generate the `.ll` code in one pass by reordering instructions to be aware of dependencies and thereby write code to disk in 1MB chunks using a CharBuffer to not pay the StringBuffer => byte[] => ByteBuffer tax

Related to #132

**Comment by densh** [comment]
Codegen is 2-pass mostly due to forward declarations in prelude. First we emit the body of the LLVM module, and then for every use of global that's not defined in this module, we remember a forward declaration to be included in prelude. We gather information about uses of globals during generation of the body, but this can also be done in separate traversal that just walks all the definitions and collects globals that were used, separately from the code generation.

**Comment by WojciechMazur** [comment]
Resolved in #1979
