### ISSUE TITLE
Reimplement regular expressions in Scala

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#873]
This will let us address two problems we currently have with RE2:

1. People find it rather hard to setup the environment in cases when RE2 is not available via system package manager.

2. RE2 supports only a subset of the regular expressions supported by JDK. 

Alternative is to use another C/C++ library but I'm afraid this is not going to address the first problem.

**Comment by densh** [comment]
Related: #828

**Comment by muxanick** [comment]
Only problem is install gcc 4.9+

**Comment by muxanick** [comment]
Ubuntu 16.04 has gcc 5.4 by default

**Comment by japgolly** [comment]
If people are finding it hard to configure their environment, it might be an idea to provide a docker image with an environment setup with everything needed for scala-native compilation.

**Comment by japgolly** [comment]
And to clarify: I don't mean put the whole world and SBT in a docker image, I just mean all the lower-level stuff like gcc/clang/rc2/???. Then SBT can invoke those executable via docker instead of searching for them locally. With the right args it's trivial to grant Docker limited read and/or write FS access.

**Comment by ekrich** [comment]
We do have a docker setup that works. The one problem I had was that it runs as root in nixos and that makes two tests fail. I tried to add a user and use it but couldn't figure out how to do it.

**Comment by densh** [comment]
The whole point of Scala Native is to run immediately on the target machine without anything in-between your code and the hardware. Having to require docker for standard usage goes quite a bit against this spirit.

**Comment by ekrich** [comment]
I see the point. I think there are possible 2 reasons for using docker that I see.

1. You can have a Docker setup so you can run a different OS for development. 
2. If you have a ScalaNative app and you want to spin up and down instances then you could run in Docker and have Kubernetes or Swarm orchestrate.

I'm surely not an expert in this area and this isn't really related to regex I suppose.

**Comment by MasseGuillaume** [comment]
@densh 

take a look at: https://swtch.com/~rsc/regexp/regexp1.html
the TL;DR; is that you don't want backtracking if you want linear, terminating regexes. the jdk support backtracking (via \1 etc)

I think reimplementing RE2 in Scala is the way to go. Also if you choose RE2j as a reference for the implementation make sure it matches the RE2 implementation in C++ because RE2j is a port of RE2 go-lang wich is a port of RE2 C++ (https://github.com/google/re2j#who-wrote-this).

**Comment by shado23** [comment]
> Also if you choose RE2j as a reference for the implementation make sure it matches the RE2 implementation in C++ because RE2j is a port of RE2 go-lang wich is a port of RE2 C++ (https://github.com/google/re2j#who-wrote-this).

Yes, RE2j performance is unfortunately pretty garbage. (see https://github.com/google/re2j/issues/12)
I was surprised by this as well, but even in extremely simple benchmarks (on JVM) it's almost 10 times slower than java.util.regex. (C++ RE2 is probably ok, I didn't check.)

I don't think it would be a good idea to go with RE2j as is. It would probably take a lot of work to make it competitive. While it's certainly a good goal to keep dependencies to a minimum, are you sure you want to take on the additional work of maintaining your own regex engine instead of using one of the existing libraries?

The main upside of RE2 in general is that it doesn't suffer from exponential blowup (because it doesn't support back references), but that makes it inherently incompatible with Java Regexes. It remains to be seen if this incompatibility is important or not. One option might be to replace it with pcre-jit, which does and is also reasonably fast. If you can get away with being incompatible, you might as well go the whole hog and switch to hyperscan, which is a lot faster than everything else. (https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/)

**Comment by densh** [comment]
Fixed in #1498
