### ISSUE TITLE
Provide conversions between CString and java.lang.String

### ISSUE THREAD

**Issue by densh** [scala-native/scala-native#98]
Add support for additional APIs:

- [ ] `def fromCString(str: CString): String = ...`
- [ ] `def toCString(str: String): CString = ...`

For clarity they should not be added implicitly to normal strings but rather be stand-alone top-level functions in `scalanative.native`.

**Comment by sjrd** [comment]
From an API perspective, I would suggest pimps so that the user site is `s.toCString` and `s.toString`. That's how both Scala/JVM and Scala.js expose conversions between Scala types and their respective host types.

**Comment by densh** [comment]
This one has just been un-blocked.

**Comment by densh** [comment]
Related: https://github.com/scala-native/scala-native/issues/130

**Comment by phdoerfler** [comment]
How does a CString handle Unicode (codepoints)? In particular: does this need special attention in the conversion? Is this trivial? What about Unicode above the basic multilingual plane? Should we use CharSequence instead of String?

**Comment by sjrd** [comment]
Unlike Java/Scala Strings, which are UTF-16 by contract, C strings do not have a definite encoding. They're almost more sequences of bytes than characters.

Therefore, I think converting to/from Scala and C strings should be encoding-dependent. Probably requiring an implicit `Charset` in scope or something?

**Comment by siriux** [comment]
I tried a quick test to convert from String to CString, but when I try to getBytes from a string it gives a link error because of unimplemented java.nio classes.

Is the same type of errors you get when trying to use println. So I think it's worth it to implement the base of java.nio first. At least Buffer, ByteBuffer, CharBuffer and Charset.

**Comment by siriux** [comment]
I think that #183 is required before a real attempt to this issue.

**Comment by densh** [comment]
NIO charsets are already merged, but we're still blocked by https://github.com/scala-native/scala-native/issues/213

**Comment by fbertra** [comment]
Hi, 

I'm almost sure that issue https://github.com/scala-native/scala-native/issues/213 (Reflective instantiation of arrays) isn't blocking this issue.

The problem occurs because object `niocharset.UTF_8` extends `java.nio.charset.Charset ` and pass an Array for parameter `aliases: Array[String]` in `CharSet `contructor.

```
private[niocharset] object UTF_8
    extends Charset("UTF-8",
                    Array( // scalastyle:ignore
                          "UTF8",
                          "unicode-1-1-utf-8"))

abstract class Charset protected (
    canonicalName: String, aliases: Array[String])
    extends AnyRef
    with Comparable[Charset]
```

Somehow, the array `aliases` is transform by an implicit to an `collection.mutable.WrapperArray` and it raises an exception when creating a class `WrapperArray::ofRef[T <: AnyRef](val array: Array[T])`. `WrapperArray` is heavily based on reflection, so a solution could be to implement java and scala reflection in scala-native.

But a much faster solution for this issue is to change the type of parameter constructor `aliases` to an `scala.List`.

I'm preparing a PR with this change.

**Comment by sjrd** [comment]
> But a much faster solution for this issue is to change the type of parameter constructor aliases to an scala.List.

Unfortunately, that would not be binary compatible with the JDK API.

**Comment by fbertra** [comment]
> Unfortunately, that would not be binary compatible with the JDK API.

I tried to remove the parameter `aliases `entirely and everything compiles and runs just fine.  So nobody uses it, atm.

But it's true that someone could create a new charset and could miss this parameter.

**Comment by densh** [comment]
#213 has just been fixed unblocking this issue.

**Comment by fbertra** [comment]
I volunteer to finish this issue if no one is currently working on it.

**Comment by ritschwumm** [comment]
please use an explicit charset, and only an explicit charset for conversion.
i've seen way too many errors in java where people left out the charset
with InputstreamReader, new String(..) and friends where they should
have not.

**Comment by fbertra** [comment]
@ritschwumm the methods signatures are, atm:

```
def fromCString(cstr: CString)(implicit charset: java.nio.charset.Charset): String
def toCString(str: String)(implicit charset: java.nio.charset.Charset): CString
```

But, there is no `implicit val cs: Charset = ...` defined anywhere in the library.  So, it will be the caller responsability to define the Charset he needs.  So, there is no default Charset like in JVM land.

Is it OK?

**Comment by ritschwumm** [comment]
@fbertra dangerous, imho. you move a method using this to another class, and suddenly it behaves completely different because a different implicit charset is in scope. you'll never know before it's too late.

**Comment by densh** [comment]
Fixed in https://github.com/scala-native/scala-native/pull/254
